### ISSUE TITLE
Site: setup automated testing

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#1003]
Visual regression, maybe also things like Lighthouse and/or aXe (to monitor for a11y issues, performance, SEO, etc.).

**Comment by JohannaJoergensen** [comment]
18 Jan - work in progress; storybook is working with docusaurus - pending chromatic setup

**Comment by JoanaMMoreira** [comment]
PR for Storybook/Chromatic setup ready for review: https://github.com/jpmorganchase/salt-ds/pull/1028
