### ISSUE TITLE
Fix outstanding design QA issues in ag-grid theme

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#1008]
### Package name(s)

AG Grid Theme v1.0.0 (@salt-ds/ag-grid-theme)

### Description

This [Figma](https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=2406%3A110647&t=L9BNtLzadE39EQ0G-0) document outlines some of the outstanding small issues:

- [x] editable cell focus corner flag is clipped
- [ ] ~~Compact HD density~~
- [x] Numerical value alignment in editable and non-editable cells

### Steps to reproduce

- [example of corner flag in the editable field](https://storybook.saltdesignsystem.com/?path=/story/data-grid-ag-grid-theme--column-group)
- N/A
- examples of [non editable numeric cell(https://storybook.saltdesignsystem.com/?path=/story/data-grid-ag-grid-theme--column-spanning) and [editable numeric cell](https://storybook.saltdesignsystem.com/?path=/story/data-grid-ag-grid-theme--column-group)

### Expected behavior

- editable cell focus corner flag overlays the border
- Compact HD density story exists
- All cells with numerical values are right aligned

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
What's the status of this?
