### ISSUE TITLE
Data Grid: Basic column sorting

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#1010]
Currently we offer no sorting functionality that exists in every other grid library. As most things with our grid this can be developed in user land with customisable headers but we want to provide and easy and accessible experience out of the box.

Add the ability for a user to sort by a single activating the sort functionality on sortable columns, one at a time. Rows can be sorted based on a column value in ascending and descending order.

Multiple composable sorting columns will not be developed at this time.

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1395
```

**Comment by parsakhan21** [comment]
2/13 - dev in progress - should have PR up soon for review

**Comment by joshwooding** [comment]
Addressing current feedback, dev review needed shortly

**Comment by libertymayc** [comment]
> @feliciackh i noticed the sort arrow icon overlaps the label when resizing the column. can we honor the base padding (per density) on either side of the icon, so there's space between the icon and the ellipses whether left or right-aligned?
> 
> I have screenshots but it keeps failing when trying to upload... not sure why... so will send them via symphony

would you be able to add size specs to the characteristics page for grid so @feliciackh knows where to use which :)

**Comment by joshwooding** [comment]
@bhoppers2008 and @dplsek to catch up on the grid size specs. @feliciackh fixing a bug found in design review

**Comment by dplsek** [comment]
@feliciackh @libertymayc I've added the padding to the 'Density examples' where we show padding. The first column of each grid example includes a sort arrow (scaled as necessary). The left set shows with padding visible and the right set with the padding hidden. The same padding rules apply whether the icon is left aligned in the header or right aligned. Let me know if this works for you. Cool.

Light:
[](https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=827%3A9905&t=Ym8CdkuugSH0Zbt8-1)

Dark:
[](https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=839%3A20398&t=Ym8CdkuugSH0Zbt8-1)

**Comment by feliciackh** [comment]
> @feliciackh @libertymayc I've added the padding to the 'Density examples' where we show padding. The first column of each grid example includes a sort arrow (scaled as necessary). The left set shows with padding visible and the right set with the padding hidden. The same padding rules apply whether the icon is left aligned in the header or right aligned. Let me know if this works for you. Cool.
> 
> Light: https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=827%3A9905&t=Ym8CdkuugSH0Zbt8-1
> 
> Dark: https://www.figma.com/file/xqqKG90bV9yT8xBJvWayzJ/Data-Grid-V1?node-id=839%3A20398&t=Ym8CdkuugSH0Zbt8-1

Yes this is great - thank you! I've used `--salt-size-unit` values instead

**Comment by joshwooding** [comment]
@feliciackh investigating a bug
