### ISSUE TITLE
UITK v33 Work

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1045]
There are a number of breaking changes we intend to make to UITK (Salt's JPM-internal only predecessor) to:

* deliver meaningful improvements to its consumers
* ease their migration to Salt
* simplify our ongoing maintenance of UITK

Since breaking changes require a major version bump, we intend to batch these into a single major release (which will be v33.0.0).

```[tasklist]
### Proposed changes
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1297
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1298
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1296
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1299
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1300
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1301
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1302
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1303
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1304
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1305
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1306
```

```[tasklist]
### Changes not being done
- [ ] ~~Add `@font-face` rules required by Salt into UITK's core CSS (?)~~
- [ ] ~~Support React 18 (?)~~
```

**Comment by joshwooding** [comment]
Supporting React 18, is quite complicated we could do a spike as an initial investigation but due to the significant changes in React I am not confident in being able to achieve this.

**Comment by origami-z** [comment]
Updated release date to Oct 6th (date sent to MTK)

**Comment by origami-z** [comment]
Push out target dates, pending validation from MTK

**Comment by origami-z** [comment]
extending target date as more feedback received

**Comment by joshwooding** [comment]
TS issues still present, still waiting for updates on the font. Moved to Amber

**Comment by origami-z** [comment]
3 Nov - MTK reviewed yesterday, another round of feedback, wait MTK tested

**Comment by shey-v** [comment]
6 Nov - Felicia in conversations with Mo for feedback.

**Comment by joshwooding** [comment]
Type issues have been resolved. MUI peer dependency PR to be reviewed and merged. Only thing left is the fonts work.

**Comment by origami-z** [comment]
17 Nov - MTK running more visual test, found 1 change, awaiting feedback

**Comment by origami-z** [comment]
20 Nov - awaiting feedback

**Comment by origami-z** [comment]
22 Nov - last font PR raised, commit message pending update.

**Comment by origami-z** [comment]
24 Nov - some dev work needed for uitk update from Figma

**Comment by origami-z** [comment]
1 Dec - Build issue sorted, will rebase next on top of develop, will merge after.

**Comment by origami-z** [comment]
6 Dec - `next` PR ready. to be merged `develop`

**Comment by origami-z** [comment]
8 Dec - storybook issue resolved, design changes to match Figma in final PR.

**Comment by origami-z** [comment]
11 Dec - Design went through qa changes, a few last code change needed. Aiming to be released EOD.

**Comment by origami-z** [comment]
Released
