### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1051]
Figma Spec: https://www.figma.com/file/hFCYdor9r1AefRvLPuthMm/Overlay

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] https://github.com/jpmorganchase/salt-ds/issues/2807
```

```[tasklist]
### Features
- [x] Appear on click/trigger
- [x] Support positioning top/left/right/bottom
- [x] Close with internal close button
```

Questions:
- Do we want to align this so all menus are overlays? e.g. dropdown, combobox

**Comment by navkaur76** [comment]
7 Sep - initial design review requested on design assets (spec, component, guide)

**Comment by joshwooding** [comment]
Moving to blocked, work still need to be reviewed

**Comment by origami-z** [comment]
Moving priority, pending design review

**Comment by bhoppers2008** [comment]
@origami-z Nav is going to move this item forwards and make sure design decisions are made so we can get it in a state for dev. With that in mind, presuming we can make those decisions by end of week, what target date can we give this component? 
@navkaur76

**Comment by origami-z** [comment]
Moving this top of backlog. If dev has spare capacity next week, we can pick this up. Or will be the one after next.

**Comment by origami-z** [comment]
23 Oct - in design review

**Comment by origami-z** [comment]
Pushing out target date, so get enough dev time after design review

**Comment by origami-z** [comment]
Push out date to include dev delivery time.

**Comment by joshwooding** [comment]
@bhoppers2008 working on completing the design work

**Comment by origami-z** [comment]
3 Nov - further design changes needed, expect to finish EOD

**Comment by joshwooding** [comment]
@feliciackh reviewing the specs and doing investigation into how other similar components are built. Target date moved to next week.

**Comment by origami-z** [comment]
13 Nov - WIP, talked with @joshwooding last week.

**Comment by origami-z** [comment]
17 Nov - @feliciackh working on other priorities. Push to amber. Dev Component started, focus trap to be the main focus.

**Comment by origami-z** [comment]
20 Nov - working on CSS, focus manager, tests, examples.

**Comment by feliciackh** [comment]
22 Nov - refactored component to use FloatingComponent to enable desktop use, floating focus manager needs reworking due to refactor

**Comment by feliciackh** [comment]
30 Nov - GH PR pending more reviews. Component updated to have focus move into floating element on trigger element press. Previously focus remains on trigger element on trigger element press. Behaviour to be discussed with @bhoppers2008 on Friday Dec 1

**Comment by origami-z** [comment]
1 Dec - PR ready, pending design review. Doc PR is separate.

**Comment by feliciackh** [comment]
Overlay doc issue: https://github.com/jpmorganchase/salt-ds/issues/2807. Please refer to email for link to Word doc
cc @bhoppers2008 @mikearildbrown

**Comment by origami-z** [comment]
4 Dec - PR review, dev to be taken from @feliciackh while OOO

**Comment by origami-z** [comment]
6 Dec - handover needs to picked up.

**Comment by joshwooding** [comment]
20 Dec - Design feedback addressed, had a catch up with @joshwooding. Working on some small changes and then will move to an API refactor

**Comment by joshwooding** [comment]
09/01 - Working on getting a RC ready. Working on changes needed after the floating-ui update. The docs have been updated.
