### ISSUE TITLE
Refactor global site CSS

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#1058]
Breaking down `custom.css` into smaller files and improving overall structure

**Comment by JohannaJoergensen** [comment]
26 Jan - work in progress

**Comment by JoanaMMoreira** [comment]
Draft PR here: https://github.com/jpmorganchase/salt-ds/pull/1061, will discuss with the team during our catch up later today

**Comment by JoanaMMoreira** [comment]
PR is ready for review https://github.com/jpmorganchase/salt-ds/pull/1061
