### ISSUE TITLE
Color Palette Exploration

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1110]
- Audit current UITK color palette vs Salt 1 (current) color palette vs Salt 2 (proposed) vs MasterBrand
- Create in-situ comps for 1:1 comparison in both light and dark modes

**Comment by parsakhan21** [comment]
2/8 - Exploration phase - auditing color palette, find way to modify current ones - something that will work across everything. Create plug in (zhihao) to streamline process

**Comment by joshwooding** [comment]
General Plan agreed, course of action being decided on. User Journeys being worked on. Contrast ratios under investigation.

Future Work: Get more realistic examples to use the proposed colors on.
