### ISSUE TITLE
SplitLayout content review

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#1128]
Storybook preview:
https://3b75de3a.saltdesignsystem-storybook.pages.dev/?path=/story/documentation-core-layout-splitlayout--page

**Comment by sion-docs** [comment]
- 2 should be 'two' throughout. 
- Change "The simple usage examples shows ..." to "This example shows..."
- Change "required to be in the opposite..." to "required to be **at** the opposite..."
- Change "we recommend you having a look at..." to "we recommend that you consider using..."
