### ISSUE TITLE
Desktop Support

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1137]
Teams need to have multi-window support with components. This would include features like opening a tooltip in a new window and opening each Cascading Menu list in new windows.

```[tasklist]
### Tasks
- [ ]  Discuss the current abstractions
```

Requirements:

- Injection of window
- Window positioning
- Styling injection

**Comment by mark-tate** [comment]
How do we see this work's priorities dovetailing with List creation ?
