### ISSUE TITLE
Evaluation, OKRs, and Tracking |  Metric Implementation

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1151]
Instrumentation of site of capture recommended measures

Note: 
- Team need to break down work / review the recommendations they are prioritising or rejecting
- CX and data engineers are reviewing recommendations ahead of meeting with team (to be scheduled)

**Comment by parsakhan21** [comment]
Feb 15 - will catch up with site team and update this issue accordingly

**Comment by zdxd** [comment]
nothing to add - awaiting availability from CX/Data Eng

**Comment by zdxd** [comment]
Meeting with CX/Data Eng to refine research brief. 

Have contacted head of UR&A to work out the information they need to prioritise the project,

**Comment by zdxd** [comment]
@JoanaMMoreira have put meeting in to discuss

**Comment by parsakhan21** [comment]
March 2 - will not prioritize right now, but work on this next quarter

**Comment by james-nash** [comment]
From @zdxd on 11. April:

> Following on this note, here is collation of our metrics discussion end of last year.
> 
> The big question remains what tools can we use!
>  
> Highly recommend behavioural/click-stream/event-based analytics before anything subjective.
>  
> Options for behavioural are: 
> - Google Analytics 4
> - Adobe 
> - Amplitude
> - Mixpanel
> - @JoanaMMoreira did you conclude whether there were additional options with Mosaic? 
>  
> The big barrier to using these is simply, which is approved and can we get an account set up? I think @AnniaT was looking into this but worth taking a look from your specialist perspectives too.

**Comment by james-nash** [comment]
From @JoanaMMoreira on 11. April:

> There are no analytics options with Mosaic but we can use [Vercel’s](https://vercel.com/docs/concepts/analytics).

**Comment by james-nash** [comment]
From @zdxd on 12. April:

> Great – and Vercel does not offer event tracking so for this purpose we would need another solution
> 
> What is the best way to move forward and learn about what is actually avail?

**Comment by james-nash** [comment]
@mikearildbrown, @joshwooding & @mark-tate: Do you have any recommendations for analytics tools that provide event tracking, which we could add to the Salt website?

Also, if you're aware of any restrictions on which provider(s) we can use, that would be helpful. Thanks!
