### ISSUE TITLE
Visual regression restructure

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1166]
We need to consider how we want to track visual regression, perhaps changing up where and how we use Chromatic to make better use of tracking changes. 

QA stories also need a rethink, perhaps we want to standardise this to an 'All' story instead of a 'QA' story, for a standard reflection of all densities/modes for the component, and then more specialised visual screenshots selected per component as necessary.

**Comment by origami-z** [comment]
All components are using QA containers now.
