### ISSUE TITLE
Setup Site deployment

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#1180]
After some investigation, Mosaic currently does not support static hosting or the edge runtime, so we cannot use Cloudflare to host the new site.

We've raised these issues to the Mosaic team, but for now, we will use Vercel to host the site.

**Comment by parsakhan21** [comment]
Feb 21 - in progress

**Comment by joshwooding** [comment]
Done; the site is available at https://next.saltdesignsystem.com
