### ISSUE TITLE
Define metadata necessary to populate a community component catalog

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#1195]
If a team or a domain creates a component, and we want to publish it into the catalog, what is necessary to provide a consistent, informed, experience for consuming those components.

e.g.

- Component name
- Common alternate names
- One line description
- Thumbnail image or url
- URL to component guidance doc (can link to Salt satellite site, Figma, Storybook, or a repo)
- Usage documentation follows template Y/N?
- There is a Figma spec and kit Y/N?
- Component has a11y specifications Y/N?
- Component has code Y/N?
- Code passes a11y tests Y/N?

**Comment by shinytoyrobots** [comment]
Connected to #1205

**Comment by james-nash** [comment]
Added this as a task of #1207, which is the epic for a community _component_ index. Also, #1195 seems related, so have added that to the same epic as well.
