### ISSUE TITLE
Define a pattern documentation template for the site

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#1196]
We need a reusable template that can be followed for providing usage guidance on all patterns.

This template will also need to be published and usable by any partners or satellite teams, so that we can start building consistency in pattern documentation regardless of the originating creator of that pattern.

Similar to #1085 (which was for components).

Should interact with domain leaders (e.g. MTK, Payments, etc) for consensus on this.

**Comment by origami-z** [comment]
#1649 ongoing for this
