### ISSUE TITLE
Avatar ADA review

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#1211]

**Comment by Fercas123** [comment]
As per conversation with @maj-stella  changes in PR: 

- [ ] Change default example's aria label for icon. (user avatar)
- [ ] Change role to `img` when children is initials and alternative text is also initials. 
- [ ] Docs: Add information about `aria-hidden` when avatar is used for decorative purposes. 
- [ ] Docs: Alternative text should convey how the avatar is used (for example, if using an avatar with icon, icon's aria label should be descriptive to the avatar context, not the icon context) buildingIcon would become Company Avatar.

**Comment by joshwooding** [comment]
PR has been merged, checking one last thing with @maj-stella
