### ISSUE TITLE
uitk-ag-theme uses same padding in .ag-menu for all densities 

### ISSUE THREAD

**Issue by pedroBlazquez** [jpmorganchase/salt-ds#1222]
### Package name(s)

AG Grid Theme v1.0.0 (@salt-ds/ag-grid-theme)

### Problem
The theme applies the same padding to .ag-menu for all densities. This seems okay for Medium and Low densities, but it looks too big for HD.
I should probably scale accordingly for each of the different densities.

This value is defined here:
https://github.com/jpmorganchase/salt-ds/blob/main/packages/ag-grid-theme/css/_uitk-ag-theme-mixin.scss#L94

#### Low density
![image](https://user-images.githubusercontent.com/15366204/221878999-0519bb5a-ff46-48a3-ae52-7dce310ae324.png)

#### Medium density
![image](https://user-images.githubusercontent.com/15366204/221879077-4f20b7f1-b74b-4e0d-b2b5-784efb6e63b5.png)

#### High density
(Please ignore the fact that the dropdown looks bigger for HD, there is a fix for that already)
![image](https://user-images.githubusercontent.com/15366204/221880469-8ede83eb-9895-4dae-99a0-2021db1b8014.png)

### Steps to reproduce

1. Visit [ag-theme story](https://storybook.saltdesignsystem.com/?path=/docs/documentation-data-grid-ag-grid-theme--page)
2. Scroll to "floating filter" story
3. Switch the theme to "UITK"
4. Click on the filter icon.
5. Repeat for the different densities

### Expected behavior

- Padding for menu scales based on density

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by bhoppers2008** [comment]
Hi Pedro,

For internal padding on your 'container' use 3xsize-unit. If you can reference the size token directly from the salt foundation that would be preferable, otherwise the px values (at 1x) for size-unit are:
hd = 4px
md = 8px
ld = 12px
td = 16px

So for HD, you would have 12px padding.

As a guide you can use the following multipliers of size-unit for other spacing attributes:

- between page title and a page description = 3x
- between title and container content = 4x
- between individual components in the same group/section = 2x
- between distinct sections/groups in your container = 4x

Cheers,
Ben

**Comment by origami-z** [comment]
This is due to the decision of making like-for-like UITK panels, i.e. 20px was the universal padding used across densities. Is there a plan to change that?

**Comment by parsakhan21** [comment]
April 11 - raised a PR (bug in AG grid)

**Comment by joshwooding** [comment]
@bhoppers2008 to begin looking at this tomorrow

**Comment by dplsek** [comment]
@ZarkoPernar based on Ben's reply, the internal padding of the container is 3x, so triple the current value for each density (snippets below). This is likely going to look too big but if we can see it, that would be great. Perhaps this will need to go to 2x and we need to define several multipliers that are based on the size of the container... just one idea. In any case, this is something we are currently trying to get sorted and defined in the principles.

**Comment by joshwooding** [comment]
> @ZarkoPernar based on Ben's reply, the internal padding of the container is 3x, so triple the current value for each density (snippets below). This is likely going to look too big but if we can see it, that would be great. Perhaps this will need to go to 2x and we need to define several multipliers that are based on the size of the container... just one idea. In any case, this is something we are currently trying to get sorted and defined in the principles.

Hey @dplsek, there's already a PR up with the changes. You should be able to see them here: https://4b9c7ff1.saltdesignsystem-storybook.pages.dev/?path=/story/data-grid-ag-grid-theme--floating-filter&globals=density:touch. When changing densities you have to close and re-open to filter to see the new padding

**Comment by dplsek** [comment]
Hmmm, I'm still seeing the same thing as before which shows the padding as - 4/8/12/16 - not the 3x Ben specified - 12/24/36/48. It won't let me attached the images for some reason, so I will email.

**Comment by bhoppers2008** [comment]
I missed @origami-z's comment earlier. We do have a concept of scaling padding in the UITK already. It's just inconsistently applied. @dplsek in Salt we've reconciled this value to --size-container-spacing. It's currently 3*size-unit to align with it's use in UITK. If we feel this is too big, we could drop to 2*. See what you think when the PR is updated.

**Comment by ZarkoPernar** [comment]
@dplsek Is that the values you want or the values you are seeing on [this branch](https://4b9c7ff1.saltdesignsystem-storybook.pages.dev/?path=/story/data-grid-ag-grid-theme--basic-grid)? If its the final values you want I can just hard code them. We don't have characteristics and all that jazz for the ag-grid theme anyways.

**Comment by ZarkoPernar** [comment]
Oh, from your screenshot @dplsek I can see you are looking at the salt not uitk theme. Use the switcher above the grid to switch to uitk theme.

**Comment by dplsek** [comment]
Hey @ZarkoPernar, adding these images for reference per our discussion. Ideally, we would follow this for both UITK and Salt regarding the spacing in all menus, with x values equalling HD-4, MD-8, LD-12, TD-16. Let me know if you have questions. Thanks.


![Image](https://github.com/jpmorganchase/salt-ds/assets/110917213/a2b486c2-d8ef-4918-a123-dcee99e6738a)



![Image](https://github.com/jpmorganchase/salt-ds/assets/110917213/5f59db54-2410-42c9-b25a-2022a00628d8)



![Image](https://github.com/jpmorganchase/salt-ds/assets/110917213/9e788049-84d2-4e3c-bacf-605a6d7b48db)



![Image](https://github.com/jpmorganchase/salt-ds/assets/110917213/eb3d98f0-359b-4e53-affc-d41c6fd04865)
