### ISSUE TITLE
Salt WYSIWYG

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#1233]
We should create a WYSIWYG sandbox where consumers can experiment with the design system components.

This can build on top of previous work in creating a WYSIWYG and can be hosted on the Salt site.

Remaining work:

- [ ] Move WYSIWYG code into salt repo
- [ ] Configure WYSIWYG to use components from Salt
- [ ] Modify UI of WYSIWYG so it is using salt components (where possible)
- [ ] Host WYSIWYG on Salt site

We should also consider adding a few high value features e.g

- [ ] Loading a canvas from url (so created work is sharable)
- [ ] Store/load canvas in local storage
- [ ] Save canvas as re-usable composition
- [ ] Save canvas as re-usable component

**Comment by joshwooding** [comment]
Out of scope for now
