### ISSUE TITLE
DS Education - Part 1: Primers

### ISSUE THREAD

**Issue by parsakhan21** [jpmorganchase/salt-ds#1250]
- [ ] About DS intro doc
- [x] For Designers
- [x] For Developers

**Comment by parsakhan21** [comment]
**Design Primer** - Paul is leading an effort to define some of the universal design principles, and identifying commonalities of what is “good” design across existing UITK efforts, and what we might provide more definition to Salt.
 
He’s leading some workshops this week that Jean has organized (which is why all the designers are unavailable for daily updates!).
 
Defining these principles will add content to both UITK and Salt – it’s about us becoming more clearly opinionated on how teams should build good applications.
 
Paul can provide the details of that work.
 
It will lead to an outcome of clearly defined universal principles of design in CIB.
 
That should then lead into a general design system primer (ideally one that takes in both UITK and Salt, at least initially), that gives both context and initial guidance – something that’s very easily shareable to, for example, a new hire.

**Tech Primer -** Josh and Robin have discussed the desire to create developer primer(s) for UITK and for Salt, and subsequently step by step tutorials that might enable a developer to get a certification or record of completion.
 
For the primers, fundamentally they should be a combination of existing developer “getting started” information, plus some additional context on what the toolkit/Salt are for, why they exist.
 
For tutorials – we already have an environment set up for Toolkit, I believe – do we have something that could be repurposed to be an easy, but objectively “complete/incomplete” step by step tutorial.

**Comment by parsakhan21** [comment]
March 24- josh to review/make sure all look ok re: tech primer ; design primer - ?

**Comment by libertymayc** [comment]
31/3 PR's waiting for review and builds to be fixed - @joshwooding investigating

**Comment by joshwooding** [comment]
@bhoppers2008 given feedback. Nearly done

**Comment by zdxd** [comment]
@navkaur76 and @pseys tracking issue for advising on behaviourally informed SALT primer https://github.com/jpmorganchase/salt-ds/issues/1523  do loop me in so I can help where I can
