### ISSUE TITLE
Consuming app CSS loading order error

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#127]
<h2 id="symptom">Symptom</h2>

CSS override from a consuming app will behave differently during a dev build and a prod build, due to CSS loading order issue.

<h2 id="reproduce">Reproduce</h2>

Using this [test repo](https://github.com/origami-z/uitk-modular-tests) as an example, clone the repo and run it locally `yarn && yarn start uitk-app` (modular unfortunately doesn't work with StackBlitz or Code Sandbox) and compare with prod build on [github pages](https://origami-z.github.io/uitk-modular-tests/) (or build and `yarn modular serve uitk-app` yourself).

Observe the Button position, where dev build would be on top right and prod build would be under the card.

Dev build, local

![Dev build, local](https://user-images.githubusercontent.com/5257855/170245991-2b91c579-fd15-4330-83d9-572cee953edf.png)

Prod build, GitHub page

![Prod build, GitHub page](https://user-images.githubusercontent.com/5257855/170245826-480b2974-ec7d-4284-b28e-1d3b3dec79d0.png)

<h2 id="why">Why</h2>

In the example repo, Button is styled with a custom class like below

```jsx
<Button className="AbsoluteButton">
```

```css
.AbsoluteButton {
  position: absolute;
  right: 0;
  top: 0;
}
```

During dev build, `index.css` is loaded last, followed the order of code

```js
import App from './App';
import './index.css';
```

![dev build style loading](https://user-images.githubusercontent.com/5257855/170246712-0c9b6764-3a75-4b0e-935b-163265e7ac6d.png)

During prod build, CSS is extracted into a static file `/static/css/main.0718f2f3.css` (contains uitk-theme CSS and `index.css`) which is loaded before style injected uitk component CSS.

![prod build style loading](https://user-images.githubusercontent.com/5257855/170248981-fd71c729-3870-475a-b3fe-a2d02041ce2b.png)

So if looking into `dist/jpmorganchase-uitk-core/dist-es/packages/core/src/button`, there is a `Button.css.js` and Button CSS will be loaded into `head` at run time.

<h2 id="potential solution">Potential solution</h2>

<h3 id="option-1">Option 1</h3>

Extract CSS during uitk component build, so consumers can load the CSS like a static asset from theme package.

If we do this, we may as well include both core and lab css into theme css file, to make the theme package representing 'all you need' CSS.

Note that in this approach, all uitk-core/lab CSS will be loaded at once instead of only components being rendered. You may wonder whether this means there are more code being loaded to the browser at run time? Kind of yes and no. Currently all components CSS is bundled in JS as string, so CSS parsing and loading is actually happening after the page is first loaded, which may actually be slower depends on browser strategy. File caching strategy could be another consideration, e.g. for apps, extracting vender css separately maybe beneficial.  

<h4 id="option-1-quick-test">Quick test</h3>

1. Modify `node_modules/modular-scripts/dist-cjs/build/buildPackage/makeBundle.js` and modify `_rollupPluginPostcss` to use `extract: true` (this [line](https://github.com/jpmorganchase/modular/blob/813c94180efa36af3dce849e11544485a7b84a87/packages/modular-scripts/src/build/buildPackage/makeBundle.ts#L91) of source code)
2. Build packages
3. Observe `dist/jpmorganchase-uitk-core/dist-es/index.css` being created
4. Copy and replace build files to the sample app `node_modules`
5. Import `import '@jpmorganchase/uitk-core/dist-es/index.css';` in sample app code
6. Observe Button rendered at the correct position in both dev and prod build

<h3 id="other-options">Other options</h3>

Given uitk consumers will be using all types of building tools (CRA, modular, webpack, rollup, etc.), we can't assume certain things being done at the tooling level.

**Comment by origami-z** [comment]
This should be covered by the new `InsertionPointProvider` introduced by #1697

**Comment by joshwooding** [comment]
This is either fixed or will be covered by https://github.com/jpmorganchase/salt-ds/issues/2532
