### ISSUE TITLE
Component "gallery" index page?

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#1288]
When we build out our component index and documentation on the site, should we have a thumbnail gallery (the browsable index), a.k.a. https://polaris.shopify.com/components, or https://carbondesignsystem.com/components/overview/, for easy browsing?

(...or should we be driving earlier than later towards an entirely integrated index - comprising both "core" components and patterns built by us, and the community built assets too)

**Comment by james-nash** [comment]
I'm thinking this could be a precursor to the community component index #1207. I.e. first step is design and build a nice component gallery page that lets people quickly browse Salt's own components. Then, the second step is to update it to display Salt and community-made components (along with whatever additional filter options and info may be needed).
