### ISSUE TITLE
UITK - Replace TTF font files with `@fontsource` packages

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1302]

**Comment by joshwooding** [comment]
@feliciackh started work on this now

**Comment by joshwooding** [comment]
Working on changing the css generation script

**Comment by joshwooding** [comment]
@feliciackh build is up, but working on getting the canary release

**Comment by feliciackh** [comment]
Reached out to Christian @ MTK to test out canary release, will hear back once he has an update on his team's availability

**Comment by origami-z** [comment]
Move to Red due to large time miss from original estimation. Updated to new date EoW 6th Oct.

**Comment by origami-z** [comment]
@feliciackh tested with CRA/Vite/Kickstart templates.
