### ISSUE TITLE
Export SVGs (new icons) and add them to GitHub

### ISSUE THREAD

**Issue by ivan-calderon** [jpmorganchase/salt-ds#1339]
Export SVGs of the new icons added to [Salt Icons](https://www.figma.com/file/9laF7Zn75aUMNsqSqRgAuX/Salt-Icons?node-id=0%3A1&t=XfUHlzT9KA64yrRy-1) library.

**Comment by ivan-calderon** [comment]
Icons to be added/updated to GitHub:

- accessible
- cart
- hospital
- man
- man-woman
- medical-kit
- pot-food
- stethoscope
- storefront
- success (update)
- tote
- utensils
- woman

**Comment by pseys** [comment]
@joshwooding Is this something someone could sort out? Hopefully its a really quick release as its just a handful of icons that need adding to the library.
