### ISSUE TITLE
User test the page template and designs

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#1349]
- [x] Shey to prep 3 x prototypes for user testing sessions
- [x] Zoe to prepare a script 
- [x] Zoe & Shey to recruit participants (no less than 15)
- [x] Zoe to set up user testing sessions and dashboard using user zoom
- [ ] Testing sessions and insight gathering to validate best design option
- [ ] Report created and shared with team
- [ ] Designs to be updated following key findings

**Comment by shey-v** [comment]
22 March - User testing begins, notes and recordings in progress, key insights being gathered

**Comment by zdxd** [comment]
@shey-v this is a duplicate issue - have added info to other ticket and closed this
