### ISSUE TITLE
Add Avatar as Ready on component status page

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1361]
### Area

Website

### The problem

The avatar component has been released as part of the Figma components, but is not reflected within the component status page.

### The solution

Indicate Avatar as **Ready** on the Salt website component status page. 

### Alternatives and examples

Indicate Avatar as **Ready** on the Salt website component status page. 

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
I looks like the change has already been made in the code. I guess we just need to publish the updates. On it...

**Comment by joshwooding** [comment]
Done
