### ISSUE TITLE
Data Grid Editable Cell not updated after blur

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#1372]
### Package name(s)

Data Grid v1.0.0 (@salt-ds/data-grid)

### Description

After editing a cell value, clicking away will revert cell value instead of accepting it

### Steps to reproduce

1. Go to data grid [storybook](https://storybook.saltdesignsystem.com/?path=/story/documentation-data-grid-data-grid--page)
2. Found "Editable cells" example
3. Double click any of the editable cell to enter edit mode
4. Make some changes to the value
5. Click away to other cells
6. Cell value reverted to original value

### Expected behavior

Cell value changed to new value entered, unless used "Esc" key

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by AmeyDagaria007** [comment]
@james-nash  @origami-z  if possible i can work on this ./Assign

**Comment by origami-z** [comment]
> @james-nash  @origami-z  if possible i can work on this ./Assign 

Feel free to raise a PR and link to this

**Comment by AmeyDagaria007** [comment]
@origami-z  Raised PR . https://github.com/jpmorganchase/salt-ds/pull/1434 . First PR so not knowing the convention your guidance would be highly appreciated
