### ISSUE TITLE
App icon + Favicon

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1386]
*Favicon*
- May only exist as Design guidance
- Jean mentioned Edward had created guidance for Favicon use within an app (needs review)

*App icon*
- Existing component (design only, exists within DP)
- Designed by UITK team but never implemented in code
- Provides an 'avatar-like' representation of an App/Product
- Inline with the Characteristics should be changed to adopt the Categorical color palette instead of primary palette

**Comment by pseys** [comment]
https://www.figma.com/file/HPKpUv2Jm4euJtrgjFhOnP/FavIcons?node-id=198%3A3884&t=cuhl89xm6wy3qjpP-1

**Comment by origami-z** [comment]
Close, seem to be completed
