### ISSUE TITLE
Data Grid: Add button cell to Figma component

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#1394]
**Light:**
https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/S3KmWEEmAwHvYq1jS6KolU/Salt-Light-Components?node-id=16%3A3068&t=zyvRpo1HQY5Q7vD7-1

**Dark:**
https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/XbiIKywcLXM9UpxiAwteqB/Salt-Dark-Components?node-id=4780%3A31740&t=ubLlhk55pjLc0DFG-1

**Comment by joshwooding** [comment]
Creating a sandbox and adding docs - ETA Friday

**Comment by dplsek** [comment]
March 31 - Figma components and QA playground have been completed; reviewed with Ben; and merged into the main branch

**Comment by bhoppers2008** [comment]
@parsakhan21 closing this. It's complete.
