### ISSUE TITLE
ComboBox stops working when source changes

### ISSUE THREAD

**Issue by cheemcheem** [jpmorganchase/salt-ds#1404]
### Package name(s)

Lab v1.0.0-alpha.0 (@salt-ds/lab)

### Description

Labs version: `@salt-ds/lab@^1.0.0-alpha.1` (the changelogs for later labs versions didn't mention any ComboBox changes so didn't check those).

If the `source` prop is not populated or is an empty array on the initial render, the `ComboBox` will act weirdly when the source is available.

E.g. when the value for the `source` props loads or is set:
* Then clicking the input will show the source items.
* But searching will fail.
* And clicking the input again after clearing the search will not show any search items.
* And it will remain in this state until rerendered.

### Steps to reproduce

Minimal example:

```tsx
const TestComponent: React.FC = () => {
  const [source, setSource] = useState<string[]>([]); // useState<string[]>() also causes the same issue
  useEffect(() => {
    const timeout = setTimeout(() => setSource(['a', 'bb', 'cc', 'abc']), 5000);
    return () => void clearTimeout(timeout);
  }, []);
  return <ComboBox source={source} />;
};
```

When the value for `source` is set after 5 seconds, the issues noted in the description will be present.

### Expected behavior

The `ComboBox` should not break when the `source` prop changes.

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by heswell** [comment]
I ran into this issue too and have fixed it locally. I'll try and find some time to raise a PR
