### ISSUE TITLE
Radio ADA review

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#1411]

**Comment by maj-stella** [comment]
Url: https://628e27029fcf95004a62cafd-njbawyhizg.chromatic.com/?path=/story/lab-radio-button--vertical-group

Tested with NVDA and Jaws in Chrome Version 111.0.5563.110 (Official Build) (x86_64). NVDA and Jaws announcement as expected.

Note: Jaws has unusual keyboard behaviour which differ from the standard keyboard interaction.

There are only two slight changes which need to be addressed:
1. role=“radiogroup” in the `<fieldset>` element is not needed. `<fieldset>` is a native element for grouping and does not require role=“radiogroup”.

2. `<legend>` element for labelling the group.

![Image](https://user-images.githubusercontent.com/112501956/229583923-c797bfc7-8574-444e-bae1-6feae0484eaf.png)

**Comment by joshwooding** [comment]
@maj-stella to do one final check

**Comment by maj-stella** [comment]
@alycrys Thanks. All done
