### ISSUE TITLE
Checkbox ADA review

### ISSUE THREAD

**Issue by ImmanuelBaskaran** [jpmorganchase/salt-ds#1414]

**Comment by maj-stella** [comment]
**Figma:** 
https://www.figma.com/file/hWEpxUvJlNV6xy9pVDgxGT/Checkbox?node-id=513-4169

**Storybook:** 
https://9299b7df.saltdesignsystem-storybook.pages.dev/?path=/story/lab-checkbox--checkbox-variations
 
https://9299b7df.saltdesignsystem-storybook.pages.dev/?path=/story/lab-checkbox--horizontal-group
 
https://9299b7df.saltdesignsystem-storybook.pages.dev/?path=/story/lab-checkbox--long-text-group

**Comment by joshwooding** [comment]
@maj-stella to update the ticket with changes needed

**Comment by maj-stella** [comment]
Browser: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
Screen readers: NVDA 2019.2.1 and Jaws 2022

Here are some changes which need to be addressed for Url: https://9299b7df.saltdesignsystem-storybook.pages.dev/iframe?id=lab-checkbox--checkbox-variations&viewMode=story

1. Please check ‘indeterminate’ word with the Content Design team. Language needs to be clear and simple.
2. Add some spacing between checkboxes for better readability. 
3. aria-checked is not needed as the native html element is used which already provide this information (please see the screenshot below)
4. Indeterminate checkboxes which are not disabled, need to have all three states (checked, unchecked, and indeterminate) keyboard accessible. E.g when you press Spacebar it should change the state, cycle through different states. At the moment the indeterminate checkbox is static, a user is not able to change the state by pressing the spacebar. (please see the screenshot below)
5. Please check with the User research team usability of checking/unchecking error checkboxes.(Please see the screenshot below)


![Image](https://user-images.githubusercontent.com/112501956/230143838-cfced5d2-600d-42bf-866d-a8871ba36727.png)



![Image](https://user-images.githubusercontent.com/112501956/230144204-f3e6bf99-b858-49c0-accc-9a0dc08710c6.png)



![Image](https://user-images.githubusercontent.com/112501956/230144362-e1643154-e3a5-4b68-85b4-d7c23538aa07.png)

**Comment by maj-stella** [comment]
@ImmanuelBaskaran 
Urls:
https://9299b7df.saltdesignsystem-storybook.pages.dev/?path=/story/lab-checkbox--horizontal-group

https://9299b7df.saltdesignsystem-storybook.pages.dev/?path=/story/lab-checkbox--long-text-group

Only one little change is needed: aria-checked is not needed as the native html element is used which already provide this information. Please delete aria-checked in `<input>` elements.

**Comment by parsakhan21** [comment]
April 11 - dev made changes; nav making some design updates re: ADA, shoudl be done today

**Comment by ImmanuelBaskaran** [comment]
@maj-stella 

URLs for review:

https://316a45cd.saltdesignsystem-storybook.pages.dev/?path=/story/core-checkbox--default

https://316a45cd.saltdesignsystem-storybook.pages.dev/?path=/story/core-checkbox--indeterminate

https://316a45cd.saltdesignsystem-storybook.pages.dev/?path=/story/core-checkbox--uncontrolled-group

**Comment by maj-stella** [comment]
2, 3, and 4 issues raised above have been fixed. Please could you confirm that 1 and 5 have been addressed? Thanks

**Comment by parsakhan21** [comment]
April 12 - sent new build links for review

**Comment by maj-stella** [comment]
@ImmanuelBaskaran 

Please could you give me a link to recheck the point 5? In 'Checkbox variations' they stay in an error state if you change the state check/uncheck/partially check. Thanks

**Comment by ImmanuelBaskaran** [comment]
@maj-stella, I should have clarified that it would be up to developers using the Checkbox component to implement what I've described earlier. We just provide the functionailty to display this error state.

**Comment by maj-stella** [comment]
@ImmanuelBaskaran Awesome! Thank you for clarifying.

**Comment by ImmanuelBaskaran** [comment]
@maj-stella 

https://885a28ef.saltdesignsystem-storybook.pages.dev/?path=/story/core-checkbox--error

I've made the change to the example anyway.
