### ISSUE TITLE
Deprecate disabled states on Accent foreground and border

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1417]
To align with code change we need to add: 
- accent border disabled
- accent foreground disabled

The following needs to be updated:
- Figma characteristics doc
- Figma light palette
- Figma dark palette

**Comment by joshwooding** [comment]
@pseys Was disabled for Progress?

**Comment by libertymayc** [comment]
yeah - I think it was for spinner and progress, which we decided to remove disabled state from both

**Comment by pseys** [comment]
Thanks for the clarification @libertymayc - so does that mean we can cancel this issue and remove the tokens from code?

**Comment by libertymayc** [comment]
yes, can we add to the sheet as it's a theme change so I guess we wont be doing it now as nothing relies on it? cc @joshwooding

**Comment by pseys** [comment]
@libertymayc @joshwooding  Shall we change this issue to 'remove' rather than 'add' then?
