### ISSUE TITLE
Data Grid: Create Figma guide for sortable header cell and button cell

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#1431]
Figma branch:
https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/WMrhmt3SRUDw7XFrRXTKb1/Salt-Figma-Component-Guides?node-id=2%3A2&t=2cb8n12AaLXYG0XG-1

**Comment by dplsek** [comment]
@bhoppers2008 I added these two art boards #13 and #14 to the guide page for Data Grid. Have a look and make any amends you think is necessary:

https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/WMrhmt3SRUDw7XFrRXTKb1/Salt-Figma-Component-Guides?node-id=421%3A9534&t=v222Yfbl10zGEQIt-1

https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/WMrhmt3SRUDw7XFrRXTKb1/Salt-Figma-Component-Guides?node-id=421%3A9534&t=v222Yfbl10zGEQIt-1

**Comment by parsakhan21** [comment]
April 4 - merged to main file; a few other things to add - will publish by eod tomorrow ; ben to check guide page re: instrucitons

**Comment by dplsek** [comment]
April 12 - Ben merged and released all guidelines
