### ISSUE TITLE
TOC links for H3s are not indented

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1439]
On the Mosaic port of the right-hand table of contents links (as used on the design & dev getting started pages) don't indent links for lower heading levels, thus making it impossible to see the structure of the outline there.

On the Docusaurus-based site this works as expected.

![side-by-side screenshots of current and new TOC implementations, with the missing indentation highlighted in the current one](https://user-images.githubusercontent.com/16718916/229479738-2e11450a-ba57-4737-bfbf-3ac6452fd121.png)

**Comment by lilyvc** [comment]
this is indented now https://www.saltdesignsystem.com/salt/getting-started/developing can we close?

**Comment by james-nash** [comment]
Yup! Thanks for letting me know. Closing the issue now :-)
