### ISSUE TITLE
Site image alt texts not appearing in HTML

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1440]
It seems none of our `<img>` elements on the Mosaic site have `alt` attributes. Thing is, as far as I can tell, `alt` texts _are_ being supplied in the source code to the Mosaic `<Image>` component. So, this may well be a Mosaic bug rather than something in our site's code.

For example, the code for the hero image on the homepage is like this:

```js
<Image
  className={styles.heroImage}
  src="/img/hero_image.svg"
  alt="hero image"
/>
```

...but the rendered HTML is like this:

```html
<img class="_1upj7i40" src="/img/hero_image.svg">
```

So it looks like the `alt` prop is being ignored. As far as I could tell from a quick skim of the TypeScript definitions, there _is_ an `alt` prop, so dunno why it's not working.

**Comment by joshwooding** [comment]
Fixed
