### ISSUE TITLE
Outcomes and action points from migration workshop

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1482]

**Comment by parsakhan21** [comment]
April 11 - need to speak to Robin to move this fwd

**Comment by zdxd** [comment]
Outcomes from workshop: 

- Research to provide short check-list to create behaviourally informed migration "getting started" / PRIMER docs  

Outcomes from migration report:

-  Exploratory research to determine effective ways for SALT tooling  to support  with (DP) developer & designer delivery.

Marked this as done and created new issues for above items
