### ISSUE TITLE
Update component page design based on user testing

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1507]
Update component page design in Figma (created in #1175) to incorporate feedback from the user testing of those designs (done by #1349).

This activity will be timeboxed so that we do not delay the implementation. We may therefore not be able to incorporate all recommendations from the testing. Any leftover improvement ideas should be written up as separate GitHub issues which will go into our backlog to be addressed at a later date.

Will update this description once a deadline and scope for this work has been agreed by the team.

**Comment by parsakhan21** [comment]
@james-nash can we close this issue as shey is tracking this work on the platform page - via issue and #1150

**Comment by parsakhan21** [comment]
April 17 - design tweaks in progress
