### ISSUE TITLE
Migration & Community | Designer and Developer Workflows - User Interviews

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1524]
Research to report on high impact opportunity areas for SALT design & development tooling Q2/3

Hypothesis: tooling is one avenue to increase adoption of SALT

```[tasklist]
- [x] create semi-structured topic guide inclusive of Sam agenda & Robin additional areas
- [x] Informal meeting w/ Execute scheduled
- [x] Analysis of results & documentation of results/recommendations
- [ ] Share with the team
```

```[tasklist]
### Deliverables
- [x] Research Brief
- [ ] Deck and Report
```

**Comment by zdxd** [comment]
@shinytoyrobots @joshwooding @bhoppers2008 @mark-tate @MitchLit

Input regarding how we might ensure alignment with DP unification and moderisation & scope to involve service design in research work appreciated

**Comment by zdxd** [comment]
@AnniaT in convo w/ Sam Hampton team to kick off designer workshop

**Comment by zdxd** [comment]
@parsakhan21 Sam put in meeting with design leads to kick off to 

"Can you walk through some of the work you have been doing on ways of working re: UI componentisation / dev partnership for Markets as a Service, Execute, Transact, Client Manager, CaaS etc etc

•	Reality, Issues and challenges of delivery / UI management at scale / over time
•	The things that haven’t worked / caused issues
•	The operational models you’re now following re:
        o	Foundational dependencies ( UITK, MTK, DPD etc)
        o	Application / sub application level Component Libraries (Dumb and Opinionated) 
        o	Aligning Designers / Technologists
        o	Aligning Figma/Code 
        o	Versioning
  " 

Will catch up with @shinytoyrobots if any additional areas for us to probe / ask on our end plus have requested that Sam schedule a US friendly time  to allow for new researcher to attend

**Comment by zdxd** [comment]
Discussion guide created, feedback from @yunjungyeh, will revise ahead of design group call tuesday nxt week. 

Expectation is that group call will provide foundational information & highlight further groups we should interview (e.g., dev side). Expectation is that @ Tara v Jonathan take on as progresses

**Comment by zdxd** [comment]
Same as above research brief/method/analysis & discussion guide ready- convo rescheduled to thursday 22nd

**Comment by tadxd** [comment]
Combining this workstream with sponsor user programme to optimize time and resources.

**Comment by tadxd** [comment]
Awaiting confirmation from AT + RC re: next interviewees.

**Comment by parsakhan21** [comment]
July 14 - analysis of interviews complete; combine this effort with sponsor user program - waiting additional teams of interest before doing roadshow to other LOBs

**Comment by parsakhan21** [comment]
July 24 - sharing results in the upcoming internal demo call

**Comment by tadxd** [comment]
Jul 29: Results shared during team call. Booking time with other groups; coordinating with Annia

**Comment by tadxd** [comment]
Jul-31: booked time with Execute; coordinating with MTK and MCP

**Comment by parsakhan21** [comment]
Aug 2- call with mtk dev team tomorrow; mcp next week (tara out from august 11 - august 20)

**Comment by parsakhan21** [comment]
Aug 4 - mtg call took place yesterday; call with mcp dev on monday and mtk desgin tuesday

**Comment by tadxd** [comment]
21-Aug: MCP Dev and MTK Dev/Design done. SS call tomorrow.

**Comment by tadxd** [comment]
Aug-25 - completed SS call. Conducting analysis.

**Comment by parsakhan21** [comment]
Aug 30 - scheduling additional interviews with product teams; working on analysis  and plans to share at steer co

**Comment by tadxd** [comment]
Sep 1 - analysis continuing

**Comment by tadxd** [comment]
Sep-15: Analysis and interviews ongoing. Scheduled calls with outstanding teams.
