### ISSUE TITLE
Usability: identify Q2 components to test and approach

### ISSUE THREAD

**Issue by zdxd** [jpmorganchase/salt-ds#1530]
Evaluate expectancy of basic components early in build, provide recommendations to inform design iterations

1 - Define components remaining to test (test at least 4 components in Q2)

**Comment by zdxd** [comment]
Component | React | Figma
-- | -- | --
AG Grid Theme | Released in v1.0.0 | N/A
Avatar | Released in v1.3.0 | Ready
Border Layout | Released in v1.0.0 | N/A
Button | Released in v1.0.0 | Ready
Card | Released in v1.1.0 | Ready
Data Grid | Released in v1.0.0 | Ready
Flex Layout | Released in v1.0.0 | N/A
Flow Layout | Released in v1.0.0 | N/A
Grid Layout | Released in v1.0.0 | Ready
Icon | Released in v1.0.0 | Ready
Link | Released in v1.0.0 | Ready
Panel | Released in v1.1.0 | Ready
Salt Provider | Released in v1.0.0 | N/A
Spinner | Released in v1.2.0 | Ready
Split Layout | Released in v1.2.0 | N/A
Stack Layout | Released in v1.0.0 | N/A
Status Indicator | Released in v1.0.0 | Ready
Text | Released in v1.0.0 | Ready
Theme | Released in v1.0.0 | Ready
Tooltip | Released in v1.2.0 | In progress
Checkbox | In progress | Ready
Country Symbol | In progress | Ready
Form Field | In progress | In progress
List | In progress | In progress
Radio Button | In progress | Ready

[AG Grid Theme](https://storybook.saltdesignsystem.com/?path=/docs/documentation-data-grid-ag-grid-theme--page)
Released in v1.0.0
N/A
[Avatar](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-avatar--page)
Released in v1.3.0
Ready
[Border Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-border-layout--page)
Released in v1.0.0
N/A
[Button](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-button--page)
Released in v1.0.0
Ready
[Card](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-card--page)
Released in v1.1.0
Ready
[Data Grid](https://storybook.saltdesignsystem.com/?path=/docs/documentation-data-grid-data-grid--page)
Released in v1.0.0
Ready
[Flex Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-flex-layout--page)
Released in v1.0.0
N/A
[Flow Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-flow-layout--page)
Released in v1.0.0
N/A
[Grid Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-grid-layout--page)
Released in v1.0.0
Ready
[Icon](https://storybook.saltdesignsystem.com/?path=/docs/documentation-icons-icon--page)
Released in v1.0.0
Ready
[Link](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-link--page)
Released in v1.0.0
Ready
[Panel](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-panel--page)
Released in v1.1.0
Ready
[Salt Provider](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-salt-provider--page)
Released in v1.0.0
N/A
[Spinner](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-spinner--page)
Released in v1.2.0
Ready
[Split Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-split-layout--page)
Released in v1.2.0
N/A
[Stack Layout](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-layout-stack-layout--page)
Released in v1.0.0
N/A
[Status Indicator](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-status-indicator--page)
Released in v1.0.0
Ready
[Text](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-text--page)
Released in v1.0.0
Ready
[Theme](https://storybook.saltdesignsystem.com/?path=/docs/theme-about-the-salt-theme--page)
Released in v1.0.0
Ready
[Tooltip](https://storybook.saltdesignsystem.com/?path=/docs/documentation-core-tooltip--page)
Released in v1.2.0
In progress
Checkbox
In progress
Ready
Country Symbol
In progress
Ready
Form Field
In progress
In progress
List
In progress
In progress
Radio Button
In progress
Ready

**Comment by joshwooding** [comment]
Meeting scheduled next week

**Comment by zdxd** [comment]
Item submitted for testing: https://github.com/jpmorganchase/salt-ds/issues/1570

**Comment by zdxd** [comment]
components identified, results reporting to align with all team DEMOs
