### ISSUE TITLE
Figure out component page layout approach

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1533]
Spike to figure out the best approach to implement the component page layout in Mosaic.

By the end we should have answers to questions like:

* Which parts are the responsibility of the layout component and which parts are components that we drop into the main content area?
* How does the source content need to be structured (e.g. is it a single MDX file, or several per-tab MDX files)?

**Comment by parsakhan21** [comment]
April 17 - in progress (working on a few options for layouts); check in with david reid tom re: mosaic

**Comment by joshwooding** [comment]
PR later today, small tweaks ongoing
