### ISSUE TITLE
Update Theme Foundations and Characteristics

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1546]
## Design

```[tasklist]
### Figma Tasks
- [x] Update Theme characteristics file
- [x] Review token changes with Dev
- [x] Update light mode palette in branch
- [x] Update dark mode palette in branch
- [x] Merge light mode palette branch
- [x] Merge dark mode palette branch
- [x] Publish light mode palette internally
- [x] Publish dark mode palette internally
- [x] Publish light mode palette to community
- [x] Publish dark mode palette to community
- [x] Notify DXD designers of changes via Symphony
```
Several changes need to be made to the design tokens, which also need to be reflected in Figma. The changes will need to be made to:
- Theme Characteristics file
- Light mode palette
- Dark mode palette

**Required changes:**
- Change all `--status-<status>-background-emphasize` attributes to have just `-background` (default) suffix [done in dev]
- Change `--overlayable-borderRegion` to `--overlayable-region`
- Update Figma specs to show colors at 0% opacity with `--opacity-0` token rather than transparent
- Add `--salt-palette-interact-background-activeDisabled` and characteristic token `selectable-background-selectedDisabled`
- Change `opacity` token scales to `-100`, `-200` etc aligning with new foundation work, removing opacity-4 (70%) and baking that into backdrop/scrim tokens as necessary
- Deprecate --salt-status-<>-foreground-disabled tokens (removed from CB and RB)

## Dev

```[tasklist]
### Dev Tasks
- [ ] Update Theme characteristic and foundation files with new tokens and deprecations
- [ ] Update Palette files with new tokens and deprecations
- [ ] Update documentation to reflect changes
```

**Required changes:**
- ~~Change `--salt-size-adornmentGap` to `--salt-size-adornment-gap` [done in design]~~ [REDUNDANT - Size tokens have now been replaced]
- Change `--salt-focused-outlineInset` to `--salt-focused-inset` [done in design]
- Change `--salt-overlayable-borderRegion` to `--salt-overlayable-region`
- Change hardcoded transparent values to be the default value at 0% opacity, by including `--salt-opacity-0` foundation token
- Add `--salt-palette-interact-background-active`
- Add `--salt-palette-interact-background-activeDisabled` and characteristic token `selectable-background-selectedDisabled`
- Change `opacity` token scales to `-100`, `-200` etc aligning with new foundation work
- Deprecate `--salt-status-<>-foreground-disabled` tokens (removed from CB and RB)

## Future considerations

PR #1522 for linting to ensure this problem isn't again encountered

**Comment by pseys** [comment]
@bhoppers2008 can you update this Issue with all the other required changes? Thanks.

**Comment by libertymayc** [comment]
Added 
Deprecate --salt-status-<>-foreground-disabled tokens (removed from CB and RB)
to ticket desc

**Comment by pseys** [comment]
All Figma libraries and the Theme Characteristic files have been updated in branch (1546 Theme updates) and are ready for merge and publish. 
- Salt Typography
- Salt Light Mode
- Salt Dark Mode
- Theme Characteristics

**Comment by libertymayc** [comment]
jun 28 - published in figma

**Comment by pseys** [comment]
@libertymayc all the code changes have been completed now haven't they? Can this be marked as closed?
