### ISSUE TITLE
Sitemap.xml has source paths instead of page URLs

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1559]
### Description

The Salt's site's `sitemap.xml` file is incorrect. The contents of `<loc>` needs to be the full URL to the page (see https://www.sitemaps.org/protocol.html), but instead seems to have the path to the source MDX file.

### Steps to reproduce

Visit https://www.saltdesignsystem.com/sitemap.xml

### Expected behavior

The contents of `sitemap.xml` should conform to the specification.

**Comment by james-nash** [comment]
Done: jpmorganchase/mosaic#328

**Comment by james-nash** [comment]
Shall I leave this issue open until Mosaic release a fix and we upgrade to it, or should I just close it now?

**Comment by james-nash** [comment]
Ok, this bug has been fixed in Mosaic (thanks @lilyvc!), so I'll close this now.

However, now we have a different problem :-(  Our live site's `sitemap.xml` is using the wrong hostname in the URLs (`http://localhost:3000/...` instead of `https://www.saltdesignsystem.com/`). I'll raise a separate issue for that shortly.

**Comment by lilyvc** [comment]
> Ok, this bug has been fixed in Mosaic (thanks @lilyvc!), so I'll close this now.
> 
> However, now we have a different problem :-( Our live site's `sitemap.xml` is using the wrong hostname in the URLs (`http://localhost:3000/...` instead of `https://www.saltdesignsystem.com/`). I'll raise a separate issue for that shortly.

this just needs to be configured in your sites .env :)

mosaic's for example:

https://github.com/jpmorganchase/mosaic/blob/main/packages/site/.env
