### ISSUE TITLE
Explore how we can align Salt AppHeader with Masterbrand primary navigation

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#1562]
- [ ] Initially discuss the AppHeader pattern as a team - James, Jo, Shey
- [ ] Discovery and design phase
- [ ] Decide who will build it
- [ ] Document pattern for site component

**Comment by james-nash** [comment]
Sounds good. Can we make sure this pattern/component also covers responsive behaviours (e.g. moving to a hamburger menu on narrow viewports or something like that).
