### ISSUE TITLE
UITK/Salt Switch component usability test

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#1570]
### Description

After a re-design phase during Q1, a usability test is required to compare the new Switch design to the old UITK one. Would like to see if testing will inform any differences in interaction between the two versions, by exposing to relevant user groups (designers + devs), and if any improvements can be made to the new design if any outcomes arise. Ideally implementation (of characteristics) would align with checkbox/radio button to form a smoother experience. 

### Type

- [ ] to understand more about a particular topic or domain
- [ ] identify factors influence an outcome
- [ ] understand how factors influence an outcome
- [ ] understand how a phenomena affects a topic or domain
- [ ] identify drivers and barriers to a behaviour
- [ ] understand how factors influence a behavioural outcome
- [ ] to know why something is the case
- [X] to evaluate the usability of a component, pattern, product or service

### Existing research and/or data

N/A

### Link to current initatives

- [X] Design System Usability
- [ ] Migration to Salt & Community
- [ ] Evaluative Surveys

### Collaboration

Yes

### Collaboration detail

In context examples (on Figma) for design testing. 

### Timeline

Within coming month

### Research impact

Ideally the findings would conclude that the Salt Switch component re-design efforts are beneficial to the end user, and if any minor design changes are required to enhance the usability of the component then that would be taken into consideration too. 

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by zdxd** [comment]
Rapid tests completed -Nav & Zoe caught up on patterns for follow up test which Nav is now working on ahead of next week

**Comment by parsakhan21** [comment]
June 2 - in progress, Zoe has scheduled a meeting with myself + Paul for next Tue to update us on the results from the testing + discuss next steps

**Comment by zdxd** [comment]
Testing done - results shared w/ Nav & Paul. Awaiting time to catch up w/ Nav on presentation to broader team

**Comment by parsakhan21** [comment]
June 16 - go back to tk switch and enhance

**Comment by parsakhan21** [comment]
June 26 - picking up where it left off from. Re-visiting the UITK switch to see where changes can be made, most of it will likely be characteristics work 
Moving this back into in-progress @navkaur76
