### ISSUE TITLE
UITK/Tableau template & presentation

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#1572]
**Goal:** form written guidance + provide an executable Tableau workbook file for DXD users that would like to implement UITK foundations within Tableau. This initiative will help save design time, effort and achieve consistency when using Tableau. 

Context (Darren Trapp's exploration): https://www.figma.com/file/gHArE256h7oCxeK1gCsxB8/Network-Management---Tableau?node-id=0%3A1&t=nwh4gQ7H5qRVYMnw-1

**Comment by navkaur76** [comment]
Sep 12 - in-progress. Nav re-visiting existing Tableau template to make enhancements/amendments where applicable. 
Sep 11 - Picking back up after Salt component/docs work. Meeting with Uttara + Paul to discuss Oct 5th global call requirements.

**Comment by pseys** [comment]
> Sep 12 - in-progress. Nav re-visiting existing Tableau template to make enhancements/amendments where applicable. Sep 11 - Picking back up after Salt component/docs work. Meeting with Uttara + Paul to discuss Oct 5th global call requirements.

@navkaur76 can you also speak to @bhoppers2008 about King Davids dashboard work and get a sense of what can be achieved between now and Oct 5th?

**Comment by navkaur76** [comment]
**Meeting notes (Tableau/Dashboard pattern) Sep 14 w/ Ben + Paul:**

Dashboard pattern work:

- Clean up exercise. Focus on narrowing scope down to provide users guidance on how to construct a basic analytical dashboard. 
- Quality over quantity: iterate visuals and refine text/theory. Focus on hi-fi mockups that provide a better overview of dashboard structure, communicate visual hierarchy, correct component usage, widgets etc. Align to Salt foundations. 
- Reach a point where we can promote an in-progress Dashboard pattern focusing on analytical dashboards. 
- For any data-vis content - use hi-charts license + packaging, Elwira's figma plugin, UITK charts page

Once dashboard pattern is in a good place...

- Refine tableau template. Opportunity to marry the two, and for dashboard work to drive tableau work
- Link to tableau template from the dashboard pattern page on the site
- 2nd Tableau template containing stickersheet of data-vis? Something to work with Uttara on

Action items:

- Nav/Paul/Ben to review dashboard pattern within it's existing state and identify content to remove/keep, edit etc
- Nav to talk to Rico about ICE dashboards
- If there's time: Paul to add categorical colours to Salt

**Comment by joshwooding** [comment]
Focused moved to completing the dashboard pattern

**Comment by bhoppers2008** [comment]
@navkaur76 targeting completion by Oct 20th. Target date updated.

**Comment by navkaur76** [comment]
Blocked due to issues with navigating the software and availability of appropriate dev support. Nav to pick up upon return from A/L, from 6th Nov onwards.

**Comment by origami-z** [comment]
Blocked - Removed from release plan

**Comment by joshwooding** [comment]
@navkaur76 to update the issue. Working on a template/pattern - deadline agreed as the 17th

**Comment by origami-z** [comment]
17 Nov - Template finished in Figma. Guidance being transferred from notes to Figma, incorporate categorical palette. ETA Monday.

**Comment by origami-z** [comment]
20 Nov - more discussion later, more cleaning to do. ETA tomorrow.

**Comment by origami-z** [comment]
22 Nov - to design a doc page (for salt site). Testing / feedback from consumers in progress.
