### ISSUE TITLE
Simplify/prettify the URLs (post Mosaic rearchitecture)

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#1575]
The current url structure - https://www.saltdesignsystem.com/salt/index - should be corrected so that we don't have those additional namespace suffixes.

**Comment by james-nash** [comment]
Indeed. This is a [known limitation of Mosaic](https://github.com/jpmorganchase/salt-ds/pull/1481#issuecomment-1497673782). I'll get something added to their backlog to make cleaner URLs possible.

**Comment by DavieReid** [comment]
This has been addressed in Mosaic a while ago --> https://github.com/jpmorganchase/mosaic/pull/311

It was released in version beta 30.

**Comment by james-nash** [comment]
Just tried this locally and it's working great.

Any suggestions on how to remove the trailing `index` parts though? I tried mucking about with `rewrites` in `next.config.js` to map URL path like `/foo/bar` to something like `/foo/bar/index`, but wasn't able to get it to work properly (disclaimer, I'm a novice at Next.js, so I may well have been doing it wrong).

**Comment by james-nash** [comment]
Thanks. I'll write up an issue shortly.

**Comment by james-nash** [comment]
@DavieReid done: https://github.com/jpmorganchase/mosaic/issues/442
