### ISSUE TITLE
Tabstrip throws an error when dynamically removing items

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#1586]
### Package name(s)

Lab v1.0.0-alpha.4 (@salt-ds/lab)

### Description

`Cannot destructure property "id' of 'collectionHook.data[activeTabIndex]' as it is undefined @ Tabstrip.tsx:466`

### Steps to reproduce

1. Render a Tabstrip with 5 items
2. Remove three items
3. ???
4. Profit

### Expected behavior

Not to crash :'(

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by parsakhan21** [comment]
April 28 - 1 or 2 errors resolved; 3rd - speak to josh about how to proceed
