### ISSUE TITLE
Define a new strategy for contact & support

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#1591]
Define an updated approach for how our team:

* Can be contacted by consumers (to report bugs, get help, request features, etc.)
* Supports consumers - including SLAs (what bugs do/don't we fix? how quickly do we do so? what kind of help do we provide? etc.)

...and get agreement from our team to implement that strategy.

The output of this will be documentation that outlines the new, agreed strategy.

**Comment by parsakhan21** [comment]
April 28 - in progress - doc in draft

**Comment by james-nash** [comment]
Just shared the proposed plan with the team internally.

**Comment by james-nash** [comment]
Feedback deadline has passed and no major objections or change requests received, so closing this issue as done.
