### ISSUE TITLE
Add Docs page for labs component

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#161]
One of the requirement for a lab component to be moved into core package is having a "Docs" page, e.g. [Button doc](https://uitk.pages.dev/?path=/docs/core-button-doc) is generated by this MDX [`button.doc.stories.mdx`](../blob/main/packages/core/stories/button.doc.stories.mdx). What we need is at least

- Examples
- API
  - Props Table
  - HTML Anatomy
  - CSS Class
  - Characteristics Used
  - Custom Property API
~~Customising styles~~

### Components

- [ ] Accordion
- [ ] AppHeader
- [ ] Avatar #247 
- [x] Badge #194
- [ ] Breadcrumbs
- [ ] ButtonBar
- [ ] Calendar
- [x] Card
- [ ] Cascading Menu
- [x] Checkbox #237 
- [ ] ColorChooser
- [ ] ComboBox
- [ ] ContactDetails
- [ ] ContentStatus
- [ ] Dialog
- [ ] Dropdown
- [ ] FileDropZone
- [ ] FormField  
- [ ] FormattedInput
- [x] Input
- [ ] Link
- [ ] List
- [ ] Logo
- [ ] MenuButton
- [ ] Metric
- [ ] Overlay
- [ ] Pagination
- [x] Panel
- [x] Pill
- [ ] Progress
- [ ] QueryInput
- [x] RadioButton #201
- [ ] Responsive
- [x] Scrim
- [ ] SearchInput
- [ ] Slider
- [ ] Spinner
- [x] StepperInput #214 
- [x] Switch #239 
- [x] Tabstrip
- [ ] ToggleButton
- [ ] TokenizedInput
- [ ] Toolbar
- [ ] Tooltip #219 
- [ ] Typography

**Comment by joshwooding** [comment]
I'm closing this since we're tracking this a different way
