### ISSUE TITLE
Vertical and Horizontal Navigation

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#1642]
- [x] https://github.com/jpmorganchase/salt-ds/issues/1054
- [x] #2328

**Comment by shey-v** [comment]
Meeting 10th May (Cha, Josh, Ben, Paul, Shey, Darrin, Nav, Jo & James), to discuss prioritising of vert nav for the site. 

Ben and Josh have already put together the following requirements (to take into consideration):

* Orientation support (vertical, horizontal)
* Activation bar at top–rather than bottom–aligned to navigable characteristic.
* Activation bar custom colour support.
* 'Always on' as optional (ie., Bar doesn't have to stay visible/no toggle state).
* 'Level' number to drive label inset amount.
* 'Parent item' as bool to determine presence of arrow (to right in vertical nav, at bottom in horizontal nav).
* Pattern examples of stacked nav items, horizontal and vertical.
* Pattern example of nav item 'nesting'.
* Pattern example of nav item with nested cards (MCP).
* Pattern example of nav item with nested mega menu (MCP).

Discussion to further scope the work and focus on building a solution (v1) for the site of a nav item that can stack. We can then document the pattern and further develop it.

**Comment by joshwooding** [comment]
Closing this as both tasks are complete
