### ISSUE TITLE
Desktop Style injection

### ISSUE THREAD

**Issue by ImmanuelBaskaran** [jpmorganchase/salt-ds#1658]
Refactor Lab components to use new style injection system in preparation

Add CSS inline plugin for storybook to prevent it's own style injection from injecting component css into stories.

**Comment by parsakhan21** [comment]
May 12 - PR up for review (cypress tests are failing as a result of change); investigating the issues

**Comment by ImmanuelBaskaran** [comment]
All that remains of this is to merge the code into main.

**Comment by parsakhan21** [comment]
Hi Immanuel, is this work close to complete? @ImmanuelBaskaran

**Comment by ImmanuelBaskaran** [comment]
This is in review, I have addressed the feedback given so far

**Comment by origami-z** [comment]
Implemented in #1697
