### ISSUE TITLE
Logo guidance published to site

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1663]
Placeholder for the component

**Comment by parsakhan21** [comment]
June 2 - will schedule kick-off once designer is assigned

**Comment by parsakhan21** [comment]
Might be a pattern and put some guidance around it.

**Comment by mark-tate** [comment]
Design standards defined, public site needs updating

**Comment by mark-tate** [comment]
Published alongside App Header
https://www.saltdesignsystem.com/salt/patterns/app-header
