### ISSUE TITLE
Figure out how to auto-generate props table on Mosaic

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#1665]

**Comment by parsakhan21** [comment]
may 26 - created plug in and merged into mosaic code base; pending - upgrading mosaic in our repo and enabling plug in - aim to finsh early next week

**Comment by james-nash** [comment]
Need to investigate a bug in the plug-in code on the Mosaic side. They're looking into it. Once they release a fix, we can update our PR to use that new version and get this merged.
