### ISSUE TITLE
Super unstable Grid Column Sorting test

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#1694]
It's not healthy to see across the board red on [Test](https://github.com/jpmorganchase/salt-ds/actions/workflows/test.yml) actions. More than 60% of the test failing recently has to with below cypress test

> Column Sorting
>    1) should sort column values when sorting is enabled

Either fix the test, or at least to disable it to reduce time to decipher whether the tests are actually failing

**Comment by ZarkoPernar** [comment]
Sorting is in alpha version so I would say disable for now.
