### ISSUE TITLE
Data Grid DropdownCellEditor throwing error when clicking on the cell 

### ISSUE THREAD

**Issue by nehadavim** [jpmorganchase/salt-ds#1705]
### Package name(s)

Data Grid (@salt-ds/data-grid)

### Package version(s)

"@salt-ds/data-grid": "^1.0.3"

### Description

I am using Data Grid component from salt and trying to create a n editable dropdown in a cell. when I am clicking in the cell it is throwing an error. 
Here is the code 
`  <GridColumn name="Comment" id="comment" defaultWidth={150} getValue={(rowData: DummyData) => rowData.Comment}>
        {' '}
        <CellEditor>
          <DropdownCellEditor options={['New York, NY', 'Jersey City, NJ', 'Boston, MA', 'San Francisco, CA']} />
        </CellEditor>
      </GridColumn>`
```
Uncaught runtime errors:
×
ERROR
useCollectionData toCollectionItem, item not found 
    at http://localhost:3001/static/js/vendors-node_modules_salt-ds_data-grid_dist-es_packages_grid_src_index_js.chunk.js:5754:11
    at Object.itemToCollectionItem (http://localhost:3001/static/js/vendors-node_modules_salt-ds_data-grid_dist-es_packages_grid_src_index_js.chunk.js:5767:14)
    at Dropdown2 (http://localhost:3001/static/js/vendors-node_modules_salt-ds_data-grid_dist-es_packages_grid_src_index_js.chunk.js:6885:37)
    at renderWithHooks (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:14150:22)
    at updateForwardRef (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:16721:24)
    at beginWork (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:18768:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:3742:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:3786:20)
    at invokeGuardedCallback (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:3843:35)
    at beginWork$1 (http://localhost:3001/static/js/vendors-node_modules_react-dom_index_js.chunk.js:23717:11)
```

### Steps to reproduce

I am using Data Grid component from salt and trying to create a n editable dropdown in a cell. when I am clicking in the cell it is throwing an error.

### Expected behavior

Ideally it should display the dropdown it is displaying in here :
https://storybook.saltdesignsystem.com/?path=/story/data-grid-data-grid--grid-example (group 2 -> location column)

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
What's the version of other `@salt-ds` packages are you using?

**Comment by nehadavim** [comment]
@origami-z "@salt-ds/core": "^1.7.1",
    "@salt-ds/data-grid": "^1.0.3",
    "@salt-ds/icons": "^1.3.1",
    "@salt-ds/theme": "^1.5.0",

**Comment by nehadavim** [comment]
@origami-z I don't have multiple versions of salt packages in my package.json

**Comment by origami-z** [comment]
@nehadavim which versions of salt are you actually using, not `package.json` but in your lock file?

**Comment by origami-z** [comment]
Try using [@salt-ds/data-grid@1.0.4-alpha.2](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fdata-grid%401.0.4-alpha.2) maybe? It might solve multiple copy issue. @nehadavim

**Comment by nehadavim** [comment]
@origami-z installed @salt-ds/data-grid@1.0.4-alpha.2 but the issue is still there

**Comment by nehadavim** [comment]
Forked the issue here https://stackblitz.com/edit/salt-grid-template-rzqisd?file=package.json,App.tsx,AssessmentFormGrid.module.scss

**Comment by origami-z** [comment]
Need  `SaltProvider` wrapping the App for the reproduce to display correctly. We get to the reason of crashing - i.e. `options` array of the dropdown editor doesn't contain the value from `dummyData`. If adding `''` to `options`, the app won't crash.

However, this is still a bug we should fix because regardless misusage, the component shouldn't crash the whole app.

**Comment by james-nash** [comment]
Bug ranking score: **48** (using rubric v3)

Priority: **high**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoxOS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6NywiZnJlcXVl
bmN5T3B0aW9ucyI6MTksImltcGFjdE9wdGlvbnMiOjIwLCJhZm
ZlY3RlZERzT3B0aW9ucyI6MTcsInVyZ2VuY3lPcHRpb25zIjox
OSwieEZhY3Rvck9wdGlvbnMiOjE4fSwicnVicmljVmVyc2lvbi
I6M30=
=========== END BUG RUBRIC SCORE DATA ============
```
