### ISSUE TITLE
Data Grid DropdownCellEditor crashes with Attribute "data-row-key" not found

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#1707]
### Package name(s)

Data Grid (@salt-ds/data-grid)

### Package version(s)

    "@salt-ds/core": "^1.7.1",
    "@salt-ds/theme": "^1.5.0",
    "@salt-ds/data-grid": "1.0.4-alpha.2",

### Description

When using DropdownCellEditor, house hover grid rows then hover over dropdown list, the grid crashes with below error

```
Error in /turbo_modules/@salt-ds/data-grid@1.0.4-alpha.2/dist-cjs/packages/data-grid/src/internal/utils.js (7:11)
Attribute "data-row-key" not found
```

### Steps to reproduce

1. Double click "Option 1" of "Column 1" to open the dropdown menu
2. Mouse hover "Value 1" cell in "Column 2"
3. Mouse hover "Value 3" cell in "Column 2"
4. Mouse hover "Option 2" within dropdown menu
5. The grid crashes

Full Stackblitz reproduce: https://stackblitz.com/edit/salt-grid-template-mcywst?file=App.tsx

### Expected behavior

The grid shouldn't crash

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
@james-nash this needs a ranking

**Comment by nehadavim** [comment]
I am facing this issue too, any idea when this will be resolved?

**Comment by james-nash** [comment]
Bug ranking score: **53** (using rubric v3)

Priority: **high**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoyNS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6NywiZnJlcXVl
bmN5T3B0aW9ucyI6MTksImltcGFjdE9wdGlvbnMiOjIwLCJhZm
ZlY3RlZERzT3B0aW9ucyI6MTcsInVyZ2VuY3lPcHRpb25zIjox
OSwieEZhY3Rvck9wdGlvbnMiOjE4fSwicnVicmljVmVyc2lvbi
I6M30=
=========== END BUG RUBRIC SCORE DATA ============
```

**Comment by nehadavim** [comment]
@james-nash Is that issue resolved?

**Comment by james-nash** [comment]
@nehadavim Not yet. We've received a [fix contribution](https://github.com/jpmorganchase/salt-ds/pull/1762), but it's pending a contributor's license agreement. Once we have that, we can merge and release the fix.

This issue will get closed when that happens.
