### ISSUE TITLE
Data Grid DropdownCellEditor doesn't allow mouse selecting the same option before edit

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#1709]
### Package name(s)

Data Grid (@salt-ds/data-grid)

### Package version(s)

[@salt-ds/data-grid@1.0.4-alpha.2](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fdata-grid%401.0.4-alpha.2)

### Description

DropdownCellEditor doesn't allow selecting the same option, so the list popup won't close when using mouse click.

This is likely to do with using [`onSelectionChange`](https://github.com/jpmorganchase/salt-ds/blob/e6775e7e7d82df78b323b7080c44f46a27a1424e/packages/data-grid/src/DropdownCellEditor.tsx#L58), maybe using `onSelect` would fix it.

### Steps to reproduce

1. Go to storybook editable cell example: https://storybook.saltdesignsystem.com/?path=/story/data-grid-data-grid--editable-cells
2. Double click any cell on the "Discount" column, to enter edit mode
3. Click "-" within the dropdown
4. Nothing happens

### Expected behavior

The dropdown should close

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
@james-nash this needs a ranking

**Comment by alexmotoc** [comment]
This looks like a bug with the `Dropdown` component as well, not just the cell editor. You're right though, `onSelect` should fix it - I can raise a PR for it once I add some tests. Doesn't seem like I can assign the issue to myself.

**Comment by Fercas123** [comment]
Waiting for @alexmotoc to onboard to the contribution process

**Comment by alexmotoc** [comment]
@Fercas123 I think I should be onboarded now!
