### ISSUE TITLE
Toast v1

### ISSUE THREAD

**Issue by parsakhan21** [jpmorganchase/salt-ds#1729]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Basic ADA
- [x] Individual toast, static
- [x] iRAG status (Info/success/warning/error)
- [x] Optional close button (default = visible)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] In Code & Figma (Component + Guide)
- [x] Supporting site documentation
```

```[tasklist]
### Features
- [x] Individual toast, static
- [x] iRAG states
- [x] Optional close button (default = visible)
```

**Comment by navkaur76** [comment]
29/06 - Kick-off meeting scheduled for 30/06

**Comment by parsakhan21** [comment]
@navkaur76 would you mind updating the github issue with kick-off notes - what was discussed, scope of work (features to be built, etc), next steps? Thank you. 
cc @AnniaT @joshwooding

**Comment by navkaur76** [comment]
**KICK-OFF MEETING NOTES (03/07):**

@bhoppers2008 @alycrys @joshwooding @dplsek 

Finalised versions scope:

**V1 (delivery deadline - 17th July EOD)**

- Densities
- Modes
- Basic ADA
- Individual toast, static
- iRAG status (Info/success/warning/error)
- Optional close button (default = visible)

**V2**

- Stacking & positioning (flexible placement on interface)
- Entry & exit animation (duration tokens)

**V3**

- (If there's a strong use case) Filled/secondary variant

**V4**

- Additional status options from status indication pattern (e.g. progress, urgency) - not a strong requirement for now as users can refer to the pattern for guidance

**Additional action items/considerations:** 

**Content** @mikearildbrown @sion-docs : documentation should clearly define the difference in usage between banner + toast ([messaging pattern](https://www.figma.com/file/ecxcWvcxVC5BzMFvhiWjq3/UITK-Patterns-%2F-Messaging?type=design&node-id=75%3A480&mode=design&t=OQ9ErE65HzFFAayV-1) exists as reference for distinction). Important that this is covered in docs for V1 Toast. 

**Placement/positioning logic:** we should ideally provide something to users that makes placement easier, especially with stacking. Useful for @alycrys to provide a demo with supporting doc in storybook, but treated as a late V1/early V2 feature. 

**Actionable button:** example available in design, and available as a story only. Nav to work with @dplsek on VD for this. 2 directions to consider for sizing/spacing: 

1. small container + spacing-100 around border
2. Size-base with spacing-50 above + below (like banner)

Pattern: toast to not be formed into a pattern as although visually similar, semantically there is a difference between toast + banner. Gives us freedom in the future to deviate and build in flexibility.

**Comment by dplsek** [comment]
07/07 - pr to be reviewed and merged

**Comment by parsakhan21** [comment]
Per Mark's comment in teams, is this on track for delivery on Friday, July 14? @alycrys @navkaur76 

FYI @mark-tate 

Thanks,
Parsa

**Comment by parsakhan21** [comment]
July 14 - agreement on structure (spacing/sizing) reached - design on track (might change after review with darrin);

**Comment by navkaur76** [comment]
**Toast V1 design assets ready for review** (@bhoppers2008):

[Design spec](https://www.figma.com/file/2xMrItDwWRTaAqdEZPFa8U/Toast?type=design&node-id=14%3A1050&mode=design&t=YHtNvnAr1rr7YNAo-1)
[Light component](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/J4FFvDI4JJqIGhrlxMWsb2/Salt-Light-Components?type=design&node-id=8674%3A82929&mode=design&t=y8gcg23E4e6bKIP5-1)
[Dark component](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/rljhfvZC16spZLqvOZSIDO/Salt-Dark-Components?type=design&node-id=5904%3A83560&mode=design&t=ooTwgS9SQC9Y79Za-1)
[Figma component guide
](https://www.figma.com/file/cuFHZFPFpbDxBQzKgj8gWW/Add-Toast-figma-component-guide?type=design&node-id=2136-84512&mode=design)

CC: @alycrys @dplsek

**Comment by navkaur76** [comment]
Hi @jpmorganchase/salt-content I've put filled in some info for [toast V1 docs](https://drive.jpmchase.com/:w:/r/personal/n768800_emea_ad_jpmorganchase_com/Documents/Microsoft%20Teams%20Chat%20Files/Toast.docx?d=weed0486ebf554ee786eff27bbd7fc8f5&csf=1&web=1&e=1YwNVD) that is ready for review. 

Key note is to highlight the difference between toast and banner usage. If you need any additional info, do let me know. Thanks!

**Comment by joshwooding** [comment]
21/07 - nearly done, one problem left to solve. Will reduce scope and release today (Figma). Docs need input from team, Nav to reach out
