### ISSUE TITLE
SSR is broken due to the new desktop support

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1755]
### Package name(s)

Core (@salt-ds/core), Icons (@salt-ds/icons), Theme (@salt-ds/theme), Lab (@salt-ds/lab), Data Grid (@salt-ds/data-grid), AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

main

### Description

When using SSR you get the following error:

"useWindow must be used within a WindowProvider"

This is because the window is undefined on the server and useWindow errors when window is undefined.

### Steps to reproduce

Use SSR

### Expected behavior

It not to error.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
@el-dav @joshwooding I think this has been fixed by #1757. If so, shall we close this issue?

**Comment by joshwooding** [comment]
Yeah, you're right
