### ISSUE TITLE
International Address Input Pattern V1

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#1760]
- Miguel, LL and team are keen to collaborate and define this as a pattern.
- Since we’re not in a position atm to allow teams to publish their own patterns, @yunjungyeh is going to drive, define and document this, so we have a pattern in the back pocket that we can publish when our pages are ready.
- We’ve got some examples collected already. @yunjungyeh  will do some due diligence to check for prior art in and outside of the business and then synthesize a first pass at a basic (v1) pattern that we can refine with the team.
- @yunjungyeh can collab with @shey-v  (and @dplsek @bhoppers2008 ) on content block requirements for the Pattern template.
- We can enhance with further versions once we have the simplest form of the pattern defined.
- The deliverables will be interaction and visual design patterns + documentation for the site
- Dev requirement unknown @joshwooding

**Comment by yunjungyeh** [comment]
Hi @parsakhan21 this is the status updates for this pattern :)

- [v] 1-2 June - To read emails (forwarded from Ben) and all the examples to understand the requirements
- [WIP] 2 June - Due diligence on the pattern
- [WIP] 2 June - Desk research 
- [v] 2 June - Sync with Shey about Patterns and the theme doc template
- [v] 2 June - Add Transact address Example

**Comment by yunjungyeh** [comment]
✅6 June - Discuss progress and further actions with @bhoppers2008 
✅6 June - Reply the email thread
✅6 June - Ask if anyone can share what I’m looking for in DXD Symphony Chats (JPM UI Toolkit & Salt Community / CIB Global DXD Team) (Who else in CIB: Markets/Security/Payments) and share the pattern link so they can add their examples
✅6 June - Reach out to Salt Dev: MS teams System channel
✅6 June - Schedule a call + Agenda on Friday (Share the research progress / proposed direction for MVP, Discuss some questions related to your projects, Iterate together, Outcome: Agree the direction of the pattern that we can move to design)
✅6 June - Reach out to Manhattan DS (Jeff Crossman)
✅6 June - Reach out to Dynamo DS (Leigh/Aled)
✅6 June - Reply Richard Salaman & to add the examples to the Collaborator canvas

✅7 June - Reply Aled and ask more questions
WIP🟠7 June - Update the public file with discover/define stuff 
WIP🟠7 June - Explore Rich S’s examples
WIP🟠7 June - Explore/Analyse more resources from Zhihao/Ivan

**Comment by yunjungyeh** [comment]
✅7 June - Explore/Analyse more resources from Zhihao/Ivan 
✅7 June - The discussion points for the call on Friday
✅7 June - Explore Rich S’s examples
✅8 June - Catch up with Ben on the progress
✅8 June - Continue the examples of proposed pattern With a clear Phases graphic
✅8 June - Check Amazon Address format web version
✅8 June - Using template to Update the public file with discover/define stuff > Prepare for discussion on Friday
✅8 June - Further steps, share some findings and resources for the matrix
✅8/9 June - Share the link to the file via the meeting invite > VPN not working at home so will share in the morning
✅9 June - Reply Aled Linh/Ask questions about API and onboarding flow in Chase UK

**Comment by parsakhan21** [comment]
June 9 - catch up with teams who initially contributed to examples for this; aim to have a grid mvp direction

**Comment by parsakhan21** [comment]
hi Yun, i see this issue has a past due date/deadline of July 7 - should the RAG status be marked as amber? Can you please clarify. Thanks! @yunjungyeh

**Comment by parsakhan21** [comment]
July 14 - writing content and share with mike next week ; review with ben

**Comment by parsakhan21** [comment]
July 17 - designs to be completed by end of week - potentially release figma guidance this week first (with effort to put on site next wek) ; dev to be assigned and due date to be assigned

**Comment by yunjungyeh** [comment]
Content to be reviewed by @jpmorganchase/salt-content 
Has sent an email with Figma link and Word text-only link, thanks

**Comment by parsakhan21** [comment]
July 24 - updating content based on feedback - review with third party proof reader group after ; feedback with ben when he's back; dev - not assigned
