### ISSUE TITLE
Input v2

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1767]
Figma Link: @bhoppers2008 to create
___

```[tasklist]
### Released in
- [x] Design
- [x] Dev
```

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1742
```

All versions assume support for:
- All densities
- All modes
- Accessibility considerations

### Version 2

a. Static suffix and prefix adornment: Icon, Text
b. Interactive suffix adornment: Adornment Button component
c. Placeholder text

**Comment by parsakhan21** [comment]
June 9 - features all merged; need design review from Ben and ADA

**Comment by shinytoyrobots** [comment]
@bhoppers2008, can someone on the design team review this so we can ship? And @maj-stella - either in advance of release or post-release, can you review and highlight any ADA updates required?

**Comment by origami-z** [comment]
Figma library released
