### ISSUE TITLE
Input v3

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1768]
Figma Link: @bhoppers2008 to create
___

```[tasklist]
### Done in
- [ ] Design
- [x] Dev
```

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1742
```

All versions assume support for:
- All densities
- All modes
- Accessibility considerations
 
### Version 3

~a. Cursor position on focus~
~b. Highlight selection on focus~
c. Spellcheck

**Comment by parsakhan21** [comment]
@bhoppers2008 please review and let us know if this is good to go. Thanks!
