### ISSUE TITLE
Qualtrics Design Theme

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#1777]
Qualtrics ‘look and feel’

- The team have sent over some example surveys with common questions and components.
- @yunjungyeh  will create some quick mock-ups of those surveys using Salt components and foundations and aligning to the recent forms pattern.
- We’ll regroup with Qualtrics to collaborate on the designs and identify constraints and compromises during that working session.
- @pseys asked why we weren’t creating mock-ups that already considered their theming constraints. My sense is that we want to move quickly (we don’t have capacity for large engagements). Since the team has a better understanding of Qualtrics theming, and our knowledge lies in the design system, my preference is to focus on what we know and iron out any restrictions in a working session together. Is that ok?
- @yunjungyeh  can collab with @navkaur76  (and @pseys ) to align on any consistencies between this work and Tableau/Ocado work.
- After this initial phase, we’ll work with the team to turn the look and feel into a theme, hosted by Salt, with some accompanying documentation. This should align with the other theming engagements we have in play.

**Comment by yunjungyeh** [comment]
✅2 June - Schedule a call (9th Fri) with Nav to review her work for Tableau
✅3 June - Waiting for the email response from Qualtrics
✅5-6 June - Review examples in the email: Qualtrics Design Action Items

**Comment by yunjungyeh** [comment]
WIP🟠7 June - View Form pattern content (by @bhoppers2008 & @dplsek )
WIP🟠6/7 June - Create Mockups using Salt components and foundations and aligning to the recent forms pattern.

**Comment by parsakhan21** [comment]
@yunjungyeh since this is on hold, should i move it back to backlog until you are ready to work on this again?

**Comment by dplsek** [comment]
07/07 - catch up on spacing today with @dplsek @bhoppers2008

**Comment by origami-z** [comment]
Consider this as done
