### ISSUE TITLE
Figma component updates

### ISSUE THREAD

**Issue by ivan-calderon** [jpmorganchase/salt-ds#1794]
- [Light card border updates](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/Salt-Light-Components?type=design&node-id=6159%3A73968&t=SQpPQo0HtVKAYe3H-1)
- [Dark card border updates](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/Salt-Dark-Components?type=design&node-id=5007%3A72977&t=QFMGUMUymetkj42h-1)
- [Card specs](https://www.figma.com/file/gbHcDLjP1M976avIlRDWl7/Card?type=design&node-id=1%3A52295&t=m4WTpcCnEhEGiyNP-1)
- [Card FIGMA guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/Salt-Figma-Component-Guides?type=design&node-id=978%3A75974&t=dGMJfRSxs4K77Zc9-1)

**Comment by bhoppers2008** [comment]
Figma components to be updated and published:
- Card - Border update
- Checkbox/Radio - Structure needs updated, Replace UITK type styles
- Tooltip - Component release
- Icon - Updated icons (@pseys assume this is outstanding?)

**Comment by dplsek** [comment]
To consider...

- For checkbox and radio, should we go ahead and change spacing-75 to spacing-100 between icon and value?
- Tool-tip Figma spec/components need to be updated with 'base' height and borders inside and reflected in code
- For button text style, we won't (necessarily) need this if we're updating all buttons with semi-bold caps with 0.6 spacing, we should be able to use secondary buttons OOTB for everything in toggle button group, and just modify the height for the horizontal variant. But this also depends if you want to bake the focus/focus active states into the component, in which case the secondary button wouldn't work OOTB

**Comment by navkaur76** [comment]
Tabs links to review/merge:

[Tabs light mode component](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/Zw3HH6IUYdS1X76PzAHHW5/Salt-Light-Components?type=design&node-id=7613%3A78321&mode=design&t=M8rkJ4ofnufzpbFR-1)

[Tabs dark mode component](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/yRqnLJHH884PxflmAEyXar/Salt-Dark-Components?type=design&node-id=5457%3A78514&mode=design&t=YypAeXj42INaMgs3-1)

[Tabs component figma guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/GTbGpEpOjOwdlaLEzWjPDA/Salt-Figma-Component-Guides?type=design&node-id=1856%3A79581&mode=design&t=TqC2a9M1ePiPQGzA-1)

[Tabs design spec](https://www.figma.com/file/stxwJ6W76LYykFURkTdtFM/Tabs?type=design&node-id=801%3A15352&mode=design&t=SvrJTT32UyuTtG2b-1)

**Comment by pseys** [comment]
@bhoppers2008 Icons have been updated and the current version of the file is accurate, but it hasn't been published.

**Comment by navkaur76** [comment]
**Checkbox and radio button updates (excluding addition of read-only states):**

[Checkbox light component](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/KP17ueEZYhUxsmyQ0uEQRL/Salt-Light-Components?type=design&node-id=6049%3A73872&mode=design&t=ENLLspdHPKgQhWPK-1)

[Checkbox dark component](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/q45su5H22pJ6zC6YagAgMs/Salt-Dark-Components?type=design&node-id=4994%3A72977&mode=design&t=hDAcTtSS4YmJbkEE-1)

[Checkbox figma component guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/D7Xn3pk3ia1f6TvPFebkAy/Salt-Figma-Component-Guides?type=design&node-id=958%3A75974&mode=design&t=a5qUQSQ8mkwKNLoP-1)

[Radio button light component](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/E9lggbKZ33NiANZe2zmycD/Salt-Light-Components?type=design&node-id=6084%3A73872&mode=design&t=85MZCvlwvCgSh9f3-1)

[Radio button dark component](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/kH0gVzDN26yP8vGd7EBhRV/Salt-Dark-Components?type=design&node-id=4990%3A72977&mode=design&t=Czo687sUOcomTKxT-1)

[Radio button figma component guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/QgbrNGY8lGYite0aClujBj/Salt-Figma-Component-Guides?type=design&node-id=953%3A75974&mode=design&t=ZRNVbyN14id74g6j-1)


----- Notes: -----

Checkbox updates include:

- Value updated to Salt typography
- Update spacing between icon and value to spacing-100
- Small tick icon added to all HD checkboxes
- Focus ring removed 
- Add indeterminate disabled state
- Add warning state
- Re-organising checkbox into 3 variants - default/ error/warning. splitting into state and selection props

Radio button updates include:

- Value updated to Salt typography
- Update spacing between icon and value to spacing-100
- Focus ring removed 
- Add warning state
- Re-organising radio button into 3 variants - default/error/warning. splitting into state and selection props

**Comment by ivan-calderon** [comment]
**UPDATES**
Card updates 
- [Light card](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/BUTxJlUQfr5NKKkgmu0o54/Salt-Light-Components?type=design&node-id=6159%3A74006&mode=design&t=m2IXcns3WOHll8Zh-1) (remove focus states)
- [Dark card](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/WRoIWZHDiaOsGz7JVjwbVD/Salt-Dark-Components?type=design&node-id=5007%3A73015&mode=design&t=uWuwdlrgEu3omiSf-1) (remove focus states)

**NEW**
List component created 
- [Light List](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/WrCy6LQeHHH73BRemPBXos/Salt-Light-Components?type=design&node-id=7005%3A78352&mode=design&t=6TJdCf5rMkaXHk7y-1) 
- [Dark List](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/IY5GyK2mFjHrnP9lnyolz9/Salt-Dark-Components?type=design&node-id=5227%3A79365&mode=design&t=e162n2BxhTDqEe0J-1)
- [List FIGMA Guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/QgJwSVGdLjvK9KPC1ggyoH/Salt-Figma-Component-Guides?type=design&node-id=1592%3A173484&mode=design&t=Sb1w6oE7HLjVh9zI-1)

**Comment by navkaur76** [comment]
**Tooltip to review:**

[Tooltip light mode component](https://www.figma.com/file/7KgRuAqrlNM8pYSMRthbjt/branch/3K1hkvp4pYxkRCszxU71gB/Salt-Light-Components?type=design&node-id=6382%3A73695&mode=design&t=zj8hrwaWIBBwiel7-1)

[Tooltip dark mode component](https://www.figma.com/file/14t5w7BuWParQh6AAnVP0C/branch/K55J4Hug43vDIW467jqpmE/Salt-Dark-Components?type=design&node-id=5170%3A78578&mode=design&t=EgvT2qh17LrzbxUi-1)

[Tooltip figma component guide](https://www.figma.com/file/9EtX0nBTROXl97lKIUSG6Y/branch/d52KH49ZjZS2V5TzyQk360/Salt-Figma-Component-Guides?type=design&node-id=1193%3A76690&mode=design&t=6miGs1XLiy95kKJ2-1)

[Tooltip design spec](https://www.figma.com/file/0qHqLDEobXhRGb1PzQ0I5q/Tooltip?type=design&node-id=801%3A15352&mode=design&t=kPTDZANVbpX7uAJq-1)

**Updates made to tooltip:**
Align sizing to size-base across all densities
Adjust top padding of icon to sit slightly lower next to text
