### ISSUE TITLE
Salt ag grid theme doesn't style filter panel

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#1806]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

"@salt-ds/ag-grid-theme": "1.1.6"

### Description

Out of box ag grid filter panel doesn't match overall styling
- Spacing within the panel are tighter than before
- Buttons looks default HTML buttons, instead of Salt ones

Raised by MTK

### Steps to reproduce

Use below code in one of column def, then open the filter panel using triple dots menu on hovering header

      filter: 'agTextColumnFilter',
      filterParams: {
        buttons: ['reset', 'apply'],
      },

https://stackblitz.com/edit/salt-ag-grid-theme-g6m6gj?file=package.json,App.jsx

### Expected behavior

Spacing should match general Salt design language, button should look like Salt ones

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
Bug ranking score: **40** (using rubric v3)

Priority: **medium**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoyNS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6NywiZnJlcXVl
bmN5T3B0aW9ucyI6MTksImltcGFjdE9wdGlvbnMiOjEsImFmZm
VjdGVkRHNPcHRpb25zIjoxNywidXJnZW5jeU9wdGlvbnMiOjE5
LCJ4RmFjdG9yT3B0aW9ucyI6MzB9LCJydWJyaWNWZXJzaW9uIj
ozfQ==
=========== END BUG RUBRIC SCORE DATA ============
```
