### ISSUE TITLE
Foundations: Finalise Spacing doc

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1829]
- [x] Update Spacing doc text
- [x] Add Size doc
- [x] Update Size doc text
- [x] Update Responsive doc text
- [x] Update Density doc text
- [ ] Update Typography doc text
- [x] Add images to Spacing doc
- [x] Add images to Size doc
- [x] Add images to Responsive doc
- [x] Add images to Density doc
- [ ] Add images to Typography doc

Update the Spacing page to include all relevant guidance. Spacing is indelibly linked to several other Foundations and therefore requires other pages to be updated at the same time. This update includes: 

- Spacing
- Responsiveness
- Size
- Density
- Typography (minor update)

New images will be needed for each doc – @dplsek will be providing these

**Comment by pseys** [comment]
Thanks @mikearildbrown – I wanted to make you aware of the changes in advance so you knew to look out for them.

**Comment by pseys** [comment]
Thanks @james-nash thats the approach I'm taking. I've set the branches up and I'm going straight from Figma into MDX with the intention for us to review content directly on the preview page. 

The only thing I could do with help on is we have several branches set up to accommodate the foundation updates, but because they're interlinked it would be helpful to merge the branches into one rather than split it across multiples. If you could help with that I'd be very grateful.

**Comment by parsakhan21** [comment]
July 19 - agreement on spacing fdn - impacts other fdns as well - in progress

**Comment by parsakhan21** [comment]
July 24 - size page done ; need to add images.

**Comment by pseys** [comment]
I've made content updates to the following pages and they are all ready for review: 

- - Foundations overview
- Responsiveness
- Scale
- Density
- Size
- Spacing

https://saltdesignsystem-git-foundations-spacing-joshwooding.vercel.app/salt/foundations/index

**Comment by parsakhan21** [comment]
@pseys hi paul, is this ready for content review. Please clarify.

**Comment by pseys** [comment]
@parsakhan21 yes its ready for content review

**Comment by pseys** [comment]
@jpmorganchase/salt-content (Delme) has reviewed the amended pages and all recommended changes have been made. One final review is needed to ensure all the changes are correct and if this is OK we can publish the new content.

**Comment by parsakhan21** [comment]
Aug 2 - Sion plans to do final review of doc by eod today

**Comment by sion-docs** [comment]
Docs reviewed, some minor changes made and committed to branch. Ready to publish.
