### ISSUE TITLE
HD Compact Density for Salt AG-Grid

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1843]
### Area

UI Components

### The problem

HD Compact is needed by Markets for the AG Grid Theme
Status bar is too tall for HD-compact

### The solution

Build the theme

### Alternatives and examples

The users override themselves

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
Status bar is too tall for HD-compact: also needs checking as part of this ticket

**Comment by libertymayc** [comment]
reviewed by @dplsek and @bhoppers2008 , PR awaiting dev review https://github.com/jpmorganchase/salt-ds/pull/2077
