### ISSUE TITLE
Stepper Input (Labs)

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#1855]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [x] Fill (Primary, Secondary, Tertiary)
- [x] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [x] Controlled API
- [x] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Basic input with arrow control
- [x] Increment value control
- [x] Min, max value support + updating arrow state
```

**Comment by origami-z** [comment]
Extending dates, 1 sprint behind

**Comment by mark-tate** [comment]
Zazu Goal: M(5)
- API issues, passing event
- merge to RC, a known state
- stakeholder review required
-  draft docs/design ready to publish

Outstanding Issues:
- Clicking and holding up/down, API issues to resolve
- Release with optional prop to avoid future breaking change

**Comment by lilyvc** [comment]
PR waiting for review: https://github.com/jpmorganchase/salt-ds/pull/3527
Docs have been QA reviewed by Ben and updated with feedback, just need to be updated with the new API when above is merged https://github.com/jpmorganchase/salt-ds/pull/3586

**Comment by mark-tate** [comment]
Goal: push to core by EOS

**Comment by origami-z** [comment]
Jul 11 - With theme next release and ag gird theme bugs, this may get delayed to next sprint.

**Comment by origami-z** [comment]
Jul 15 - Push to next sprint due to other priorities

**Comment by mark-tate** [comment]
Goal: need event handler work and then move to Core
Requires some resourcing

**Comment by mark-tate** [comment]
will be picked up in cortado

**Comment by mark-tate** [comment]
Cortado Goal
Third party feedback before merge to core

**Comment by origami-z** [comment]
Aug 7 - had a look at existing code. Need refactor to not use `Input`.

**Comment by joshwooding** [comment]
Aug 20 - EOS goal to labs, will create another ticket to move to core (waiting for feedback)

**Comment by origami-z** [comment]
Aligning the schedule with #3878

**Comment by mark-tate** [comment]
Code complete / Design review required in Espresso

**Comment by mark-tate** [comment]
Frappe Goal: Merged to Labs
(delayed by 1 sprint due to Button release)

**Comment by origami-z** [comment]
Sep 23 - #3976 ready for review. No site examples design available

**Comment by mark-tate** [comment]
goal for the week,  site examples defined - defined by Wednesday
(needs dev capacity to create examples by end of week)

**Comment by navkaur76** [comment]
24/09 - Site docs ready for review in figma

**Comment by mark-tate** [comment]
Ready for dev state reached
