### ISSUE TITLE
Switch

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#1863]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```
```[tasklist]
### Features
- [ ] Dependency: New design validation
- [ ] On/Off states
- [ ] Optional label
- [ ] Integration: Form field example
```

**Comment by navkaur76** [comment]
Pending design work for Switch: 

- How it is constructed and how we can best align to the current, and recently updated tokens within the characteristics. This includes finding a solution for the background/icon issue that the newer Salt switch was trying to solve. 
- Involve development within this process to gain a better understanding of structure and solutions 
- Specifically look to update the disabled ‘on’ state to reinforce as a disabled state, which should create better distinction between ‘on’ and ‘disabled on’. Such changes will also be applicable to radio button and checkbox

**Comment by libertymayc** [comment]
pending feature: FF integration

**Comment by parsakhan21** [comment]
Aug 4 - doing some design reviews ; darrin updated specs on thrusday (ben merged in from figma pov)

**Comment by parsakhan21** [comment]
August 7 - released in labs from dev pov; docs required - ben/josh will work on it

**Comment by joshwooding** [comment]
Created #2178 to track the left over
