### ISSUE TITLE
Multiline Input v1

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1886]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
### Features
- [x] Variants and styling
- [x] States (disabled, readonly)
- [x] Adornments (static, button)
- [x] Validation status
- [x] Fixed number of rows
```

Required for #1773

**Comment by libertymayc** [comment]
https://github.com/jpmorganchase/salt-ds/pull/1930

**Comment by libertymayc** [comment]
7/7 - PR merged, ready to release in dev, not moving to ready to release until confirmed by @bhoppers2008 (unless that column is just for dev? @parsakhan21 )

**Comment by parsakhan21** [comment]
ready for release should consider all assets ready (not just dev) and final before its released to users. @joshwooding please confirm. Thanks.

**Comment by parsakhan21** [comment]
July 17 - ben to review docs

**Comment by libertymayc** [comment]
jul 21 - Ben has created spec, docs still with Ben before passing to content. ready for release in dev

**Comment by parsakhan21** [comment]
@bhoppers2008 is there an update on the docs for this per Liberty's comment?

**Comment by parsakhan21** [comment]
July 25 -  v1 and v2 Both docs done asap – definitely this week. But not a blocker. Can be added later.

**Comment by AnniaT** [comment]
@bhoppers2008 status on docs? ready for release today?

**Comment by AnniaT** [comment]
@bhoppers2008 to catch up w/ @mikearildbrown on docs

**Comment by libertymayc** [comment]
interaction spec pending @bhoppers2008 
docs have been given to content - awaiting review

**Comment by joshwooding** [comment]
Created tickets to track left over #2128  #2127
