### ISSUE TITLE
MCP Partner Program Initiative

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#1899]
Provide design compositions and guidance around login.

**Comment by parsakhan21** [comment]
June 26 - working on MCP login decisions. They will be impacted by spacing tokens work that needs to be applied to components.

**Comment by dplsek** [comment]
June 30 - created first set of screens for inactivity time out, inactivity time out warning, and login. designs were shared with Victoria Statsenko and Josephine Floyd on June 29.

https://www.figma.com/file/twYHKQUYYRuYLsFI74d0s9/MCP-Error-and-Timed-Out-Pages-(Salt%2FUITK)?type=design&node-id=0%3A1&mode=design&t=DvwhDxxlyHQ5Y1FQ-1

**Comment by parsakhan21** [comment]
July 14 - login was released ; @dplsek please update when you return.
