### ISSUE TITLE
Salt Site Utilities Library

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#1915]
Creating Salt Site Utilities Library
Equivalent to Salt Spec Utilities: https://www.figma.com/file/i8kSFpGbHIWXnv6LFvWKdU/Salt-Spec-Utilities?type=design&mode=design&t=NfBcCGpE9XLZ5AKi-0

**Comment by origami-z** [comment]
Duplicate for #1916
