### ISSUE TITLE
Multiline Input v2

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#1934]
```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

```[tasklist]
- [x] Form Field integration
- [x] Question component
- [x] Character count
```

Required for #1773

**Comment by Fercas123** [comment]
11/07 - I had a catchup with @bhoppers2008 about the form field question styles, changes have been applied, pending dev review.

**Comment by Fercas123** [comment]
14/04 - PR merged, one conversation pending to rename prop `fullBorder` to `border` or `bordered`.

**Comment by libertymayc** [comment]
19/7 - v3 rescoped, character count moved to v2. should be done by fri 28th.

**Comment by libertymayc** [comment]
21/7 - design update, PR made to reflect changes waiting for reviews. after that, PR is ready to move to core, and ready for release in dev. ben has made specs, docs still with him

**Comment by parsakhan21** [comment]
@bhoppers2008 updates on docs?

**Comment by parsakhan21** [comment]
July 25 -  Both docs v1 and v2 done asap – definitely this week. But not a blocker. Can be added later.

**Comment by AnniaT** [comment]
@bhoppers2008 spec to be finalised.

**Comment by AnniaT** [comment]
@bhoppers2008 spec to be finalised (interactions) Will aim to get this done by end of tomorrow

**Comment by bhoppers2008** [comment]
@libertymayc found a bug in the build that prevents the user from dragging over all text in the multiline when there is overflowing text in the field. 

Action: Fill with text until overflowing. Click in field with mouse cursor and drag up.
Expected: Field content scrolls as mouse is dragged. Text is highlighted.
Actual: Only visible text is highlighted. Content doesn't scroll.

**Comment by bhoppers2008** [comment]
@mikearildbrown have added to and reviewed the docs template for Multiline. Need a content review please.

@libertymayc

**Comment by parsakhan21** [comment]
tagging @jpmorganchase/salt-content so they are aware of the request. Please see ben's request for content review. Thanks.

**Comment by libertymayc** [comment]
interaction spec pending @bhoppers2008 
docs have been given to content - awaiting review

**Comment by parsakhan21** [comment]
Aug 2 - docs currently in review with Input. Will be done by COB today.

**Comment by sion-docs** [comment]
Aug 3 - docs reviewed and minor updates made.

**Comment by libertymayc** [comment]
aug 4 - docs done, just pending figma release @bhoppers2008
