### ISSUE TITLE
Dashboard pattern design

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#1947]
- Assess and define the typical dashboards used in partner applications and their universal functionalities. 
- Assess some typical applications and try to identify a couple of common dashboard patterns that would be worth documenting on the Salt website.

Key milestones:

- [x] Gather features and key user requirements from users across DXD 
- [x] Carry out research and gather internal examples from across DXD and external competitors
- [x] Narrow down scope for dashboard pattern to something bitesize and can be documented over the next 6-7 weeks
- [x] Collect and synthesise insights from key findings, once all research has been collated
- [x] Socialise work to internal team (all team demos) and stakeholders met with - encouraging open feedback loop
- [ ] Document pattern rules, recommendations and best practises around designing for dashboards
- [ ] Consider accessibility standards that dashboard designs should generally adhere to 
- [ ] Design explorations of common dashboard templates using Salt components

**Comment by kinghga** [comment]
- Scheduled meetings with more teams working on dashboard and made notes: Vida, ICE, Nebula, Tableau, Qualtrics...
- Created an affinity map of all dashboards gathered to enable categorisation
- Met with Ben, Paul and Robbin for reviews and implemented feedback
- Read articles on dashboards patterns, F-Z , readability, minimising cognitive load, efficient use of data viz
- Carried out External research on competitor dashboards: Morgan Stanley, Bloomberg, Edward Jones, Chase Private Client, HSBC, Barclays...

**Comment by kinghga** [comment]
- Made progress documenting some patterns
- Met with different stakeholders to share patterns and got helpful feedback
- Shared feedback with Shey and Paul for further guidance and implementing feedback
- Studying Layout components
- Studying and documenting underlying patterns/ systems in other dashboards- spacing, background tokens and other components used

**Comment by bhoppers2008** [comment]
@navkaur76 Have assigned this ticket to you. Can you setup some time to review the pattern as left off by King so we can scope what's remaining alongside your tableau work. Thanks

**Comment by joshwooding** [comment]
@dplsek - should have design assets completed to be used by @navkaur76

**Comment by navkaur76** [comment]
3 Oct - V1 of dashboard pattern is ready for design review @bhoppers2008 @dplsek

**Comment by navkaur76** [comment]
13 Oct - design review complete + feedback addressed. Pattern is ready for content review @jpmorganchase/salt-content

**Comment by origami-z** [comment]
Comments left this morning from @mikearildbrown

**Comment by origami-z** [comment]
20 Oct - final design review EOD. Ready to be picked up for dev work next week.

**Comment by origami-z** [comment]
23 Oct - Design done.
