### ISSUE TITLE
Migration & Community | Desk Research - Design System Benchmarks Lit Review

### ISSUE THREAD

**Issue by tadxd** [jpmorganchase/salt-ds#1979]
The purpose of this research is to explore industry best practices on benchmarks for the adoption and impact of design systems; as well as review internal systems that could be used to track ongoing adoption and impact. Ultimately, this research will help inform the creation of SLEs for Salt adoption and impact. It will also inform the creation of persistent dashboards to track the adoption/impact of Salt.  

```[tasklist]
### Tasks
- [x] Research brief
- [x] Data collection and analysis
- [x] Recommendation report
```

```[tasklist]
### Deliverables
- [x] Recommendation report
```

**Comment by parsakhan21** [comment]
July 14 - drafting research brief

**Comment by tadxd** [comment]
Jul 24 - brief in peer review > send to RC for review + approval.

**Comment by tadxd** [comment]
Jul 26 - Brief reviewed/approved by RC. Beginning data collection + analysis.

**Comment by tadxd** [comment]
21-Aug. Debriefed with Robin. Met with Zhihao re: internal systems that could be leveraged. Map identified metrics with internal systems and baselines.

**Comment by tadxd** [comment]
25-Aug no updates from the above.

**Comment by tadxd** [comment]
Sep 1 - No updates

**Comment by tadxd** [comment]
Sep-15: going to revisit benchmarks and metrics in Q4
