### ISSUE TITLE
go/salt-learning Intro to Typography Foundation training

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1989]
- [x] Setup IEMS registration page
- [x] Send invites
- [x] Run training
- [x] Distribute survey

To help educate Designers on the revised foundations, new patterns and updated components we are kicking of a Design System Knowledge Share series, starting with Typography foundation. 

This series will occur every 3-4 weeks.

**Comment by pseys** [comment]
Invites have been distributed to DXD and UITK distro list, as well as publicised on Symphony. It was also announced in a global team meeting.

**Comment by parsakhan21** [comment]
July 17 - first session tomorrow

**Comment by tadxd** [comment]
Jul-21: survey distributed on the 18th; will close on the 28th. Request from team to encourage participation.
