### ISSUE TITLE
Theming investigation

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#1990]
Darrin and Paul to review the current theme and identify areas for improvement further investigation in order to provide a fully theme-able solution.

**Comment by james-nash** [comment]
@pseys & @dplsek I have some ideas/suggestions about this stuff, if you're interested. Could talk you through them on a call perhaps?

**Comment by pseys** [comment]
That would be great @james-nash .  Could we set something up for later in the week?

**Comment by james-nash** [comment]
Sweet. I'll try to find some time in our calendars then

**Comment by libertymayc** [comment]
> Sweet. I'll try to find some time in our calendars then

I'm interested, if I could please be added in!

**Comment by james-nash** [comment]
@libertymayc Of course! Done.

**Comment by pseys** [comment]
@libertymayc @james-nash Darrin and I had a quick catch-up on this last night, just to start the ball rolling from a design perspective and get on the same page. It'd be good to get us all together to discuss it more detail.
