### ISSUE TITLE
Checking boxes in a CheckboxGroup causes TypeErrors with React 16

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#2003]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.8.0-rc.4

### Description

The CheckboxGroup seems to be broken when used with React 16 (it works fine with React 18 and I haven't tested React 17). Since we support React 16 (and need to for compatibility with UITK), this needs to be fixed.

(Note: reporting this on behalf of an internal consumer, so adding the "community" label)

### Steps to reproduce

1. Setup an app that uses React 16 and include some basic `CheckboxGroup` code (the [uncontrolled example from our Storybook](https://storybook.saltdesignsystem.com/?path=/docs/core-checkbox--uncontrolled-group) works fine. I've copied the code below for convenience)
1. Check/uncheck the checkboxes a few times

The following runtime error will occur (in my case this seems to happen the second time you uncheck a checkbox in the group):

```
Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
    at http://localhost:3000/static/js/bundle.js:871:34
    at basicStateReducer (http://localhost:3000/static/js/bundle.js:21638:45)
    at updateReducer (http://localhost:3000/static/js/bundle.js:21746:26)
    at updateState (http://localhost:3000/static/js/bundle.js:21830:14)
    at Object.useState (http://localhost:3000/static/js/bundle.js:22456:20)
    at useState (http://localhost:3000/static/js/bundle.js:34813:25)
    at useControlled (http://localhost:3000/static/js/bundle.js:1332:81)
    at CheckboxGroup2 (http://localhost:3000/static/js/bundle.js:863:115)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:21464:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:23232:24)
```

I also see this warnings on the console which might be relevant/helpful:

```
react-dom.development.js:88 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `target` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
    in ForwardRef(CheckboxGroup2) (at App.js:6)
    in App (at src/index.js:13)
    in ViewportProvider (created by SaltProvider)
    in AriaAnnouncerProvider (created by SaltProvider)
    in SaltProvider (at src/index.js:12)
    in StrictMode (at src/index.js:11)
```

---
Example code to use for reproducing:
```js
<CheckboxGroup
  defaultCheckedValues={[
    'option-1',
    'option-2'
  ]}
  onBlur={function _l(){}}
  onChange={function _l(){}}
  onFocus={function _l(){}}
>
  <Checkbox
    label="option 1"
    value="option-1"
  />
  <Checkbox
    label="option 2"
    value="option-2"
  />
  <Checkbox
    label="option 3"
    value="option-3"
  />
</CheckboxGroup>
```

### Expected behavior

You should be able to uncheck as often as you like without crashing the app :-P

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [X] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
Bug ranking score: **53** (using rubric v3)

Priority: **high**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoyNS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6NywiZnJlcXVl
bmN5T3B0aW9ucyI6MTksImltcGFjdE9wdGlvbnMiOjIwLCJhZm
ZlY3RlZERzT3B0aW9ucyI6MTcsInVyZ2VuY3lPcHRpb25zIjox
OSwieEZhY3Rvck9wdGlvbnMiOjE4fSwicnVicmljVmVyc2lvbi
I6M30=
=========== END BUG RUBRIC SCORE DATA ============
```

**Comment by joshwooding** [comment]
Reproduction for easier triage: https://codesandbox.io/s/checkboxgroup-reproduction-wrv8nc
