### ISSUE TITLE
Semicolon at the end of AG Grid theme install instructions

### ISSUE THREAD

**Issue by michaellimair** [jpmorganchase/salt-ds#2018]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

1.1.6 (latest as of 20 July 2023)

### Description

The Storybook documentation includes a semicolon for the installation instructions of Salt's AG Grid theme:
[Link to Documentation](https://storybook.saltdesignsystem.com/iframe?viewMode=docs&id=documentation-data-grid-ag-grid-theme--page#salt)

Installation command for `yarn` should be
```
yarn add @salt-ds/ag-grid-theme
```
and for `npm` should be
```
npm install @salt-ds/ag-grid-theme
```

Having a semicolon at the end of the package name will cause installation issues for users who are trying to install the package.

### Steps to reproduce

Navigate to [the documentation link](https://storybook.saltdesignsystem.com/iframe?viewMode=docs&id=documentation-data-grid-ag-grid-theme--page#salt)

### Expected behavior

Remove semicolon at the end of installation instructions

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by oliffur** [comment]
+1, this should be fixed.

**Comment by james-nash** [comment]
Thanks for bring this issue to our attention. Will get it fixed soon.
