### ISSUE TITLE
Tooltip Desktop Support V2

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2036]
Following the initial work to support Tooltip and other Salt floating components on other platforms e.g. desktop, we've had some feedback from consumers. Overall the solution and API works for them and they are happy that the same solution can be used for various floating components. There are some additional changes that are required:

Issues:
- Tooltip is Flipped (due to modifiers used)
- Tooltip Slightly too high (due to modifiers used)
- Frequency of updates get stale, causing Tooltip to be positioned incorrectly after a window move
- x and y has to be accessed through the style prop, which doesn’t really make sense on desktop
- Don’t have access to width and height in the tooltip

```[tasklist]
### Features Required
- [x] Give consumers a way to update the floating-ui middleware used
- [x] Give consumers a way to adjust the auto-update behaviour of the tooltip
- [x] Pass x and y as independent properties rather than as part of the style prop
- [x] Pass width and height from floating ui to the tooltip component via getTooltipProps
```

**Comment by parsakhan21** [comment]
August 2 - majority of functionality are done; some tidying up to be done (refactor of component required) ; due date tbd (dependent on execute's project)

**Comment by el-dav** [comment]
Update:
- Completed most of the requirments, has some trouble with passing width/height of tooltip so will clarify that requirement with consumers
- In the meantime creating a snapshot release and will request that consumers test out the new release
- Have done a quick check around integration with the new Combobox/Dropdown components, should be relatively straightforward

**Comment by el-dav** [comment]
Consumers will be trying out the snapshot release next week.

**Comment by AnniaT** [comment]
Release done on friday

Some changes to be done this week post review w/ Execute

**Comment by AnniaT** [comment]
PR up for review

**Comment by joshwooding** [comment]
@el-dav working on one small piece of feedback, aiming to get it merged into main soon

**Comment by mark-tate** [comment]
set rag status to red and updated our ship date to one week's time but aiming to ship ASAP

**Comment by joshwooding** [comment]
fixing tests still, aiming to get it merged next week

**Comment by joshwooding** [comment]
Writing docs for it and the PR still need to be ticked, due date end of this week
