### ISSUE TITLE
Badge V2

### ISSUE THREAD

**Issue by parsakhan21** [jpmorganchase/salt-ds#2046]
```[tasklist]
### Checklist
```

```[tasklist]
### Deliverables
```

```[tasklist]
### Features
```

**Comment by navkaur76** [comment]
To discuss during V2 KO (25/07):

- Alternative positioning: standalone/inline
- Discrete dot indicator
- Badge positioning spacing values for top right corner (bespoke/characteristics?)

**Comment by parsakhan21** [comment]
paused for now, moving to backlog

**Comment by origami-z** [comment]
Inline now available
