### ISSUE TITLE
Checkbox/RadioButton label alignment incorrect on Storybook zoom

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2050]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.8.0-rc.5

### Description

On zoom in, the label isn't in alignment with the Checkbox /RadioButton; Storybook only (not browser)

### Steps to reproduce

1. Go to story, see how alignment is fine on default zoom:

<img width="321" alt="Screenshot 2023-07-25 at 09 41 00" src="https://github.com/jpmorganchase/salt-ds/assets/91206958/92b48ace-f04e-4dc2-80fd-aabc7fc92834">

2. Zoom in with storybook zoom tool
3. Notice alignment is wrong with label and icon:

<img width="336" alt="Screenshot 2023-07-25 at 09 42 01" src="https://github.com/jpmorganchase/salt-ds/assets/91206958/737ff946-d03c-4500-a8b4-c030f102e0b6">

### Expected behavior

Alignment should still be correct on zoom

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Need a screenshot and some annotation to illustrate which is wrong.

**Comment by libertymayc** [comment]
> Need a screenshot and some annotation to illustrate what is wrong.

thanks, was going to and couldn't, but remembered it works off vpn! added

**Comment by joshwooding** [comment]
This is actually due to Storybook's usage of the non-standard zoom CSS style. Which they've removed in newer versions. This probably doesn't present itself with the usage of normal browser zoom so I think it's a non-issue.

**Comment by libertymayc** [comment]
> This is actually due to Storybook's usage of the non-standard zoom CSS style. Which they've removed in newer versions. This probably doesn't present itself with the usage of normal browser zoom so I think it's a non-issue.

cool - Zhihao said the same so will close
