### ISSUE TITLE
Create IAI templates in Figma

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#2058]

**Comment by joshwooding** [comment]
replaced all the ff components, working on responsiveness. aim to finish by end of week

**Comment by yunjungyeh** [comment]
🟠12 Sep - Figma Templates: list questions to be discussed with Ben

🟠9/11/12 Sep - Update Figma Templates: Responsive Behaviour (after discuss with Ben)

✅8/9 Sep - Replace to the form field components use the Light library one (Relink the form fields components)

**Comment by joshwooding** [comment]
had a catchup, aligning now on final approach

**Comment by yunjungyeh** [comment]
🟠18 Sep - Tag Ben & Darrin to review the Figma template

✅18 Sep - Add how to use
✅18 Sep - Update the templates in the grid examples (heights in different densities 12, 24, 36, 48)
✅17 Sep - ADD minimum widths & Wrap
✅15 Sep - Catch up with Ben to check the final direction 
✅15 Sep - Catch up with Darrin to discuss Template questions
✅14 Sep - Catch up with Ben: providing 1920,  1280,  960,  600,  320 with grid layout
✅12 Sep - Figma Templates: list questions to be discussed with Ben

**Comment by yunjungyeh** [comment]
@bhoppers2008 to try the template, the final option tbd.

**Comment by yunjungyeh** [comment]
Catched up with @bhoppers2008 and completed the templates
