### ISSUE TITLE
Update differential colors

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2062]
- [ ] Investigate current color values
- [ ] Recommend alternatives
- [ ] Check alternative with VD lead
- [ ] Agree alternative values with MCP
- [ ] Update tokens in Figma theme file
- [ ] Update tokens in Figma mode libraries (light and dark)
- [ ] Publish Figma libraries internally
- [ ] Publish Figma libraries to community
- [ ] Update tokens in code

MCP have highlighted an issue with the color contrast levels of differentials (positive and negative values)

**Comment by joshwooding** [comment]
@pseys I guess this is Theme 2.0 work?

**Comment by pseys** [comment]
This issue is resolved by the color palette work in Salt 2.0 theme.
