### ISSUE TITLE
Data grid error on last page of paginated view

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#2065]
### Package name(s)

Core (@salt-ds/core), Data Grid (@salt-ds/data-grid)

### Package version(s)

Current

### Description

Error thrown on last page of paginated data table

### Steps to reproduce

Using a paginated grid:

- Scroll to the bottom of the grid
- Navigate to the last page of the grid
- The Grid will crash

### Expected behavior

Should correctly display the data grid on the final page

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by shinytoyrobots** [comment]
@joshwooding - from current conversation with James Sol.

**Comment by joshwooding** [comment]
We'll need to contact James Sol for more information on how to reproduce this

**Comment by solcratius** [comment]
Thanks for looking into this.

https://adl-sandbox.apps.test.na-1z.gap.jpmchase.net/#/data-grid-page

In this page Datagrid is scrollable with in. Scroll all the way down in data grid to see the last row of data and then click on page 4 (last page of the grid). Error will appear. But when you don't scroll down and go to the last page it will show the last few rows of data correctly.

https://bitbucketdc.jpmchase.net/projects/DXD/repos/access-design-library/browse/packages/sandbox/src/data-grid-page/index.tsx?at=refs%2Fheads%2Fdevelop

**Comment by james-nash** [comment]
James Sol has shared more details with me. We can't post them here, as they reference internal code. I'll share on Teams internally, but can also email a copy to whoever investigates this one.

**Comment by joshwooding** [comment]
@feliciackh I've added reproduction steps here

**Comment by james-nash** [comment]
Has this been fixed yet?

**Comment by libertymayc** [comment]
@james-nash  #2171 has been ready for a while but still pending getting it merged in
