### ISSUE TITLE
Figma Form Field: status icon and value spacing

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2070]
Update spacing between status icon and value for error and warning messages in Form Field. The current is spacing-100 and should be spacing-75 to be consistent with other status components.

![Image](https://github.com/jpmorganchase/salt-ds/assets/110917213/b63a2d95-8ab5-457f-9eb5-2ecdb9271322)

**Comment by joshwooding** [comment]
@dplsek @bhoppers2008 I'm assuming we still want to do this?

**Comment by origami-z** [comment]
Confirm fixed in the new variable library
