### ISSUE TITLE
When using the AG Grid theme the column separator isn't aligned properly in wrapped column header

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2074]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

latest

### Description

When using the AG Grid theme the column separator isn't aligned properly in grouped columns

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by parsakhan21** [comment]
Aug 4- PR up for review (hoping last bug) - release by eod or by monday latest
