### ISSUE TITLE
Text alignment in AG Grid 

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2079]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Description

Text align has changed from center alignment to top alignment

### Steps to reproduce

Inspect grid

### Expected behavior

Text align has changed from center alignment to top alignment

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
This was only a problem due to overrides, should be fixed with the Salt HD compact theme rather than overrides

**Comment by joshwooding** [comment]
@libertymayc Thanks. I'll close this for now
