### ISSUE TITLE
Salt AG-Grid theme cell content shifting on focus in high density

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2081]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

AG Grid theme @salt-ds/ag-grid-theme

### Description

Salt AG-Grid theme cell content shifting on focus in high density

### Steps to reproduce

Inspection

### Expected behavior

Fix cell content shifting on focus in high density

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
can't reproduce - waiting on more details from MTK

**Comment by parsakhan21** [comment]
Aug 2 - in progress; awaiting dev review - deadline tbd
