### ISSUE TITLE
Salt AG-Grid theme pivot row group chevrons are misaligned with text

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2082]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

@salt-ds/ag-grid-theme

### Description

pivot row group chevrons are misaligned with text

### Steps to reproduce

inspection

### Expected behavior

alignment of chevrons and text in rows

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
This was only a problem due to overrides, should be fixed with the Salt HD compact theme rather than overrides

**Comment by joshwooding** [comment]
@libertymayc Thanks. We can probably close this for now until we confirm it's an issue
