### ISSUE TITLE
Salt AG-Grid theme Status bar styling

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2083]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

@salt-ds/ag-grid-theme

### Description

Status bar Labels font weight
Status bar height
Status bar foreground color

In general, status bar hasnt been defined in salt theme

### Steps to reproduce

inspection vs old theme

### Expected behavior

font weight needs adjusting

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
PR raised

**Comment by parsakhan21** [comment]
augu - same as other ag theme tix
