### ISSUE TITLE
Update Tooltip sharktooth tokens

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2110]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

Salt

### Description

The arrow/ sharktooth in the tooltip isn't scaling as per the Figma component/ spec.

### Steps to reproduce

To follow the other tokens it would just be salt-size-sharktooth rather than specify width or height in the name. We'd clearly indicate this in the Foundation page as with other sizes.

It would be useful if the token is used to drive the height with width scaling proportionately. The token can then be used to also define the gap (from the main body of the tooltip to the 'thing' it is anchored to (in code, the position is not defined by the point of the arrow to the component).

 It would be helpful if we could think about a definition of the token at the same time.

### Expected behavior

NA

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by pseys** [comment]
Suggest the token is --salt-size-sharktooth without mention for height or width inline with other size tokens. 

Is sharktooth the most appropriate name for this or is 'caret' or something similar more widely recognised?

**Comment by origami-z** [comment]
Lowering priority, not business critical

**Comment by origami-z** [comment]
Unassign everyone as no one working on it
