### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2114]
```[tasklist]
### Checklist
- [x] Density (HD, MD, LD, TD)
- [x] Mode (Light, Dark)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [x] Characteristics spec
- [x] Interactions spec, where necessary
- [x] React component
- [ ] Supporting site documentation
- [x] Figma component + guide
```

```[tasklist]
### Features
- [x] Standardise width
- [x] Scrolling
- [x] Update useId call to not use hardcoded fallback and allow custom id
- [x] Review API
- [ ] Ensure aria-labelledby and aria-describedby are always valid even when components are missing
- [ ] Check if we need to update aria-describedby behaviour
- [ ] Check Dialog tests
- [ ] Transition needs standardising to ease in out with perceptible token (plus updating in characteristic spec)
- [x] Update to use Scrim
- [x] Update Dialog to allow description to be optional depending on the content
```

**Comment by bhoppers2008** [comment]
Current labs dialog supports states for:
- Default/ Generic
- Information, Error, Warning, Success

It has feature support for:
- Scrolling area
- Title
- Accent bar
- Optional close button (as DialogAction)

Figma specs can be found [here](https://www.figma.com/file/mwOfVisFMPyiQxtkanggsb/Dialog?type=design&node-id=41%3A15441&mode=design&t=rYJhuxbhujy0OKNp-1).
Figma component is already released.

What is required (in addition to features in description)?
- [ ] Desktop support to be reviewed (with partners)
- [ ] Standardized dialog width to be spec'd (design) and implemented (possibly) as S, M, L across breakpoints
- [ ] Visual affordance for scrolling needs updating (in line with prefs dialog)
- [ ] Border missing from default dialog (spec to be updated–design), plus should be inner border.
- [ ] Contextual examples (design) and site descriptions
- [ ] Review Figma component (after build updates) and update as required.

**Comment by origami-z** [comment]
Reported bug by MTK #2970
