### ISSUE TITLE
Multiline Input Figma component

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2127]

**Comment by joshwooding** [comment]
50% done need to update with adornments and do the Figma component guide

**Comment by AnniaT** [comment]
@bhoppers2008 to prioritise on Friday

**Comment by AnniaT** [comment]
@bhoppers2008 to finalise by COP

**Comment by AnniaT** [comment]
@bhoppers2008 finalising 16/08
