### ISSUE TITLE
Drawer Figma Component

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2129]

**Comment by parsakhan21** [comment]
Aug 2: Nav to work on this when back from holidays

**Comment by AnniaT** [comment]
@pseys to review today

**Comment by pseys** [comment]
@AnniaT all done. @dplsek and I have both added comments. They’re only minor issues.

**Comment by AnniaT** [comment]
Final changes to be completed by EOP

**Comment by pseys** [comment]
@AnniaT I've completed my review and baring one typo its good to go.
