### ISSUE TITLE
Realistic component examples

### ISSUE THREAD

**Issue by delmej** [jpmorganchase/salt-ds#2136]
### Area

UI Components, Documentation

### The problem

Component use story examples in SB currently use placeholder text.

### The solution

Content works with team to create realistic examples.

### Alternatives and examples

n/a

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.
```[tasklist]
### Tasks
```

**Comment by libertymayc** [comment]
Feedback from original email:
- Checkbox Group long text needs wording
- Radio Button Group long text needs wording
- I can't access the link under Link pdf comment
- Salt Provider examples need doing, dont seem to relate
- Accordion has been updated, may need redoing
