### ISSUE TITLE
International Address Input Pattern Add to Site

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2140]
Add pattern documentation to [site patterns](https://www.saltdesignsystem.com/salt/patterns/) section

Design work was done by #1760

**Comment by lilyvc** [comment]
Initial draft PR https://github.com/jpmorganchase/salt-ds/pull/2257

**Comment by lilyvc** [comment]
- Made changes recommend by content
- PR marked as ready for review. Have asked devs to review.

**Comment by yunjungyeh** [comment]
✅5/6 Sep - Design QA
