### ISSUE TITLE
Controlled ListNext component: keyboard nav highlight defaults to first list item instead of pre-selected item 

### ISSUE THREAD

**Issue by feliciackh** [jpmorganchase/salt-ds#2173]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)
[@salt-ds/lab@1.0.0-alpha.15](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.15)

### Description
When ListNext is used as a controlled component in another component i.e. DropdownNext or ComboBoxNext, on keyboard navigation, highlighted item defaults to first list item instead of pre-selected item. 

Affects:
Dropdown Next V1
Combo Box Next V1

### Steps to reproduce
Go to Dropdown Next or Combo Box Next (component) story, select an item. Using keyboard, focus on component and do an `ArrowDown`, regardless of whether there's a selected item or not, first item always gets highlighted. 

### Expected behavior
Go to Dropdown Next or Combo Box Next (component) story, select an item. Using keyboard, focus on component and do an `ArrowDown`:
- If there's a selected item, selected item gets highlighted, and highlight moves from selected item upwards (`ArrowUp`) or downwards (`ArrowDown`) 
- If there's no selected item, first item in list gets highlighted

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
Bug ranking score: **49** (using rubric v3)

Priority: **high**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoyNS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6MTIsImZyZXF1
ZW5jeU9wdGlvbnMiOjE5LCJpbXBhY3RPcHRpb25zIjoxMSwiYW
ZmZWN0ZWREc09wdGlvbnMiOjE3LCJ1cmdlbmN5T3B0aW9ucyI6
MTksInhGYWN0b3JPcHRpb25zIjoxOH0sInJ1YnJpY1ZlcnNpb2
4iOjN9
=========== END BUG RUBRIC SCORE DATA ============
```

**Comment by origami-z** [comment]
Had a quick debug, `activeDescendant` is not being correctly linked between dropdown and list. e.g. `activeDescendant` on dropdown is having a stale value when list is closed, and when list is open, new set of `id`s is being created.

**Comment by mark-tate** [comment]
Hold off picking this up, until we have a discussion on the next steps for List based components

**Comment by origami-z** [comment]
Remove priority label, as no one will pick this up anytime soon.
