### ISSUE TITLE
AG-Grid Theme feedback fixes

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2185]
1. Floating filters 
(Has been redesigned, but MTK unsure about redesign, need @bhoppers2008 to perhaps chat with MTK designer to discuss)
2. Column group cells
- one continuous vertical line instead of short open line, needs fix
3. Header Cell - need design input @bhoppers2008  @dplsek 
- the short vertical line is getting shorter (HD compact) 
- misaligned with the column group cell vertical lines by 2px, needs fix
4. Status bar - need design input @bhoppers2008  @dplsek
- right side text has a smaller font size, needs fix
- the left side looks shifted up and to the left, needs margin
5. Wrong padding in HD/HD compact
- Ticket 8349 (Figma file for DataGrid says each cell should have 4px padding either side, but the AgGrid theme applies 7px)

**Comment by joshwooding** [comment]
@bhoppers2008 to talk to the team about feedback, @libertymayc looking at the blotter demo.

@jpmorganchase/salt-developer to review the PR
