### ISSUE TITLE
Radio Button Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2187]

**Comment by parsakhan21** [comment]
Aug 21 - word doc in progress, catch up after call today

**Comment by joshwooding** [comment]
@jpmorganchase/salt-content this is ready for review.

**Comment by feliciackh** [comment]
Aug 22 - Dev PR up, ready for final eyes/updates

**Comment by parsakhan21** [comment]
Aug 24 - ongoing pr

**Comment by feliciackh** [comment]
build ready for final design review

**Comment by feliciackh** [comment]
Aug 25 - PR to get dev reviews

**Comment by parsakhan21** [comment]
Aug 29 - pushing on dev reviews > merge after

**Comment by feliciackh** [comment]
PR merged
