### ISSUE TITLE
Check Box Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2194]

**Comment by navkaur76** [comment]
Aug 23 - peer review done. Updates being made to ongoing PR. Ready for content review @jpmorganchase/salt-content

**Comment by sion-docs** [comment]
Initial content review done, updates made and some questions added

**Comment by parsakhan21** [comment]
Aug 24 - on going pr

**Comment by feliciackh** [comment]
build ready for final design review

**Comment by feliciackh** [comment]
Aug 25 - PR to get dev reviews

**Comment by feliciackh** [comment]
PR merged
