### ISSUE TITLE
Toggle Button Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2195]

**Comment by navkaur76** [comment]
24 Aug - docs started, in progress

**Comment by parsakhan21** [comment]
Aug 24 - toggle button and toggle button group both are now combined into one doc. Passed onto Shey for peer review, plus content has been tagged for content review before Felicia starts a PR

**Comment by navkaur76** [comment]
Aug 25 - design review of PR complete

**Comment by parsakhan21** [comment]
Aug 29 - pushing on dev reviews > merge after

**Comment by parsakhan21** [comment]
Aug 30 - addressing feedback

**Comment by feliciackh** [comment]
PR merged
