### ISSUE TITLE
Button Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2198]

**Comment by navkaur76** [comment]
Aug 22 - doc started, in progress

**Comment by feliciackh** [comment]
@jpmorganchase/salt-content Button docs ready for content review ty!

**Comment by parsakhan21** [comment]
Aug 29 - pushing on dev reviews > merge after

**Comment by parsakhan21** [comment]
Aug 30 - dev review comments being addressed

**Comment by feliciackh** [comment]
PR merged
