### ISSUE TITLE
Badge Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2199]

**Comment by parsakhan21** [comment]
August 21 - docs in progress - dev: branch already open so link to the issues if there is an active branch so there isnt any double work. Recommend to start in word.

**Comment by parsakhan21** [comment]
@el-dav @yunjungyeh hi both, what are updates for this docs - were you two able to collaborate and get things moving? Thanks!

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content @pseys @bhoppers2008 Badge doc is ready for peer review

**Comment by parsakhan21** [comment]
August 25 - couple of comments to resolve on this - nav to take a look if time.

**Comment by navkaur76** [comment]
Aug 31 - badge doc peer review complete, ready for official content review @jpmorganchase/salt-content

**Comment by sion-docs** [comment]
Content review done.

**Comment by el-dav** [comment]
Ready to merge once checks are complete
