### ISSUE TITLE
Pill Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2200]

**Comment by parsakhan21** [comment]
Aug 21 - will work on doc template

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content @bhoppers2008 @pseys Pill doc is ready to be reviewed :)

**Comment by yunjungyeh** [comment]
21 Aug - Sync on guidance/materials, checking examples
22 Aug - Content doc ready to be reviewed

**Comment by el-dav** [comment]
PR has been created, awaiting dev review

**Comment by parsakhan21** [comment]
Aug 30 - all comments reviewed; need one more tick on it @mikearildbrown
