### ISSUE TITLE
Icon Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2202]

**Comment by el-dav** [comment]
Added initial content/examples from stroybook into the doc

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content @pseys @bhoppers2008 Icon doc is ready for peer review, thanks!

**Comment by pseys** [comment]
@bhoppers2008 Is reviewing this along side Status Indicator

**Comment by parsakhan21** [comment]
Aug 25 - resolving comments; almost done

**Comment by parsakhan21** [comment]
Aug 30 - addressing comments ; should merge soon
