### ISSUE TITLE
Spinner Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2204]

**Comment by el-dav** [comment]
Added initial documentation to the doc from existing storybook

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content @bhoppers2008 @pseys Spinner doc is ready for peer review, thanks!

**Comment by el-dav** [comment]
Few more comments to resolve on the doc. MDX files have been created but will need to be updated
