### ISSUE TITLE
Status Indicator Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2205]

**Comment by el-dav** [comment]
Added initial documentation into the doc from existing storybook

**Comment by yunjungyeh** [comment]
@jpmorganchase/salt-content @bhoppers2008 @pseys Status Indicator is ready for peer review, thanks!

**Comment by sion-docs** [comment]
Content review done and updates made.

**Comment by el-dav** [comment]
Comments mostly respoved. Aiming to be complete by EOD

**Comment by el-dav** [comment]
Have created a PR, awaiting dev review

**Comment by parsakhan21** [comment]
Aug 30 - addressing a few comments
