### ISSUE TITLE
Border Layout Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2206]

**Comment by parsakhan21** [comment]
Aug 21 - adding comments to word doc, call after daily update to review examples. design - look at examples which prob isnt ada compliant - will try to visualize these better

**Comment by bhoppers2008** [comment]
- Examples agreed.
- Examples spec'd up and being built
- Docs copy finalised and sent to Mike for review

**Comment by bhoppers2008** [comment]
Docs approved by content.

**Comment by JoanaMMoreira** [comment]
PR link: https://github.com/jpmorganchase/salt-ds/pull/2274
Preview: https://saltdesignsystem-git-border-layout-docs-fed-team.vercel.app/salt/components/border-layout/examples

**Comment by parsakhan21** [comment]
Aug 25 - ready to release; content and design aprpoved
