### ISSUE TITLE
Grid Layout Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2211]

**Comment by bhoppers2008** [comment]
@mikearildbrown @jpmorganchase/salt-content these docs are ready for review.

**Comment by sion-docs** [comment]
Content review done and updates made

**Comment by parsakhan21** [comment]
Aug 24 - pretty much complete. jo finishing up examples.

**Comment by parsakhan21** [comment]
Aug 25 - dev: pr ready for review

**Comment by parsakhan21** [comment]
Aug 29 - content/ design reviewed, PR is open and needs reviews
