### ISSUE TITLE
Split Layout Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2212]

**Comment by bhoppers2008** [comment]
Parking this component for docs week. Working to have the content and examples spec'd up and ready for build at the next convenient opportunity.

**Comment by parsakhan21** [comment]
Sept 1 - in progress; will pick up with ben next week

**Comment by origami-z** [comment]
Adding @lukeac123

**Comment by origami-z** [comment]
Oct 6, planning to release v1 today
