### ISSUE TITLE
Stack Layout Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2213]

**Comment by bhoppers2008** [comment]
Scoped and adding content and examples for build at a later date.

**Comment by bhoppers2008** [comment]
Copy and examples ready for review by @JoanaMMoreira

**Comment by parsakhan21** [comment]
Aug 29 - have the design specs from Ben and a draft doc that will need to be reviewed by content. Will start working on this once done with Flow

**Comment by JoanaMMoreira** [comment]
@jpmorganchase/salt-content  this is ready for review please

**Comment by parsakhan21** [comment]
Aug 30 - jo working on examples

**Comment by sion-docs** [comment]
Content review done and updates made
