### ISSUE TITLE
ComboBox Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2217]

**Comment by parsakhan21** [comment]
Aug 29 - in progress

**Comment by parsakhan21** [comment]
Aug 30 - word doc in progress

**Comment by feliciackh** [comment]
@jpmorganchase/salt-content @jpmorganchase/salt-design word doc ready for content and design review

**Comment by sion-docs** [comment]
Content review done, updates made and one question asked.

**Comment by navkaur76** [comment]
1 Sep - content review addressed. Pinged @shey-v for design review.

**Comment by navkaur76** [comment]
4 Sep - doc ready for content review @jpmorganchase/salt-content

**Comment by feliciackh** [comment]
PR merged
