### ISSUE TITLE
Progress Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2220]

**Comment by parsakhan21** [comment]
Aug 25 - most of guidance is complete - needs review for double checking as well as accessibility; prob wont finish this week

**Comment by parsakhan21** [comment]
Aug 29 - complete, need to post on site

**Comment by shey-v** [comment]
Have answered the question and added another bit of guidance here - ready for content review @sion-docs

**Comment by sion-docs** [comment]
One outstanding question concerning circular/linear progress indicators

**Comment by joshwooding** [comment]
Duplicate of #2586
