### ISSUE TITLE
Tabs Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2231]

**Comment by shey-v** [comment]
Parking this component for docs week. Working to have the content and examples spec'd up and ready for build at the next convenient opportunity.

**Comment by parsakhan21** [comment]
Aug 30 - ben to review when back @bhoppers2008

**Comment by shey-v** [comment]
Aug 30 - Update: Darrin and Josh need to sort this next week when they are both back @dplsek @joshwooding - Tabs still being built and Darrin is reworking the spec doc and waiting for @bhoppers2008 to review the Figma components.

**Comment by parsakhan21** [comment]
Sept 1 - park for now until darrin/josh address a few things; ben to review figma
