### ISSUE TITLE
Card Documentation

### ISSUE THREAD

**Issue by AnniaT** [jpmorganchase/salt-ds#2237]
[Card Teams Doc](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B1d930e06-65ef-4dc8-bb4e-3995d386b7d7%7D&wdOrigin=TEAMS-WEB.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1)

**Comment by lilyvc** [comment]
21/08 - doc created

**Comment by lilyvc** [comment]
PR raised https://github.com/jpmorganchase/salt-ds/pull/2294

**Comment by ivan-calderon** [comment]
@jpmorganchase/salt-content, updates on Card component are ready for review. TY!

**Comment by parsakhan21** [comment]
@lilyvc  and @ivan-calderon to make updates to issue

**Comment by ivan-calderon** [comment]
Just confirmed with Michael that @lilyvc resolved the issue. [Card MDX page](https://saltdesignsystem-git-card-docs-fed-team.vercel.app/salt/components/card/examples).

**Comment by parsakhan21** [comment]
Aug 29 - complete, awaiting dev review

**Comment by ivan-calderon** [comment]
@jpmorganchase/salt-content we have made an update on the Card doc. Could you please review it? TY

**Comment by sion-docs** [comment]
Content review done and updates made.

**Comment by parsakhan21** [comment]
Sept 1 - needs reviews
