### ISSUE TITLE
Combobox Desktop Support

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2244]
Extending desktop support to Combobox to support advanced usage of floating components in multi-window applications. This ticket builds on the [Tooltip desktop support work](https://github.com/jpmorganchase/salt-ds/issues/2036) and integrates those changes into the Combobox Component

**Comment by joshwooding** [comment]
@el-dav the work is in the same branch as the tooltip desktop support but is blocked until that is complete
