### ISSUE TITLE
Dialog Documentation

### ISSUE THREAD

**Issue by parsakhan21** [jpmorganchase/salt-ds#2269]
[Dialog Teams Doc](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/_layouts/15/Doc.aspx?sourcedoc=%7BD31070B4-A61D-4985-8885-577A3C534FDA%7D&file=Dialog.docx&nav=eyJjIjoxMTg1MzI4NTc1fQ&action=default&mobileredirect=true)

**Comment by ivan-calderon** [comment]
FYI. @sion-docs is reviewing and updating content for Dialog.

**Comment by parsakhan21** [comment]
aug 24 - Will re-work focus examples. Need to provide assets to Lily.

**Comment by parsakhan21** [comment]
Aug 25 - issues displaying on site (josh to look into fix)

**Comment by lilyvc** [comment]
PR - https://github.com/jpmorganchase/salt-ds/pull/2306

**Comment by parsakhan21** [comment]
Aug 30 - example not working, lily will address (consult with other devs)

**Comment by parsakhan21** [comment]
Sep 1 - will address example issue potential solutions

**Comment by lilyvc** [comment]
Fix ok'd by devs, PR marked as ready for review.
