### ISSUE TITLE
Accordion Documentation

### ISSUE THREAD

**Issue by parsakhan21** [jpmorganchase/salt-ds#2270]
[Accordion Teams Doc](https://sites.jpmchase.com/:w:/r/sites/JPMUIToolkit/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B83be56bf-4284-4c34-9035-b4118a9293f2%7D&wdOrigin=TEAMS-WEB.teamsSdk.openFilePreview&wdExp=TEAMS-CONTROL&web=1)

**Comment by parsakhan21** [comment]
@ivan-calderon  issue created

**Comment by sion-docs** [comment]
First content review done, updates made + one question

**Comment by ivan-calderon** [comment]
I left a few comments in the Accessibility section.

**Comment by parsakhan21** [comment]
aug 24 - WIP. Need to double check if there are comments from content.

**Comment by parsakhan21** [comment]
@jpmorganchase/salt-content

**Comment by sion-docs** [comment]
No further comments

**Comment by parsakhan21** [comment]
Aug 29 - Minor change requested on the 'inline badge' example

**Comment by parsakhan21** [comment]
Aug 30 - very close to being completed - today. Requires a few approvals.
