### ISSUE TITLE
When using Stack Layout touch density has a smaller gap than low density

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2278]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

latest

### Description

Low density has a bigger gap than touch density using Stack Layout.

### Steps to reproduce

https://codesandbox.io/s/stack-layout-touch-density-gap-issue-y2l89j

### Expected behavior

Touch  density should have a bigger gap.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
This is because of a CSS specificity issue. Flex Layout styling is interfering.

**Comment by Fercas123** [comment]
it seems fine that it is inheriting from flex, but the issues originates in flexLayout, `--flexLayout-gap-density-multiplier` is being reassigned to `2` for `.salt-density-touch`
