### ISSUE TITLE
The `variant` prop for Text and Link should be deprecated and renamed to `color`

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2286]
### Area

UI Components

### The problem

The attribute they are changing is referred to as `color` in most of our documentation and the usage of `variant` here doesn't map to any of our other components

### The solution

Renamed `variant` to `color` in a backwards-compatible way and remove `variant` in v2.

### Alternatives and examples

N/A

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by libertymayc** [comment]
> the usage of variant here doesn't map to any of our other components

Variant elsewhere is changing between the primary and secondary tokens, granted these only change color, I don't see how it's different?

**Comment by origami-z** [comment]
`variant` is the correct term derived from characteristics. `color` in Icon was more recent and not aligned?

**Comment by joshwooding** [comment]
@origami-z This decision has already been discussed with design. If you have any concerns please start a chat on Teams

**Comment by origami-z** [comment]
Done in #2619
