### ISSUE TITLE
Navigation Pattern

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2328]
Define a navigation pattern for the site which provides users with guidance they need to compose navigation within their own websites or applications following best practises and using Salt's navigation components (Navigation Item and Tabs). 

**Scope for v1:**
Initial version will focus on Navigation Item component. We will at some point in the near future fold in the Tabs side of things, build up combined navigation and the hierarchy of how they should be used together - that will depend on when tabs docs are released.

_We are deprioritising the examples aspect for a Horizontal nav in this release, because there is a dependancy on the AppHeader pattern which we will need first._

For v2 and v3 we can fold in the guidance for Tabs and more complex structures of horizontal navigation e.g. a mega-menu and things we have seen in MCP such as pinning / favouriting. 

---

Dev task to add to site: #2536

**Comment by shey-v** [comment]
1st Sept - put together a first draft of navigation pattern content, ready for @bhoppers2008 to review next week

**Comment by shey-v** [comment]
11 sept - scope refined and reflected in issue description. Focus is on navigation item component, not tabs until this documentation is finalised. examples of vertical navigation currently being collected from dxd designers and will be created for testing purposes to see if our pattern guidance and components are fit for purpose before publishing this pattern. @dplsek is helping me with creating the visual examples.

**Comment by joshwooding** [comment]
Ongoing, tidying up examples. Spacing questions to be discussed about Navigation Item. Draft is mostly complete and being peer reviewed

**Comment by shey-v** [comment]
Have made amends to Navigation Item spacing formula, with @dplsek and @JoanaMMoreira. First draft of pattern currently undergoing content review. Have set up time with @bhoppers2008 tomorrow to finalise pattern guidance so far.

**Comment by shey-v** [comment]
Content have come back with the first round of copy amends, currently updating the pattern to reflect suggestions. Making tweaks to the format and mocking up some vertical nav templates to include with this release. Will aim to have final version ready for Friday for a final round of content + design reviews.

**Comment by shey-v** [comment]
Pattern ready for @bhoppers2008 review. Has been through content review and updates have been reflected in the latest version in Figma. Once signed off, we can assign to dev to get on to the site.

**Comment by shey-v** [comment]
Ben has reviewed, waiting for a final content review @mikearildbrown. 

Caught up with Mark Tate and he mentioned he will allocate someone from dev to work with to get up on to the site this week and release the navigation item spacing updates (which have been merged to a PR) at the same time.

**Comment by shey-v** [comment]
v1 complete. ready for dev. New ticket has been created: https://github.com/jpmorganchase/salt-ds/issues/2536
