### ISSUE TITLE
Component Doc Usability Testing

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2344]
Usability tests to quantify improvements with the new component docs versus the old ones.

Key Metrics 
- Efficiency - as measured by time on task 
- Discoverability - as measured by error rate 
- Satisfaction 
- Usability, Trust, Appearance, Loyalty - SUPR_Q

```[tasklist]
### Tasks
- [x] Plan out usability test
- [x] Identify participants - going to recruit external audience via UZ
- [x] Schedule test
- [x] Complete test
- [x] Report results
```

**Comment by tadxd** [comment]
Sep-8: Brief drafted; in review with leads.

**Comment by tadxd** [comment]
Sep-15: Programming test in UZ; will look to run this weekend / early next week

**Comment by tadxd** [comment]
Sep-22: Test is live, being closed today. Will conduct analysis.
