### ISSUE TITLE
Review Multiline Input read-only state

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2355]
We made the change in #2179 to change read-only to accept focus.

We need to make sure that the change has been implemented correctly. Some questions:

```[tasklist]
### Tasks
- [x] Decide what happens when validation status and read-only are both present
```

**Comment by origami-z** [comment]
Dropping priority, no one reported issue yet.

**Comment by joshwooding** [comment]
The current behaviour is correct:

- Multiline input shows status when read-only and removes it when disabled
