### ISSUE TITLE
App Header pattern design

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2356]
## Description   
Describe the pattern 

## Context   
Describe scenarios where the pattern is most applicable 

## Extra information  
Dev work to push this to site in #2669

**Comment by origami-z** [comment]
25 Oct - Ivan started research

**Comment by joshwooding** [comment]
Aiming for ready for review by end of the week. Moved to Amber. Separate ticket should be created to track the pattern being added to the site

**Comment by origami-z** [comment]
3 Nov - wip, not to be mixed with button bar & navigation, will take another week

**Comment by james-nash** [comment]
Once the pattern has been published to our site, it might be a good idea to review our site's current header. Does it align with the pattern? If not, should we update it accordingly.

We should be practicing what we preach :-)

**Comment by joshwooding** [comment]
Shared for review. Still needs content review, will be sent after the design review has been completed. Pattern to be completed by end of this week.

@bhoppers2008 to review this afternoon

**Comment by origami-z** [comment]
17 Nov - Doc page designed

**Comment by origami-z** [comment]
20 Nov - discussing how to build examples

**Comment by origami-z** [comment]
22 Nov - updated details on how to build (which components), aim to finish doc before holiday.
