### ISSUE TITLE
Preferences Dialog Pattern

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2368]
## Description   
Describe the pattern 

## Context   
Describe scenarios where the pattern is most applicable 

## Extra information  
Add extra info

**Comment by origami-z** [comment]
22 Nov - Kick off tomrrow

**Comment by origami-z** [comment]
24 Nov - KO done, consolidate preference pattern & pref dialog, reach out to stakeholders

**Comment by origami-z** [comment]
27 Nov - starting this afternoon.

**Comment by origami-z** [comment]
8 Dec - caught up on VD decisions, doing Figma examples, outstanding question around vertical nav v.s. tab.

**Comment by origami-z** [comment]
11 Dec - question around nav v.s. tab

**Comment by joshwooding** [comment]
15 Dec - Waiting for @bhoppers2008. Trying to get an answer on Tabs vs Vertical Navigation. Content needs to be shared with @mikearildbrown

**Comment by joshwooding** [comment]
18 Dec - @bhoppers2008 is currently reviewing. @mikearildbrown to review after the design review.

**Comment by joshwooding** [comment]
20 Dec - @bhoppers2008 wants to use Vertical Navigation. The rest of the pattern is going well, working on content changes.

**Comment by joshwooding** [comment]
09/01 - Had a catch up about the visual design of the examples. Will reach out to @bhoppers2008 for a design review this week. Darrin to review the content using the copy checker

**Comment by navkaur76** [comment]
22/01 - Content review carried out by Mike last week - feedback addressed. Visual examples + figma stickersheet updated. Pattern is now complete and ready to be picked up by a dev.

**Comment by joshwooding** [comment]
Published to the site https://www.saltdesignsystem.com/salt/patterns/preferences-dialog
