### ISSUE TITLE
Switch label vertical alignment

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2372]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

[@salt-ds/lab@1.0.0-alpha.16](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.16)

### Description

Switch is not vertically alignment to the center, should be spacing-25 from the top

### Steps to reproduce

https://storybook.saltdesignsystem.com/?path=/story/lab-switch-qa--all-examples-grid

### Expected behavior

Label vertically aligned

### Operating system

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by james-nash** [comment]
Bug ranking score: **41** (using rubric v3)

Priority: **medium**

```
========== BEGIN BUG RUBRIC SCORE DATA ===========
eyJ2YWx1ZXMiOnsiYWZmZWN0ZWRQZW9wbGVPcHRpb25zIjoyNS
wiYWZmZWN0ZWRDb21wb25lbnRzT3B0aW9ucyI6NywiZnJlcXVl
bmN5T3B0aW9ucyI6MjUsImltcGFjdE9wdGlvbnMiOjEsImFmZm
VjdGVkRHNPcHRpb25zIjoxNywidXJnZW5jeU9wdGlvbnMiOjE5
LCJ4RmFjdG9yT3B0aW9ucyI6MTh9LCJydWJyaWNWZXJzaW9uIj
ozfQ==
=========== END BUG RUBRIC SCORE DATA ============
```

**Comment by origami-z** [comment]
16 Oct - Updated code, pending design review on Chromatic
