### ISSUE TITLE
International Phone Number Pattern

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#2379]
Dev task for adding to site: #2537

**Comment by yunjungyeh** [comment]
🟠11/12 Sep - List more questions to be answered/discussed (e.g. +1 can be US and Canada)
🟠11/12 Sep - Research on International Phone Number 
🟠11/12 Sep - Review LOB's file

✅11 Sep - Create a new file for it
✅11 Sep - list the further tasks > Sync with LOB designer > Facilitate Tech/Product discussions
✅11 Sep - Schedule some time with LOB designer
✅11 Sep - Have a meeting with the team

✅5 Sep - Robin introduce the team > Schedule some time to introduce International Address Input Pattern and to discuss further collaboration for International Phone Number.

**Comment by yunjungyeh** [comment]
✅21 Sep - Catch up with Yukimi and agree on the design  
Agreed designs: - Remove country symbol - Use stack layout - Include Auto-generated number placeholder 
To-dos: 
✅- Yun double check the colour of XXXXX  (placeholder)  should be secondary or disabled 
- Yun double check with Zarko if we use: Controls/Input + Decoration/Primary input + decoration

✅21 Sep - Reply email - share the proposed pattern and details
✅20 Sep - Update the research details + rationale behind them and Design mockups using product designs (Stack layout and Inline Layout) update Dropdown list
✅19 Sep - Check what questions to ask
✅19 Sep - Update the research details / Prepare the agenda for the meeting
✅19 Sep - Research: abbreviation UK (+44) vs United Kingdom (+44)

✅19 Sep - Update the details/Content in the template

**Comment by joshwooding** [comment]
@bhoppers2008 to catch up with @yunjungyeh on Monday. To figure out state/hand over

**Comment by yunjungyeh** [comment]
✅3 Oct - Update guidance > ask Ben to review

✅2 Oct - Review guidance with Ben
✅2 Oct - User testing to see if country symbol is good

✅29 Sep/1 Oct - write Guidance content

✅29 Sep - Check with Josh: about country symbol implementation questions

✅29 Sep - reply email to follow up and update

**Comment by yunjungyeh** [comment]
17 Oct - Synced with @Fercas123 and got images updated

**Comment by origami-z** [comment]
Design work done, Dev work to add to site in #2537
