### ISSUE TITLE
Button Bar pattern

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2380]
## Description   
Displays groups of core and secondary actions (as buttons).
Button position and order varies depending on the container (dialog or not) and the context (multi-step or single flow). 
The position of buttons with the bar is also driven by breakpoint. If desired, at a certain breakpoint, buttons can stack and fill the width of the bar. In this case, actions are ordered core at top, secondary at bottom.

## Context   
Button Bar is common to, but not exclusively for, Forms. It's generally used to display groups of core and secondary actions, following user input.
A Button Bar is also commonly found within a Dialog.

## Extra information  
UITK Button Bar docs can be found [here](https://uitk.gaiacloud.jpmchase.net/build/components/button-bar).
Button Bar guidance can be abstracted from the Salt Forms pattern (Forms pattern can be updated to point towards the Button Bar pattern).

(Add extra info)
```[tasklist]
### Dev Tasks
- [ ] Reverse engineer UITK and work out feature set covered in code
- [ ] implement features using Salt component in storybook, ordered by difficulties
- [ ] add a new pattern page from design without live code example
- [ ] investigate best way to share code between storybook and live code shown on site
- [ ] add live code example to pattern page
```

**Comment by mark-tate** [comment]
keep as standalone dev work, so we don't create any blocker from design (just storybook examples)

**Comment by lilyvc** [comment]
What is the work I need to do here? Is it going to be a page to copy over from Figma like the other patterns?

**Comment by joshwooding** [comment]
@lilyvc It's a bit more work than that. I'm unsure if anything has changed over the 2 weeks I've been off. Still, the general approach would have been reverse engineering the rules that were built into the Button Bar previously and documenting what they are in a way that users can understand. I would probably then add a stretch goal to add examples showing how to achieve that with Salt

**Comment by origami-z** [comment]
25 Oct - design first pass done, pending review. Dev - adding a few examples to Salt storybook.

**Comment by origami-z** [comment]
Pushing out dates to get design work published to site, which was not planned in the original target

**Comment by joshwooding** [comment]
Still on track for the deadline

**Comment by origami-z** [comment]
3 Nov - design guide reviewed today, page publish WIP

**Comment by shey-v** [comment]
6 Nov - under review. Some changes anticipated from content. Dev reviews pending.

**Comment by joshwooding** [comment]
@mikearildbrown to leave comments on the PR. Target date end of the week depending on the content updates.

**Comment by lilyvc** [comment]
https://www.saltdesignsystem.com/salt/patterns/button-bar
