### ISSUE TITLE
Content Status pattern

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2381]
## Description   

- Content Status will be a Salt Pattern. 
- The pattern will document how status messages are communicated. 
- The initial scope of the pattern is to document how the UITK Status Content component can be built using Salt components and styles.

## Context   
The pattern is most commonly found where content in a container is replaced with a status message (as information, error, warning, success or loading).

## Extra information  

- UITK Content Status docs can be found [here](https://uitk.gaiacloud.jpmchase.net/build/components/content-status).
- Content Status guidance should consider documentation for Status Indicator component and Progress/Spinner components (when should one be used over another).
- The docs should capture error messaging guidance that has already been completed by the content team (Delme has the information).
- Build needs to align to Salt characteristics.
- Figma Stickers will be published to the Salt component library (to be co-ordinated with Ivan).
- LOW PRIORITY If time allows, this release could extend to other types of content status pattern that the team might be aware of (for example, a compact pattern for use in components, a low performance intensive version (VIDA text only label in cells, etc).

**Comment by lilyvc** [comment]
23/01 - Kickoff held today. Lily to build UITK examples in Storybook and Yun to begin designing page in Figma.

**Comment by lilyvc** [comment]
25/01 - examples built in this [PR](https://github.com/jpmorganchase/salt-ds/pull/2943). Will add content from Figma to site page next week.

**Comment by yunjungyeh** [comment]
24-25/1 - working on Figma stickers & site doc

**Comment by yunjungyeh** [comment]
29/01 - Reviewed site doc with @mikearildbrown
