### ISSUE TITLE
Metric pattern Design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2382]
## Description   
Describe the pattern 

## Context   
Describe scenarios where the pattern is most applicable 

## Extra information  
UITK Metric docs can be found.
Salt Metric needs to consider updated Salt Typography and Spacing foundations.

(Add extra info)

**Comment by origami-z** [comment]
Adjust target date with additional stakeholder consideration needed.

**Comment by origami-z** [comment]
Revise assignee and timeline

**Comment by origami-z** [comment]
22 Nov - start review what we have, need adjust timeline

**Comment by yunjungyeh** [comment]
Scope: 

Design: Pattern guidance, Figma templates
Code: Storybook example, Pattern guidance site page

**Comment by origami-z** [comment]
1 Dec - first draft of content ready, verify from design / dev POV, while Mike is away

**Comment by origami-z** [comment]
4 Dec - Caught up with @lilyvc, code updated. Content ready.

**Comment by origami-z** [comment]
11 Dec - updating Figma sticker and images, from @mark-tate 's feedback.

**Comment by joshwooding** [comment]
18 Dec - Was released last Friday.
