### ISSUE TITLE
List Builder Pattern

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2384]
## Description   
Describe the pattern 

## Context   
Describe scenarios where the pattern is most applicable 

## Extra information  
UITK List Builder docs can be found [here](https://uitk.gaiacloud.jpmchase.net/build/components/list-builder).
Salt List Builder pattern should consider the requirements of the markets business.
Should consider use of Tree in the Pick list.

(Add extra info)
```[tasklist]
### Tasks
```

**Comment by joshwooding** [comment]
Published to the site https://www.saltdesignsystem.com/salt/patterns/list-builder
