### ISSUE TITLE
Split Button Pattern (Publish to Site)

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2397]
### Notes
- Composed of SegmentedButtonGroup, Button, Menu
- Supports button variants and menu features i.e., button = cta, primary, secondary and menu = groups, icons in items
- Has Primary + Additional actions hidden in a menu
-  Can contain multiple primary actions
- Needs to reference button guidance - label, icon-only, tooltip
- Contextual examples can be collected from stakeholders.
- Add accessibility guidance to pattern page (?)

```[tasklist]
### Deliverables
- [x] Pattern page on site
- [x] Figma sticker
- [ ] Storybook examples
```

**Comment by mark-tate** [comment]
Converted to a Pattern, with have Segmented Button as a component published to Core and Split Button will be a design pattern

**Comment by mark-tate** [comment]
https://www.saltdesignsystem.com/salt/patterns/split-button

examples will follow as a stretch goal during Sulley/Ursula
