### ISSUE TITLE
Add dynamic list position to combo box

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2407]
## Description
The overlay list is displayed beneath the field by default.
If there is not enough space beneath the field, the list is displayed above the field. 
If the list is visible and space is insufficient beneath the field, the list should remain visible but automatically position itself above the field. 

## Notes
This feature has a dependancy on the 'popper' type positioning, previously existing in UITK.  
This issue does not require design.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

**Comment by joshwooding** [comment]
This has already been delivered.
