### ISSUE TITLE
Add FreeText (FreeSolo) entry to combo box Storybook examples

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2409]
As a user of ComboBox I can add select a value in ComboBox that is not part of the List.

- Add example to Storybook of how this can be achieved

**Comment by mark-tate** [comment]
This is thought to be possible already, so we could rescope this to create an example on the doc site
Suggest Pepper team try to compose an example that supports FreeSolo and we discuss from there

**Comment by origami-z** [comment]
Example try which doesn't work fully: https://stackblitz.com/edit/salt-template-8udmuj?file=App.tsx

**Comment by joshwooding** [comment]
Close by #3358
