### ISSUE TITLE
Create component for file drop zone

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2419]
## Description
The file drop zone component should include default, disabled, and drag and drop states.

There is a version of component existed in lab, try reuse it.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

**Comment by origami-z** [comment]
Push out a week so previous work can be addressed first

**Comment by origami-z** [comment]
20 Nov - Started design, will meet with stakeholders

**Comment by origami-z** [comment]
22 Nov - working on characteristics, did some research.

**Comment by origami-z** [comment]
1 Dec - Design component ready, minor discussion on states. KO next Monday.

**Comment by origami-z** [comment]
6 Dec - discussion around accessibility

**Comment by joshwooding** [comment]
18 Dec - Making a couple of improvements to the API. Docs PR has been created. Looking to merge the code PR today. Figma component/guide still waiting to be merged.
