### ISSUE TITLE
Tree Component Design

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2422]
## Description
TBD.

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

**Comment by origami-z** [comment]
8 Dec - de-prioritized

**Comment by joshwooding** [comment]
Snipped from #2882 

@navkaur76 
> Kick off meeting notes (w/ Darrin, Josh, Mike + Nav):
> 
> Variants to focus on for this sprint:
> 
> Default/single-select
> Checkbox support + relevant multi-select behaviour. Would be nice to include shift key behaviour for selecting/highlighting multiple tree items
> Icon support
> Styling updates this sprint:
> 
> Will use chevrons, not triangle/caret icon
> Tree updated with List styling
> Park for future sprint:
> 
> All asynchronous states
> Error state
> Drag and drop functionality + styling
> Core partners: MTK (Richard S.) + Fusion (Oykun)

**Comment by mark-tate** [comment]
complete, ready for dev [#2882](https://github.com/jpmorganchase/salt-ds/issues/2882)
