### ISSUE TITLE
Contact details pattern examples

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#2430]
- [ ] Add examples to storybook
- [ ] Migration QA to StackOverflow

**Comment by origami-z** [comment]
8 Dec - started working, examples being added to storybook

**Comment by origami-z** [comment]
11 Dec - adding last variant

**Comment by joshwooding** [comment]
18 Dec - making changes based on PR feedback.

**Comment by yunjungyeh** [comment]
@bhoppers2008 asked me to pick up the site doc for this, cc @lukeac123 @dplsek

**Comment by joshwooding** [comment]
20 Dec - Reviewed and ready to merge.
