### ISSUE TITLE
AEM component Salt style alignment

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2458]
DP Content have requested assistance to migrate their AEM component library to use Salt styling. 

- Details to be added.

**Comment by joshwooding** [comment]
@ivan-calderon working with @dplsek before meeting with the adopting team. Before the meeting. Better understanding of timeframe after Friday

**Comment by origami-z** [comment]
Oct 6 - discussion ongoing, make progress with spacing & typography

**Comment by origami-z** [comment]
Done last friday
