### ISSUE TITLE
AG Grid popup heights not recalculated on density change

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2479]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

v1.3.0

### Description

According to https://www.ag-grid.com/javascript-data-grid/global-style-customisation-compactness/?#changing-row-and-header-heights-at-runtime, changing --ag-list-item-height should force cached calculated values to recalculate. The demo on this page works for this.

But, from what I have been experiencing, the values aren't being recalculated for us with this method... which causes a significant issue when the density is changed (e.g., density changed HD -> TD - see overlap on sunshine icon):

<img width="92" alt="Screenshot 2023-09-19 at 3 12 17 PM" src="https://github.com/jpmorganchase/salt-ds/assets/91206958/ee45c674-7de9-4124-8dd2-af3187ff5b36">

I'm not sure if this could be because we need to upgrade ag grid? I can't find this being linked to a version. https://github.com/jpmorganchase/salt-ds/pull/2469 shows that the solution described in the ag-grid docs above not working in Storybook. I've also tried adding extra classes just for this value change (--ag-list-item-height) and changing it on ag-popup itself, to no avail. Notice how the height is being calculated so we can't apply our own styles (which makes sense, we should just be able to change the --ag-list-item-height to cause it to be recalculated as explained above)

<img width="263" alt="Screenshot 2023-09-19 at 4 03 06 PM" src="https://github.com/jpmorganchase/salt-ds/assets/91206958/d4a3ba5f-c08b-4f37-a76c-0f8b5d895ec4">

The row and header height are fine changing between densities because of the API callbacks provided https://github.com/jpmorganchase/salt-ds/blob/main/packages/ag-grid-theme/stories/dependencies/useAgGridHelpers.ts#L65. It seems Rustam probably already knew of this being an issue and also couldn't find a fix: https://github.com/jpmorganchase/salt-ds/blob/main/packages/ag-grid-theme/stories/dependencies/useAgGridHelpers.ts#L68. Weirdly, ag grid seems to only allow you to set header and row height here, despite listing --ag-list-item-height as a variable within the page https://www.ag-grid.com/javascript-data-grid/global-style-customisation-compactness. And api.getSizesForCurrentTheme() also only returns row and header height. 

Note: The values are only calculated when the pop up shows up, so any filters that haven't already been opened won't be affected by density change.
Related:
https://stackoverflow.com/questions/73877337/increase-the-height-of-filter-list-ag-grid-set-filter
https://stackoverflow.com/questions/56293765/aggrid-how-to-set-the-line-height-of-a-ag-virtual-list-item-inside-a-sidebar-fi

This might be something that can be fixed in https://github.com/jpmorganchase/salt-ds/issues/2103

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

**Comment by origami-z** [comment]
Resolved by #3195
