### ISSUE TITLE
Combobox Next / Dropdown Next is mis-using blur event to close dropdown list

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2487]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

[@salt-ds/lab@1.0.0-alpha.17](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.17)

### Description

[Combobox Next](https://github.com/jpmorganchase/salt-ds/blob/8a57226922f9fcecdff5d27a55e920c3c517757a/packages/lab/src/combo-box-next/useComboBox.tsx#L72) and [Dropdown Next](https://github.com/jpmorganchase/salt-ds/blob/8a57226922f9fcecdff5d27a55e920c3c517757a/packages/lab/src/dropdown-next/useDropdownNext.tsx#L129) are both using trigger elements' blur event to close dropdown list, rather than detecting click outside of list (`useInteractions` `useDismiss`) and selection on list. This causes several issues, e.g., in desktop where the list is dismissed before selection handler can detect and fire, or clicking/dragging scrollbar of the list will dismiss the list.

Thanks to @jchristou for raising this and suggesting alternative.

### Steps to reproduce

See storybook
- http://localhost:6006/?path=/story/lab-dropdown-next--default
- http://localhost:6006/?path=/story/lab-combo-box-next--default

### Expected behavior

/

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by lukeac123** [comment]
pr merged - https://github.com/jpmorganchase/salt-ds/pull/2551

**Comment by joshwooding** [comment]
PR, up needs reviews
