### ISSUE TITLE
Edit supported platforms page

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2494]
Our supported platforms page has a few issues.

- Some grammatical issues.
- IE11 listed as supported when it's not.
- Safari version listed twice when it's the same value.
- We use >= to show "X or above" but may not be clear to all readers.
- Browser support in a table but only has two rows—not ideal for mobile.

Content to edit the page and tweak the above issues.

**Comment by joshwooding** [comment]
Yep 0 support for IE
