### ISSUE TITLE
ComboboxNext inside Dialog renders the list popup under the Dialog overlay

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#2495]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

Latest alpha 1.0.0.17

### Description

Both Dialog and ComboboxNext use floating-ui Portal and therefore render side by side. Therefore, they are competing for z-index and Dialog is using a higher z-index.

### Steps to reproduce

Render an open Dialog with an open ComboboxNext

### Expected behavior

ComboboxNext list popup should render above Dialog

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by lukeac123** [comment]
pr merged - https://github.com/jpmorganchase/salt-ds/pull/2551

**Comment by ZarkoPernar** [comment]
@origami-z should we close this issue? It looks like it is done

**Comment by origami-z** [comment]
Done by #2551
