### ISSUE TITLE
FormField adds extra "padding" below the input

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#2497]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.8.1

### Description

FormField declares three grid template areas, even when the elements for those areas are not rendered. For example, this is the grid-template-area by default:

```css
.saltFormField-labelTop {
grid-template-areas:
        "label"
        "controls"
        "helperText";
}
```

The issue is gap property  is always applied to all three areas, even when we are rendering no helper text which results in additional "padding" below form field.

<img width="334" alt="Screenshot 2023-09-22 at 17 28 00" src="https://github.com/jpmorganchase/salt-ds/assets/8259681/0cb960cf-9ecd-42c4-9571-6b957ebd3b30">

### Steps to reproduce

Check out an example without helper text here https://www.saltdesignsystem.com/salt/components/form-field/examples

### Expected behavior

The gap between the input and helper text should not be applied when there is no helper text. Only one gap should be applied, between the label and the input.

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by ZarkoPernar** [comment]
@libertymayc I assume this would be slightly annoying to fix since FF is not rendering helper text directly so we have to notify up from helper text. Or use `:has` with progressive enhancement.

**Comment by mark-tate** [comment]
we can’t use has, it breaks the minimum browser support

**Comment by lilyvc** [comment]
I also noticed if you have two form field inputs side by side, and one has helper text, then the inputs are not aligned

**Comment by libertymayc** [comment]
> I also noticed if you have two form field inputs side by side, and one has helper text, then the inputs are not aligned

that's a good spot - without giving too much thought, I think the only way we could remedy this with the structure of the form field is putting the responsibility on the user to set the heights
