### ISSUE TITLE
Make Chromatic action run on forked PR

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#251]
Chromatic doesn't run on forked PR, e.g. https://github.com/jpmorganchase/uitk/pull/247. [Chromatic doc](https://www.chromatic.com/docs/github-actions#forked-repositories) suggests to move the token to project.

**Comment by joshwooding** [comment]
Maybe we can use something like this: https://github.com/chromaui/chromatic-cli/issues/196#issuecomment-1114337113
