### ISSUE TITLE
Remove components table from index page

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2516]
The components index page has a table that lists all available and upcoming components. The vertical nav and roadmap mostly duplicate the table's content, with two key exceptions:

- Table shows which components are still in lab
- Table links to a few docs that are still only available in Storybook

Once the below tasks are complete, the table will be redundant and we can remove it.

```[tasklist]
### Tasks
- [ ] #2502 
- [ ] #2506 
- [ ] #2212 
- [ ] #2229 
- [ ] #2228 
- [ ] Remove table from components/index page
```

**Comment by james-nash** [comment]
I think this makes sense. As you say, once those other issues are completed, the table will be pretty much redundant.

I'd say the info about when a component was first released is useful, but not critical. I think it could be surfaced somewhere on the component pages (maybe in the right-hand column somewhere?), but even if we didn't have anything like that in place yet, it shouldn't block the removal of the table.

**Comment by origami-z** [comment]
16 Oct - decision to be made on whether removing the table is needed. Pending ag grid doc to be moved.
