### ISSUE TITLE
Add Categorical color palette

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2523]
Colors in Figma: https://www.figma.com/design/WOxL4BTkDq2ghzDVoJ0euz/Salt-2-Palette-%E2%80%93-Categorical-(final)-r1?node-id=1361-2597&t=7G6DEF8lZqxyscB6-1

```[tasklist]
### Tasks
- [x] Define categorical color palette
- [x] Update Figma
- [x] Update code (@origami-z) #3534
```

**Comment by bhoppers2008** [comment]
18th Jan meeting notes:

- Will be known as 'Category' palette.
- Will be part of Salt Theming release (formally 2.0).
- Full set of colours will be available at Foundations, with 3 levels per colour, per mode.
- Will be mapped to the palette layer (not characteristic).
- Palette layer naming will be colour agnostic (ie., --cat-1, --cat-2, --cat-3, etc).
- Levels will be defined as --weak, --default and --strong.

@pseys @dplsek @origami-z @joshwooding

**Comment by pseys** [comment]
- Token structure and relationship mapped in Figma. 
- In the process of adding colors to variables-driven library

**Comment by origami-z** [comment]
Reopen until characteristics token is in
