### ISSUE TITLE
Theme 1.0 Code Updates from Design

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2530]
Details to be provided by @pseys

**Comment by joshwooding** [comment]
Potentially related: https://github.com/jpmorganchase/salt-ds/issues/1951

**Comment by pseys** [comment]
> Potentially related: #1951

I can confirm that this is related and has now been included within the Excel summary. FYI @feliciackh

**Comment by origami-z** [comment]
Need more time to go through design iteration. Pushing target date and RAG to amber

**Comment by joshwooding** [comment]
Spoken with @pseys to arrange a 30 min call for Tues/Wed

**Comment by origami-z** [comment]
Unblocked, with new token names agreed (mostly around `text` => `content` characteristics)

**Comment by joshwooding** [comment]
@feliciackh addressing @pseys feedback. Target date is end of this week

**Comment by origami-z** [comment]
13 Nov - Design questions resolved, PR to be dev reviewed

**Comment by origami-z** [comment]
17 Nov - Token changes merged, 2 more follow up updates on doc
