### ISSUE TITLE
ag grid theme package v2 feedback and alpha release

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2531]
Wait for MTK feedback and release.

The issue is created, so the main dev work is scoped on [release plan](https://github.com/orgs/jpmorganchase/projects/18) with the feedback timeframe separate.

**Comment by origami-z** [comment]
16 Oct - adding tests on cypress, to cover items not covered by Chromatic

**Comment by joshwooding** [comment]
Updated the target date to match #2103

**Comment by origami-z** [comment]
3 Nov - Need MTK further testing
