### ISSUE TITLE
Add Navigation Pattern to Site

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2536]
Add pattern documentation to [site patterns](https://www.saltdesignsystem.com/salt/patterns/) section

Design work in #2328

**Comment by Fercas123** [comment]
content in PR, images to be updated
https://saltdesignsystem-git-navigation-pattern-fed-team.vercel.app/salt/patterns/navigation

**Comment by origami-z** [comment]
16 Oct - minor changes in PR.
