### ISSUE TITLE
Create closable pill

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2538]
## Description

The Pill should support a closeable action. This should be achieved by allowing the addition of a close button to the end of the Pill.

Requirements:
- When clicking the close button it should allow for deletion to be recognised.
- The decisions made on the API/structure should allow the label to have a clickable action in the future (with the correct semantics)

Dependency of #2541

## Tasks

```[tasklist]
### Checklist
- [ ] Density (HD, MD, LD, TD)
- [ ] Mode (Light, Dark)
- [ ] Fill (Primary, Secondary, Tertiary)
- [ ] State (Default, Hover, Selected/Active, Disabled, Read-only, Other)
- [ ] Controlled API
- [ ] UITK accessibility parity (screen reader + keyboard interactions)
```
```[tasklist]
### Deliverables
- [ ] Characteristics spec
- [ ] Interactions spec, where necessary
- [ ] In Code & Figma (Component + Guide)
- [ ] Supporting site documentation
```

**Comment by origami-z** [comment]
23 Oct - wip, api review?

**Comment by yunjungyeh** [comment]
26 Oct - Storybook example discussion with @Fercas123
 1. When using keyboard to navigate, the parts that are focused with focus ring should be hover state
 2. The example can be displayed as Pill group and some can show icons

**Comment by origami-z** [comment]
Push target date by 1d, to align with OOO holidays

**Comment by joshwooding** [comment]
PR ready to merge, follow up PR for documentation
