### ISSUE TITLE
Release Navigation Item spacing updates - code & Figma

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2546]
@JoanaMMoreira has already merged the spacing updates for the Navigation Item component into a PR. This now needs to be released. 

@bhoppers2008 will release the same changes to the component in Figma.

**Comment by origami-z** [comment]
Code released in [@salt-ds/lab@1.0.0-alpha.18](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.18)

**Comment by shey-v** [comment]
Spoke to @origami-z - issue with deployment. storybook needs to update code to reflect changes on Jo's PR: https://52566ce1.saltdesignsystem-storybook.pages.dev/?path=/story/lab-navigation-item--vertical-nested-group

**Comment by origami-z** [comment]
@shey-v can you check again on storybook? Updated

**Comment by JoanaMMoreira** [comment]
> @shey-v can you check again on storybook? Updated

This seems to have updated :)

**Comment by shey-v** [comment]
> @shey-v can you check again on storybook? Updated

has updated for me too :)

**Comment by origami-z** [comment]
Closing the ticket. Ben has his own Figma tracking.
