### ISSUE TITLE
Carousel not rendering children width correctly

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2558]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

1.0.0-alpha.18

### Description

Carousel is not having correct width in respect to children's width [**timebox 1d**]

### Steps to reproduce

https://stackblitz.com/edit/salt-template-pk7j3b?file=App.tsx,package.json,style.css

### Expected behavior

Carousel should take CarouselSlide's width as default width

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
This is a bug in DeckLayout but surfaced in Carousel

**Comment by mark-tate** [comment]
Need to find out if MCP need this and if not we can lower the priority.

**Comment by mark-tate** [comment]
Will pick this up when we revisit deck layout

**Comment by mark-tate** [comment]
Will pick this up when we revisit deck layout
