### ISSUE TITLE
Tabs: Supporting site documentation

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2587]

**Comment by origami-z** [comment]
16 Oct - Check Word doc align with latest design.

**Comment by origami-z** [comment]
Push out a week to get component examples migrated

**Comment by origami-z** [comment]
MDX branch: https://github.com/jpmorganchase/salt-ds/tree/tabs-supporting-site-documentation

**Comment by origami-z** [comment]
3 Nov - MDX transferred, needs example migrated, check props

**Comment by shey-v** [comment]
6 Nov - in progress.
