### ISSUE TITLE
Document theme roadmap and recommended practices

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2612]
Document what is next for theme, primarily when and how to adopt upcoming 2.0 

Draft plan: release new color foundations in a `next` branch to be tested

**Comment by joshwooding** [comment]
Moved to planned, since it's not being worked on currently.

**Comment by origami-z** [comment]
Dropping from release plan, while the focus is on component delivery

**Comment by bhoppers2008** [comment]
A draft of the Salt Theming roadmap can be found [here](https://confluence.prod.aws.jpmchase.net/confluence/pages/viewpage.action?spaceKey=SALTDS&title=Salt+Theming+Release).
