### ISSUE TITLE
ListNext gets controlled warning when hovering on Dropdown

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2638]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

most recent

### Description

<img width="628" alt="Screenshot 2023-10-23 at 5 36 01 PM" src="https://github.com/jpmorganchase/salt-ds/assets/91206958/8cf4692e-3059-45e0-b8bf-74d2f2b88673">

The above happens when hovering over a Dropdown component with minimal code:

```
<Dropdown
        onSelect={(event, data) => setChannelFilter.(data.value)}
        selected={channelFilter}
        source={Channels}
/>
```

### Steps to reproduce

Code shown

### Expected behavior

Controlled behaviour should be fine as expected 

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
This is due to highlighted is reset to `undefined` when controlled. Controlled props needs to use `null` instead. Need #2607 first.

**Comment by joshwooding** [comment]
With Dropdown being moved to core I'm going to close this as our recommendation would be to use that. If it still happens we can re-open.
