### ISSUE TITLE
Stepped Tracker icon does not show correct color on site example 

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2650]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

-

### Description

Color of stepped tracker icon is wrong

### Steps to reproduce

https://www.saltdesignsystem.com/salt/components/stepped-tracker/examples

### Expected behavior

Show correct colors (e.g. blue)

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

### Browser

- [X] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Depends on a Mosaic fix #2623

**Comment by joshwooding** [comment]
Closed due to #2623
