### ISSUE TITLE
PillNext has inconsistent text styles that lead to misalignment of icons and clipping of descenders 

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2667]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

Latest

### Description

PillNext has inconsistent text styles that lead to misaligned icons and clipping of descenders.

![image](https://github.com/jpmorganchase/salt-ds/assets/12938082/51130a3c-1a82-45b5-9431-005f6bc6bd8d)

![image](https://github.com/jpmorganchase/salt-ds/assets/12938082/161acc48-7a56-4029-b8b3-755620f34e95)

### Steps to reproduce

Visit https://storybook.saltdesignsystem.com/?path=/story/lab-pill-next-qa--examples-grid

### Expected behavior

It not to be misaligned

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
As @Fercas123 is already working on PillNext she has volunteered to fix this :)

**Comment by lilyvc** [comment]
I think this looks fixed now
