### ISSUE TITLE
UITK to Salt migration guide v3

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2682]
Continue development of the UITK to Salt internal migration guide on StackOverflow

- [x] Avatar
- [x] Banner
- [x] Card
- [x] Checkbox
- [x] Radio Button
- [ ] Flag / Country Symbol

Update UITK Salt FAQ (what is Pattern)

**Comment by origami-z** [comment]
Added Flag to the list

**Comment by origami-z** [comment]
Move schedule due to delays from other tickets

**Comment by mark-tate** [comment]
internal migration guides complete, created new issue #4218 for flag
