### ISSUE TITLE
Nested StackLayouts with separators share tokens

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#2698]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

most recent

### Description

When you nest a Stack Layout (of row direction - potentially will happen with both directions) within another, and set the inner gap to be different, the position of the first separator picks up the `--stackLayout-gap-multiplier` token from the nested Layout

At the same time, can clean up some tokens/code throughout of seEerator spelling, which differ from the spelling of 'sepArators' prop

### Steps to reproduce

```
<StackLayout separators>
    <StackLayout gap={7} separators direction={'row'}>
        <div>hello</div>
        <div>hello</div>
    </StackLayout>
    <div>something else</div>
</StackLayout>
```

notice the outer stack picks up the gap of 7 coming from nested layout

### Expected behavior

tokens should respect their own gap

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
@libertymayc is this still an issue ?
