### ISSUE TITLE
Make Navigation Item compatible with Routing Libraries

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2706]
### Area

UI Components

### The problem

NavItem appears to be the recommended component to use for building app navigation. This app navigation is normally going to be done via links/urls.

NavItem tries to help with this by using an anchor element. However this makes it difficult to work with common routing libraries e.g. react-router.

react-router uses a [`Link` or `NavLink`](https://reactrouter.com/en/main/components/nav-link) component to create a link which integrates with the rest of the react-router library. This Link/NavLink adds it's own anchor element around the wrapped component.

The issue is that you can't have nested anchor elements so it doesn't work well to wrap a NavItem in a react-router NavLink.

### The solution

To work with routing libraries it would be ideal to leave the routing aspect up to the routing library and just have NavItem provide the UI (with some recommendations of how to use it with/without a routing library), without providing the anchor element itself.

We should also consider any other components which might feasibly want to be used with Routing Libraries, and  add documentation/examples of the best way to achieve this e.g. ToggleButtonGroup/Button etc

### Alternatives and examples

Alternatively we could provide a way to customise the behaviour of NavItem and potentially other components via props for situations where they will be used with a routing library.

Material UI has a strategy where you can add link behaviour to other components using the 'component' prop: https://mui.com/material-ui/guides/routing/#navigation-components

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
I think this task is mainly documentation and education. Toggle Button is semantically wrong to use for navigation so I wouldn't recommend it. 

Third-party navigation libraries generally provide support for custom "links", e.g. react router offer a [hook](https://reactrouter.com/en/6.18.0/hooks/use-link-click-handler), next has props for Link https://nextjs.org/docs/pages/api-reference/components/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag

**Comment by joshwooding** [comment]
Closed by #3709
