### ISSUE TITLE
Dropdown onSelect doesn't trigger using keyboard events

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2721]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

1.0.0-alpha20

### Description

DropdownNext `onSelect` callback doesn't trigger when using keyboard interactions. This means that the component isn't accessible when using as a controlled component.

### Steps to reproduce

create a controlled DropdonNext component using onSelect to update the selected state, use keyboard navigation to try and select a new value. The selected value doesn't change, and onSelect is never called.

```jsx
import { useState } from "react";

import { SaltProvider, StackLayout } from "@salt-ds/core";
import { DropdownNext } from "@salt-ds/lab";

import "@salt-ds/theme/index.css";

export default App = () => {
  const [selected, setSelected] = useState("one");

  return (
    <SaltProvider>
      <StackLayout align="center">
        <p>When using keyboard onSelect doesn't seem to trigger</p>
        <DropdownNext
          source={["one", "two", "three"]}
          onSelect={(e, data) => {
            console.log(data.value);
            setSelected(data.value);
          }}
          selected={selected}
        />
      </StackLayout>
    </SaltProvider>
  );
};

```

See [codesandbox reproduction](https://codesandbox.io/s/jovial-star-c8yqqs?file=/src/App.js:0-667)

### Expected behavior

The selected value should change and onSelect should trigger when using keyboard interactions

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
@el-dav This should be fixed in the new DropdownNext
