### ISSUE TITLE
Calendar component: sending preselected date object to default calendar. 

### ISSUE THREAD

**Issue by solcratius** [jpmorganchase/salt-ds#2725]
### Area

UI Components

### The problem

Per development team's request I'm trying to create single calendar date picker with predefined date list that selects single dates when clicked on the list items. It seems that labs calendar component does not accept predefined date into the calendar for single calendar and the behavior that we are looking for is not executable.

### The solution

create preselected date input for not just the range calendar but the default/single calendar so we can create this user flow.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Are you controlling `selectedDate`? Please don't paste any JPMC internal link, if you can, provide a reproducible code on StackBlitz.

**Comment by solcratius** [comment]
Yes I would need to control selectedDate in order to pass date object from the list to the calendar.

**Comment by origami-z** [comment]
Assigning myself, connect offline

**Comment by origami-z** [comment]
Resolved, some sample code used: https://stackblitz.com/edit/salt-template-tb3kev?file=App.tsx
