### ISSUE TITLE
Pagination: Button stays active when becoming disabled

### ISSUE THREAD

**Issue by alycrys** [jpmorganchase/salt-ds#2765]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.11.1

### Description

Button stays active after becoming disabled.

Most likely due to condition on line 49 in useButton.ts

### Steps to reproduce

When on Pagination Default example in storybook:
On page load the left arrow button is disabled, as the active page is 1. 
Using the keyboard tab through to page 2 and press Enter. Observe the left arrow button gets enabled.
Tab back to it and press Enter. Observe it gets disabled again. Then tab again to get to page 2, the press Enter. 
Left arrow button is now in an active state.

### Expected behavior

Left arrow button should not be in an active state.

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Stale issue which upon re-testing appears resolved, please re-open if you can re-produce
