### ISSUE TITLE
Tableau getting started doc

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2776]
Design and push a pattern from #1572

**Comment by origami-z** [comment]
27 Nov - first draft to content review (proof reader sent)

**Comment by origami-z** [comment]
4 Dec - image added. TODO: add link (Tableau server) to file.

**Comment by origami-z** [comment]
6 Dec - blocked | discussion call tomorrow (link to Tableau server).

**Comment by origami-z** [comment]
11 Dec - need to verify access request.

**Comment by joshwooding** [comment]
18 Dec - Confluence page has been created. Just need the site to be updated and will be merged today,
