### ISSUE TITLE
Figma wireframe library (used in pattern)

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2777]
Final goal and deliverables to be filled by @ivan-calderon @yunjungyeh

**Comment by origami-z** [comment]
27 Nov - working in progress

**Comment by origami-z** [comment]
4 Dec - Need last wireframe component, before Thursday's review

**Comment by origami-z** [comment]
6 Dec - in good shape, minor update, review tomorrow.

**Comment by origami-z** [comment]
11 Dec - reviewing library tomorrow, pending feedback.

**Comment by joshwooding** [comment]
18 Dec - Discussion around accessibility concerns. But done.
