### ISSUE TITLE
Preference Dialog Pattern examples and publish design doc

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#2784]
- [ ] Publish pattern doc to site from #2368
- [ ] Add examples to storybook
- [ ] Migration QA to StackOverflow

**Comment by origami-z** [comment]
modify start date, delayed by other tasks

**Comment by origami-z** [comment]
Blocked by vertical nav v.s. tab. Looking at parent child layout first.

**Comment by mark-tate** [comment]
We have pattern guidance, we have the components we need for folks to build the patterns.
Closing
