### ISSUE TITLE
Allow passing null as the value to controlled components

### ISSUE THREAD

**Issue by el-dav** [jpmorganchase/salt-ds#2808]
### Package name(s)

Core (@salt-ds/core), Lab (@salt-ds/lab)

### Package version(s)

1.13.0

### Description

When using certain input components as controlled components you sometimes want to set the value to `null`. For example with RadioButtonGroup if you wanted to start out with no option selected.

This is currently difficult as if `null` / `undefined` is passed as the value to these components then it assumes it is uncontrolled and with log errors in the console. Typescript can also complain.

In some circumstances passing an empty string is an option, but this isn't always intuitive, and allowing `null` for a controlled component would make sense.

### Steps to reproduce

Open the following sandbox: https://codesandbox.io/s/clever-artem-xd5klx?file=/src/App.js

Open the console and toggle the radio buttons, you will see errors in the console because the component assumes it it uncontrolled.

### Expected behavior

There should be no errors in the console as null should be an acceptable value for controlled components (where a null value makes sense)

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Closed by #3204
