### ISSUE TITLE
Combo box next list does not automatically resize when a custom floating component is provided

### ISSUE THREAD

**Issue by ImmanuelBaskaran** [jpmorganchase/salt-ds#2842]
### Package name(s)

Core (@salt-ds/core), Lab (@salt-ds/lab)

### Package version(s)

Core: 1.13.1, Lab: 1.0.0-alpha.23

### Description

When a custom floating component that renders content outside of the current window document, is passed to ComboBoxNext, the combo box list does not resize when the items are filtered. This behaviour was found within the custom floating platform example in the storybook.

### Steps to reproduce

Open the following example in chrome or a chromium based browser: https://saltdesignsystem-storybook.pages.dev/?path=/story/core-floating-platform--custom-floating-ui-platform

Type any string into the combo box and while the items are filtered, the list remains at the same height.

![image](https://github.com/jpmorganchase/salt-ds/assets/25984083/d83bd0be-1fa7-4982-b13e-97d6155bc2f6)

### Expected behavior

I expected the combo box list to resize as the list is filtered, behaving as it did without the custom floating component.

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Could you try the new Combo Box Next please
