### ISSUE TITLE
Update color tokens

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#2845]
Implement foundation color changes and changes to the palette layer following ADA compliance checks and design review. 

```[tasklist]
### Dependencies:
- [ ] #2844 
```

**Comment by joshwooding** [comment]
20 Dec - Having a discussion on moving the color palette closer to MB.

**Comment by pseys** [comment]
A unified palette has been agreed. We're implementing it as part of the Figma variables library.
