### ISSUE TITLE
Pill

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2871]
```[tasklist]
### Tasks
- [ ] #2540 
- [ ] #2402
- [ ] #2730
```

**Comment by joshwooding** [comment]
09/01 - @Fercas123 to set up a meeting to discuss feedback

**Comment by Fercas123** [comment]
10/01 - actions from meeting: 
- pill should have just one action, so for any actions that require an icon like close, onClick should handle the action and the icon can be added to the pill as children. 
- spacing 50 to be used between items in pill

**Comment by Fercas123** [comment]
17/01 - PR to move Pill to core in review process, will need a patch for Mosaic before it can be merged
