### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2878]
```[tasklist]
### Tasks
- [ ] #2390 
- [ ] #2393 
- [ ] #2392 
- [ ] #2391 
```

**Comment by mark-tate** [comment]
One sprint delay for the release of Date Picker to Core, we are now targeting for end of Ursula for our Date Picker release (which includes Calendar and DateInput)

**Comment by mark-tate** [comment]
Date picker is now in PR and ready for review
https://github.com/jpmorganchase/salt-ds/pull/3716

**Comment by mark-tate** [comment]
Calendar has been updated and re-published to Labs, we are refining through feedback before we push to Core.
If you require DatePicker/Calendar or DateInput, please feedback through #4096 , so we can make the changes in Labs, before we move a stable set of components to Core
