### ISSUE TITLE
Tabs (Labs)

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2884]
```[tasklist]
### Tasks
- [ ] #2401
- [x] Update specs for add/close tabs (Design)
- [ ] #4021
```

**Comment by ivan-calderon** [comment]
The [Add/remove tabs](https://www.figma.com/design/wh4iwNOuVIpebbV1qgSnxP/Tabs-2?m=auto&node-id=3148-4756&t=J2A0nMMl1BLUls73-1) desing specs and interaction info are ready for review.

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- add/close behaviour to be defined by EOS
- ready for Dev by EOS

**Comment by joshwooding** [comment]
Meeting update:

- Focus behaviour has been defined for close button and add button
- Design has been spec'd
- Starting on Dev

**Comment by origami-z** [comment]
Aug 12 - closing on overflow, mostly working for add / close, on track for EOS

**Comment by mark-tate** [comment]
Espresso goal , merge to Labs in a known state

**Comment by mark-tate** [comment]
Sprint Goal: Extended by 1 sprint to add Keyboard Navigation

**Comment by mark-tate** [comment]
Frappe Goal: a11y review feedback addressed and pushed to Labs

**Comment by mark-tate** [comment]
Galao Goal: Dev complete by EOS, pushed to Labs and wait for feedback from stakeholders

**Comment by origami-z** [comment]
FYI - SO questions/92115 asked possibility to keep tab panel mounted between switches (for UITK), it was asked a few times before as well

**Comment by dplsek** [comment]
Progress is being made by @joshwooding @ivan-calderon ... addressing some accessibility issues with @jake-costa

**Comment by mark-tate** [comment]
Lungo Goal: address a11y feedback and push to Labs, review/publish site docs

**Comment by mark-tate** [comment]
Macc Goal: Docs reviewed by Design by EOS
Dev's A11y questions answered by EOS
Publish labs changes

**Comment by origami-z** [comment]
From Symphony, UITK `fullWidth` equivalent design / example
