### ISSUE TITLE
Design Date Controls

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#2896]
Work on the designs for:

```[tasklist]
### Tasks
- [ ] #2878 
- [ ] #2877 
- [ ] #2881 
```

**Comment by joshwooding** [comment]
09/01 - Will share the progress and updates with @bhoppers2008. Focusing on the Date Input

**Comment by ivan-calderon** [comment]
17/01 - (WIP) Addressing feedback from leads.

**Comment by mark-tate** [comment]
Figma designs complete, dev work started
