### ISSUE TITLE
Issue with recent change in 'icon' attribute of Pill Component

### ISSUE THREAD

**Issue by ikhyati-chopra** [jpmorganchase/salt-ds#2921]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

`"@salt-ds/lab": "^1.0.0-alpha.16",`

### Description

The removal of the "icon" argument from you codebase (https://github.com/jpmorganchase/salt-ds/blob/main/packages/lab/src/pill-next/PillNext.tsx) in "PillNext" component has affected out codebase.
The same has not been reflected in the corresponding usage section on the website : https://saltdesignsystem-git-spinner-2-docs-fed-team.vercel.app/salt/components/pill/usage.
This inconsistency has led to issues on our end in the Live page.

I kindly request that you consider backward compatibility or provide clear documentation for such changes.

### Steps to reproduce

-

### Expected behavior

1. Please ensure 'Backward Compatibility' is supported.
2. Keep 'Usage' section up to date for each component.

### Operating system

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

### Browser

- [X] Chrome
- [X] Safari
- [X] Firefox
- [X] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
You can still use icon as children of Pill, see [Icon example](https://www.saltdesignsystem.com/salt/components/pill/examples#icon). As mentioned in [lab component](https://www.saltdesignsystem.com/salt/components/index#lab-components), API of lab component is not stable.

**Comment by ikhyati-chopra** [comment]
> You can still use icon as children of Pill, see [Icon example](https://www.saltdesignsystem.com/salt/components/pill/examples#icon). As mentioned in [lab component doc](https://www.saltdesignsystem.com/salt/components/index#lab-components), API of lab component is not stable.

Gotcha. Appreciate you quick reply.

- Additionally please keep the Usage section up-to-date.

- Also is there any Distribution List for each component, which broadcasts the changes in the component. We are thinking of a way to keep our codebase up-to-date with the latest release. ?
