### ISSUE TITLE
Toast - option to disable automatic scrollIntoView

### ISSUE THREAD

**Issue by preteshmistry** [jpmorganchase/salt-ds#2941]
### Area

UI Components

### The problem

Currently when multiple toasts are displayed and the a scrollbar is needed, whenver a new Toast is shown, it automatically scrolls into view
https://github.com/jpmorganchase/salt-ds/blob/main/packages/core/src/toast/Toast.tsx#L40

Our users typically handle toasts in the order the events occur, therefore the scrolling to the newest toast would not work for them and it means if we have any action buttons on the toast, the user could end up clicking on the wrong toast if it automatically scrolls just as they click on the button on the taost.

### The solution

Have an optional property on the Toast component to prevent the scrollIntoView being called

### Alternatives and examples

Have an optional property on the Toast component to prevent the scrollIntoView being called

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Thanks for the report, I think we should delete the scrollIntoView code. Toast shouldn't really be in charge of that logic

https://github.com/jpmorganchase/salt-ds/blob/702e274dd36adf878a6630b06a73c34a971817d3/packages/core/src/toast/Toast.tsx#L39-L41
