### ISSUE TITLE
Card reconciliation

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#2944]
**Description**
Currently Card and Interactable Card have distinctly different styling solutions. This creates inconsistency when used together or in proximity of one another.

This issue will merge styling solutions for the two cards into one. Both Card and Interactable Card will have border and shadow treatments, with an optional T,R,B,L accent.

Interactable Card will require additional styles for interactive states (hover, active, disabled states).

**To discuss**
The guidance when to use Interactable Card vs Card. We should review whether we use a polymorphic component (do we need to wrap it with a link? what about if we want it to behave like a button, e.g., not navigation).

Do we merge the two variants into one single component instead? If it's used as a link/ button, the interactive states would be displayed (in code).

**Use cases to consider**
MCP have card use cases in their Dashboard (it should also work in our own Salt Dashboard pattern). Speak to Paula from MCP.

The updates will enable Card to be used in Salt's Selectable Card pattern. Consider the requirements of that pattern when making these updates.

-----
**Issue update:** 

2 Feb - In a discussion today between design and dev, we’ve restructured our approach to the Card component, which will need to roll into the next sprint.
 
We’ve decided that we will provide users with 3 x cards:
**Basic Card** - this will give the user the option to apply an accent bar in any placement (top, right, bottom, left), the card will also be hoverable whereby the accent changes state. States include: Default and Hover.
**Clickable Card** - which will use our selectable tokens, similarly to our selectable cards, this card allows the user to make a selection: single-select or multi-select. States include: Default, Hover, Selected, Focused, Disabled and Selected-disabled.
**Link card** - where the whole card navigates a user somewhere. States: Default, Hover, Active, and Focused.
 
We will include the Clickable Card in the ‘selectable card pattern’ and also include an example of a Clickable Card Group.
 
Token updates will be needed: container-primary-borderColor & container-secondary-borderColor to gray40 in light mode and equivalent in dark mode.
 
This sprint we can aim to reconcile the border and the accent in both cards (Basic card and Link card). Next sprint we will aim to deliver the token updates, the basic card, clickable card and link card examples.

The selectable card pattern will add complexity, but it's what teams are asking for (flexibility). If feedback is too complex, then we can review the ‘selectable card’ component requirement at later date.

**Comment by shey-v** [comment]
23 Jan - Kick off held today + Shey to gather use cases from MCP and DP studio and reconcile the card component specs in a Figma branch.

**Comment by lilyvc** [comment]
Raised a draft [PR](https://github.com/jpmorganchase/salt-ds/pull/2954) deleting interactable card - current state of the combined component can be reviewed here: https://8a112d48.saltdesignsystem-storybook.pages.dev/?path=/story/core-card--default-as-link

**Comment by joshwooding** [comment]
Done as it was split into Card, LinkCard and InteractableCard
