### ISSUE TITLE
Update container-border tokens and app header/tabs token usage

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#2979]
## Theme updates

Light theme - update:
palette-neutral-primary-border to gray-50
palette-neutral-secondary-border to gray-50
container-primary-borderColor to gray-50
container-secondary-borderColor to gray-50

Dark theme - update: 
palette-neutral-primary-border to gray-300
palette-neutral-secondary-border to gray-300
container-primary-borderColor remains gray-300
container-secondary-borderColor to gray-300

Update all disabled container border color token values to 40% alphas.

## Component 

Update App Header and examples to use separable primary
Update Tabs to use separable secondary

**Comment by pseys** [comment]
Figma Theme Characteristics file updated.

**Comment by pseys** [comment]
Light and Dark mode Figma libraries updated and published internally.

**Comment by yunjungyeh** [comment]
Release Note:

**Light**
**--palette-neutral-primary-border** updated to gray-50 from gray-60
**--palette-neutral-secondary-border** updated to gray-50 from gray-90
**--container-primary-borderColor** updated to gray-50 from gray-60
**--container-secondary-borderColor** updated to gray-50 from gray-90
**--container-primary-background-disabled** updated to gray-50 40% alphas from gray-60 40% alphas
**--container-primary-borderColor-disabled** updated to gray-50 40% alphas from gray-60 40% alphas
**--container-secondary-background-disabled** updated to gray-50 40% alphas from gray-90 40% alphas
**--container-secondary-borderColor-disabled** updated to gray-50 40% alphas from gray-90 40% alphas

**Dark**
**--palette-neutral-secondary-border** updated to gray-300 from gray-90
**--container-secondary-borderColor** updated to gray-300 from gray-90
**--container-secondary-background-disabled** updated to gray-300 40% alphas from gray-90 40% alphas
**--container-secondary-borderColor-disabled** updated to gray-300 40% alphas from gray-90 40% alphas
