### ISSUE TITLE
DropdownNext Options showing beneath Dialog

### ISSUE THREAD

**Issue by willa65** [jpmorganchase/salt-ds#2983]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

    "@salt-ds/ag-grid-theme": "^1.3.8",
    "@salt-ds/core": "^1.16.1",
    "@salt-ds/data-grid":"^1.0.4-alpha.6",
    "@salt-ds/icons": "^1.9.1",
    "@salt-ds/lab": "^1.0.0-alpha.30",
    "@salt-ds/theme": "^1.11.0",

### Description

DropdownNext used within salt Dialog, Dialog Content. Options for drop down are showing underneath Dialog 

![Uploading image.png…]()

### Steps to reproduce

DropDownNext with options embedded within dialog will list items underneath the dialog 

 

### Expected behavior

Dropdown options to display above dialog 

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Similar to #2495 as regression, needs test to cover this

**Comment by origami-z** [comment]
@joshwooding

**Comment by joshwooding** [comment]
Fixed by #3000 

And will be in the next release.

**Comment by origami-z** [comment]
Released in [@salt-ds/lab@1.0.0-alpha.32](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Flab%401.0.0-alpha.32)
