### ISSUE TITLE
Resolve pattern page inconsistencies

### ISSUE THREAD

**Issue by mikearildbrown** [jpmorganchase/salt-ds#2992]
For the pattern pages
- [x] Draft a pattern page structure in Word/Figma
- [ ] Change the sidebar to separate related components/patterns
- [ ] Capture token recommendations somewhere

Edited pattern pages-ensure all follow new structure

- [ ] App header
- [ ] Button bar
- [ ] Contact details
- [ ] Content status
- [ ] Forms
- [ ] International address input #2975 
- [ ] International phone number
- [ ] Metric
- [ ] Navigation
- [ ] Preferences dialog
- [ ] Analytical dashboard

**Comment by joshwooding** [comment]
Replaced by #3112
