### ISSUE TITLE
Dropdown placeholder not showing when value is empty

### ISSUE THREAD

**Issue by Fercas123** [jpmorganchase/salt-ds#2999]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

1.0.0-alpha.31

### Description

Behaviour reported: if value is an empty string (in dropdown), we'd expect the placeholder to take priority and render
however, we're seeing that if value is an empty string, the dropdown field is just blank. and in order to get the placeholder to render, value must be undefined. Is this correct?
 
also the docs: https://www.saltdesignsystem.com/salt/components/dropdown/usage, don't specify that 'undefined' is valid for the value prop

### Expected behavior

placeholder should be showing when the value is undefined

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Closed by #3000
