### ISSUE TITLE
ComboBoxNext does not show drop down options when used within a Dialog.

### ISSUE THREAD

**Issue by jay-kay-kay** [jpmorganchase/salt-ds#3029]
### Package name(s)

Core (@salt-ds/core), Icons (@salt-ds/icons), Theme (@salt-ds/theme), Lab (@salt-ds/lab)

### Package version(s)

    "@salt-ds/core": "^1.17.0",
    "@salt-ds/icons": "^1.9.1",
    "@salt-ds/lab": "^1.0.0-alpha.29",
    "@salt-ds/theme": "^1.11.1",

### Description

Options are not displayed when ComboBoxNext is used on a Dialog. When the control is selected, the icon changes to show the control has been selected however the contents are not displayed.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Same to #2983

**Comment by origami-z** [comment]
@joshwooding

**Comment by joshwooding** [comment]
Fixed by #3000
