### ISSUE TITLE
Tab being deleted when pressing backspace during label editing

### ISSUE THREAD

**Issue by stevenmckinnon** [jpmorganchase/salt-ds#3036]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

1.0.0-alpha.31

### Description

When `enableRenameTab` is enabled, and `onCloseTab` is provided, and editing a tab, pressing backspace to edit the label deletes the tab.

In [Tab.tsx](https://github.com/jpmorganchase/salt-ds/blob/4ab245a7c0c852c919a25ff9e8353cfba26fc7fb/packages/lab/src/tabs/Tab.tsx#L111), it should consider `editing` when pressing backspace/delete

### Steps to reproduce

Example component:

```
import { Tab, Tabstrip } from "@salt-ds/lab";

const TabTest = () => {
  const [activePage, updateActivePage] = useState(0);
  const [pages, updatePages] = useState(pageList);

  const removePage = (pageIdx: number) => {
    const newConfig = [...pages];
    newConfig.splice(pageIdx, 1);
    updatePages(newConfig);
  };

  return (
      <Tabstrip
        enableAddTab
        enableRenameTab
        activeTabIndex={activePage}
        onActiveChange={updateActivePage}
        onCloseTab={removePage}
      >
        {pages.map((page, i) => (
          <Tab
            key={page.id}
            label={page.pageName}
            data-testid={`page-link-${i + 1}`}
            closeable={i !== 0}
          />
        ))}
      </Tabstrip>
  );
};
```

### Expected behavior

Tab doesn't close/delete when pressing backspace

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
@stevenmckinnon, If you know the fix already, feel free to file a PR to change.

**Comment by stevenmckinnon** [comment]
I'm not able to push a branch (403 error), does it need to be from an internal JPM github account?

**Comment by origami-z** [comment]
> @origami-z I'm not able to push a branch (403 error), does it need to be from an internal JPM github account?

Contribution will come through a fork from your account.
