### ISSUE TITLE
Importing salt-ag-theme bloated JS bundle

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3043]
### Discussed in https://github.com/jpmorganchase/salt-ds/discussions/3042

<div type='discussions-op-text'>

<sup>Originally posted by **priyassg** February 23, 2024</sup>
Hello, 
When I do import '@salt-ds/ag-grid-theme/salt-ag-theme.css' my JS bundle size increase by >4MB.
Is there a way to import a minified version. One solution I found is to use the minified version provided by jsdelivr (https://cdn.jsdelivr.net/npm/@salt-ds/ag-grid-theme@1.3.8/salt-ag-theme.min.css) Wondering if there is any other way I don't know about? </div>

**Comment by joshwooding** [comment]
Fixed with v2
