### ISSUE TITLE
Clicking outside a controlled overlay does not work

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3077]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

latest

### Description

Clicking outside of an overlay does not call `onOpenChange` or `onClose` which stops it working in a controlled setup.

### Steps to reproduce

https://codesandbox.io/p/sandbox/controlled-overlay-bug-zkff56

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Overlay needs to be updated to be consistent with our other components. It has two callbacks `onOpenChange` and `onClose` and its signature for `onClose` is different other components e.g. Dialog, ComboBox, Dropdown

**Comment by lukeac123** [comment]
Can we expose CloseButton as its own component ( same as Dialog and Drawer ) - would also allow users to optionally remove the CloseButton if required. 
@joshwooding @origami-z thoughts ?
