### ISSUE TITLE
Add cloud icons and an expand icon

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3115]
Three icons identified that are needed for Fusion.
 
- Cloud icons that indicate that information is being saved to cloud storage and able to be saved.
- The third expand icon is for a container be able to minimised and maximised (Salt has expand Image but no minimise?)

Contributed by Shannon

**Comment by pseys** [comment]
New icons created in Figma and ready for publishing:

- Collapse (default only)
- Cloud-success (default, solid)
- Cloud-disabled (default, solid)
- Cloud-upload (default, solid)
- Cloud-download (default, solid)
- Microphone (default, solid)
- Microphone-disabled (default, solid)
- Semantic-satisfied (default, solid)
- Semantic-neutral (default, solid)
- Semantic-dissatisfied (default, solid)

**Comment by origami-z** [comment]
Done in #3227 #3349
