### ISSUE TITLE
size-indicator token update

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3122]
size-indicator token values to update to: 2, 3, 4, 5px in the theme file as a result of the slider exploration work within this figma file: https://www.figma.com/file/QEZzr2FBemADRFB1pSnQac/Progress-2?type=design&node-id=2546-614&mode=design

This would also require making code + design updates to the following components: tabs, nav item and calendar.

**Comment by pseys** [comment]
Correction made in Theme Characteristics Figma file and new variables library, so will be applied to all relevant components automatically.
