### ISSUE TITLE
Toggle multi select dropdown group

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3154]
### Area

UI Components

### The problem

When using `OptionGroup` with multi-select dropdown, it would be nice to also have a checkbox next to the group label, so the user don't need to select all the sub-options one by one

### The solution

/

### Alternatives and examples

/

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Adding this to #4077
