### ISSUE TITLE
Button Bar

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#317]
## Preparation

-   [ ] Existing defect backlog reviewed/evaluated, prioritized, and selected
-   [ ] Functional requirements defined: functional test script is defined/written (not coded) and signed off by Dev, Design, ADA and Product leads
-   [ ] Non-functional requirements defined (e.g. controlled vs. uncontrolled)
-   [ ] Existing enhancements backlog reviewed/evaluated, prioritized, and selected
-   [ ] Usability testing plan defined or deemed unnecessary
-   [ ] Examples needed to properly demonstrate component features are defined and signed off by Dev, Design, ADA and Product leads

## Development

-   [ ] Component implemented in/ported to TypeScript
-   [ ] 3rd-party dependencies removed
-   [ ] JSS converted to CSS
-   [ ] CSS upgraded to use characteristics
-   [ ] Selected defects resolved
-   [ ] Component API finalized
-   [ ] Necessary refactoring completed
-   [ ] Selected enhancements added

## Testing

-   [ ] Functional test script is implemented in Cypress and passes
-   [ ] Code not covered by the functional test script is identified and reviewed by Dev & Design leads
-   [ ] QA (v1-2 visual regression) test passes
-   [ ] Automated Axe tests added and pass

## Examples

-   [ ] All examples present in TK1 are implemented as stories in Odyssey (ported from BitBucket)
-   [ ] All examples needed are implemented as stories (either ported from BitBucket or created net new)

## Deployment

-   [ ] Codemods for migration created and verified
-   [ ] Reviews/Signoff
-   [ ] Dev production review
-   [ ] Design review
-   [ ] Product signoff
-   [ ] ADA review
-   [ ] Documentation
-   [ ] Dev docs content provided
-   [ ] TK1→Odyssey migration guide provided
-   [ ] Design docs provided
-   [ ] Consolidated documentation produced by combining dev content, migration guide, and design docs
-   [ ] Consolidated documentation published on Storybook
-   [ ] Consolidated documentation reviewed and updated according to user feedback
-   [ ] Figma symbols
-   [ ] New Odyssey Figma symbol created
-   [ ] Figma symbol references updated to use new Figma symbol

**Comment by origami-z** [comment]
Blocked by Button

**Comment by origami-z** [comment]
Replaced by #2380
