### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#3233]
### Area

UI Components

### The problem

Create a Tag component.

Tag is a visual adornment for Cards that is somewhat like a Pill (visually) and enables you to highlight keywords, or related metadata/tags

### The solution

Publish to Core components. 

### Alternatives and examples

n/a

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

```[tasklist]
### Dependency
- [ ] #2523
```

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- component is in Core
- docs yet to be published to core
- tag in a card example to be created 

Outstanding Question
- overriden styles required

**Comment by Fercas123** [comment]
Closed by: 
https://github.com/jpmorganchase/salt-ds/pull/3515
https://github.com/jpmorganchase/salt-ds/pull/3605
https://github.com/jpmorganchase/salt-ds/pull/3608
https://github.com/jpmorganchase/salt-ds/pull/3624
