### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by alycrys** [jpmorganchase/salt-ds#324]
https://github.com/jpmorganchase/salt-ds/issues/324#tasklist-block-0bef242f-b09e-484a-b5af-4b85fd92fd53

Figma Link: https://figma.com/file/0qHqLDEobXhRGb1PzQ0I5q

**Comment by parsakhan21** [comment]
1/18 - 
Nav working on design specs; send link by eod today for review - design and ada

**Comment by joshwooding** [comment]
Re-opening until we merge the release to main
