### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#325]
```[tasklist]
### Tasks
- [x] Documentation
- [x] Content review
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1109
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1494
```

Figma: https://www.figma.com/file/k6SG16rdiJSZYm04G1PdME/Panel?node-id=1%3A2804&t=soxujDL9cQwrdaU7-0

**Comment by origami-z** [comment]
This is the first component we are about to release which contains `emphasis` concept, is the way of using static class `.uitkEmphasisHigh` considered finalized (given theme is not)? Does that impact `CSS Class` table?


On the "Custom Property API" section, is `3` being ok as the default of `--uitkPanel-padding`

**Comment by libertymayc** [comment]
https://github.com/jpmorganchase/salt-ds/issues/1109 created

**Comment by libertymayc** [comment]
31/3 design spec still in progress
