### ISSUE TITLE
ComboBox ResizeObserver issue

### ISSUE THREAD

**Issue by efriandika** [jpmorganchase/salt-ds#3262]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.24.0

### Description

There is an error occurred in multiselect combobox, after typing something then remove it using backspace
ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3003/static/js/bundle.js:7756:58)
    at http://localhost:3003/static/js/bundle.js:7775:7

### Steps to reproduce

1. Create more than one combobox with the same options
2. In any combobox (after the first one), type something, then remove it using backspace. There will be an error message:

ERROR
ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3003/static/js/bundle.js:7756:58)
    at http://localhost:3003/static/js/bundle.js:7775:7

### Operating system

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [x] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Could you provide a minimum reproducible example?

**Comment by joshwooding** [comment]
Closing this for now, if we have a reproduction we can reopen
