### ISSUE TITLE
Fix Tooltip height

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3266]
### Package name(s)

Core (@salt-ds/core)

### Description

Tooltips do not match the spec and are too tall.

Tooltip spec: https://www.figma.com/design/0qHqLDEobXhRGb1PzQ0I5q/Tooltip?t=Yhu4PzPwLh4YliZe-0

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- fix Core

**Comment by origami-z** [comment]
Tooltip is shown as base height in all densities, what's really wrong?

**Comment by origami-z** [comment]
PR ready to be reviewed
