### ISSUE TITLE
Density dependent tokens broken by nesting

### ISSUE THREAD

**Issue by libertymayc** [jpmorganchase/salt-ds#330]
The ordering of density scoped variables is broken if the component name is also used and there are nested densities, i.e. in situations like:

.uitk-density-high .MyComponent {
      --myComponent-var: ;
}
.uitk-density-medium .MyComponent {
      --myComponent-var: ;
}

This can be seen when looking at 'Compare with Original Toolkit' stories if the above format is in code. Mostly, when the canvas is in medium density, everything appears OK, but switching to e.g. touch density will impact from which density the styling is from due to nesting and CSS ordering conflicts. 

The current best fix (as seen in #323) is to scope these density variables only to e.g. .uitk-density-medium, rather than .uitk-density-medium .MyComponent. The downside to this is that it explodes the amount of variables exposed within the density scopes, which also makes these variables seem like theme tokens rather than component tokens.

**Comment by joshwooding** [comment]
Closing since I believe this is now fixed. Will re-open if not
