### ISSUE TITLE
Inlaid Drawer component design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3306]
Provide designs for Inlaid Drawer using existing layout (parent-child, border layouts) and UI components, and Salt --spacing tokens for margins.

Document as examples.

Designs provide the basis for Pepper inlaid drawer patterns.

**Comment by origami-z** [comment]
Waiting for a11y direction

**Comment by mark-tate** [comment]
Zazu Goal: M(5)
- waiting for a11y feedback from Jared

Outstanding Decision
- Should Inlaid drawer be a component ? (create issue for decision, pattern or component)

**Comment by navkaur76** [comment]
**Kick off notes:** 

Two separate concerns:
 
Implement Inlaid Drawer somewhere in code as component.

Nav to do docs + specs + figma for component – Design work to be done by EOS (Zazu).
                                                               i.      To confirm what will be in component vs example (Josh)
                                                             ii.      Asmita to identify definitive ‘drawer’ requirements that Pepper need from Salt.  
Build > Pepper dev to build (Thushara/Vineet) in Americano.
                                                               i.      T/V to confirm with Adrian whether unopinionated Inlaid Drawer is sufficient from Pepper, specifically:

- Do Pepper actually need inlaid behaviour?
- Pepper happy to build header/footer/main regions into Salt Drawer as Pepper component/pattern?

Asmita to follow up with Anh/Adrian/JJ Pepper implementation of Drawer (Salt to update as necessary).

Modal behaviour on Overlay Drawer (ability to interact with app underneath) is a separate issues.
Ben/Josh to align on follow-up with Jared.

**Comment by navkaur76** [comment]
- Nav working on site docs, likely some overlap into Americano for reviews + final decisions on how we want to handle sizing (i.e. follow drawer, or provide S/M/L set sizes). 
- Characteristics complete, enough available for Pepper devs to make a start on build

**Comment by mark-tate** [comment]
Goal: ready for Dev by EOS

**Comment by navkaur76** [comment]
Figma assets merged (Salt 1 Light/Dark, Salt Next + figma guide)

**Comment by navkaur76** [comment]
Carryover to address ADA spec w/ Jake

**Comment by navkaur76** [comment]
Outstanding ADA questions addressed with Jake in figma spec. Closing ticket.
