### ISSUE TITLE
Dropdown Select All design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3307]
Collaborate with Pepper team to define and spec a single Select All behaviour for the Dropdown component.

**Comment by shey-v** [comment]
Design spec for dropdown select all Figma link: https://www.figma.com/design/EX0dWn0r2rEOoA2JkWXDOM/branch/8RvQTesX1OuMh2o7F4FoDZ/Dropdown?m=auto&node-id=6083-25154&t=DLKGjaykuesOK8RU-1
