### ISSUE TITLE
System Status design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3318]
Salt and Pepper to collaborate on single solution for system banner using Salt Banner component.

**Comment by pseys** [comment]
### Tokens/Variables

Agreement to add the following tokens and variables to support `System Status` styling:
- `status-error-bold-background`
- `status-info-bold-background`
- `status-warning-bold-background`
- `status-success-bold-background`

A foreground token/variable is also needed. The new token is also needed for #3325 . The new foreground token is:
- `content-bold-foreground`

**Comment by pseys** [comment]
### Figma library progress

- The new tokens have been added to **Salt (Next) Styles library** as variables, the updates have been published ready for use
- The new tokens have been added to **Salt Light mode library** as styles, the updates have been published ready for use
- The new tokens have been added to **Salt Dark mode library** as styles, the updates have been published ready for use
- The **Theme Characteristics** file has been updated to document the changes to Salt Light/Dark mode libraries.

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- Figma component to be updated in Salt 1/2
- add ticket to backlog to develop

**Comment by shey-v** [comment]
- Shey and Thurshara discussed the approach to build the system status component.
- Thushara will build the component and prepare site documentation according to Shey's Figma specs.
- Shey will prepare the Figma component in the current and next libraries.
- The component has a dependency on the status button, so some site examples will be incomplete until the status button can be added.

Note: Update the site examples when the status button is ready.

**Comment by shey-v** [comment]
- QA in progress; there is an issue with the PR build, Thurshara has asked Josh to fix it so that Shey can design QA the site docs
- Thushara is adding one more example to storybook and the site around 'full width' which Josh and Shey requested yesterday
- Shey to create a seperate ticket to add the status button in to the component (figma and code) when it is available.

**Comment by shey-v** [comment]
- Design QA done, all issues raised have now been addressed. 
- Ticket to add status button into the component when it is ready has been created [here](https://github.com/jpmorganchase/salt-ds/issues/3771).
