### ISSUE TITLE
Figma: Swap design

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3319]
Align on single solution for Swap component in Figma and update library as required.

Story solution: https://www.figma.com/file/WtUyH0EIjgrrA6LSgnwCVI/StoryDS_Salt_Gap_Analysis?type=design&node-id=428%3A64383&mode=design&t=lPLHC8PHof4os0Jg-1

**Comment by mark-tate** [comment]
Completed as part of Figma work
