### ISSUE TITLE
Colored / Status Button

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3326]
Added colored / status option to button, for both current and theme next

**Comment by origami-z** [comment]
Updated est. sprint

**Comment by pseys** [comment]
Need to ensure adequate time at the start of the sprint to:
- agree token/variable naming in line with changes to `actionable` characteristic documented in #3325 
- update variables in Salt (Next) Style library
- update styles in Salt Light mode library
- update styles in Salt Dark mode library

**Comment by pseys** [comment]
The intention is to provide 3 colored status buttons:
- red `negative` using the `negative` characteristic
- green `positive` using the `positive` characteristic
- orange `warning` using the `warning` characteristic

These will follow `accent` and `neutral (default)` and will be available in 3 'appearances':
- `solid`
- `outline`
- `transparent`

**Comment by pseys** [comment]
All required tokens have been mapped, documented and agreed with @origami-z 

Next steps:
- Update variables in Salt (Next) Styles library
- Update Salt Button spec in Figma to document token usage for 3x3 new Button variants.
- Update `button` Figma component in Salt (Next) Component library

**Comment by origami-z** [comment]
Extend to Cappuccino, given #3325 is delayed

**Comment by bhoppers2008** [comment]
Moved to Cortado given sprint priorities.

**Comment by mark-tate** [comment]
Work overlaps with Bordered Buttons, Paul combining effort

**Comment by mark-tate** [comment]
Cortado Goal: Close with other bordered button work

**Comment by origami-z** [comment]
Aug 12 - blocked by #3325

**Comment by mark-tate** [comment]
Will  be released by 13th September

**Comment by pseys** [comment]
- Button spec complete
- Token spec complete, including Next and Legacy token values
- Salt (Next) Styles Library updated and published
- Salt (Next) Component and Pattern Library updated, merged and ready to be published.

**Comment by pseys** [comment]
- Salt Theme Characteristics file updated
- Salt Light Mode styles library updated and published
- Salt Dark Mode styles library updated and published

Still to do:
- Update Salt Light Components library with new styles
- Update Salt Dark Components library with new styles

**Comment by pseys** [comment]
All supporting Figma files and libraries have been updated now and are ready to publish.
