### ISSUE TITLE
Way to limit the max height of a combobox or dropdown list

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3333]
### Area

UI Components

### The problem

There is no easy way to limit the max height of a combobox or dropdown list.

The current way is to target the "saltOptionList" class and apply a max-height directly.

### The solution

.

### Alternatives and examples

.

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Extend dates to Xion, 1 sprint behind

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- PR to be raised , docs only change

**Comment by Fercas123** [comment]
notes from @jpmorganchase/salt-developer  conversation on 01 July 24: 

- there is no current way of passing `popperProps` in any of the components that use portal
- the preferred way wold be to increase composition to avoid adding props that pass down to portal.
- current solution could be to document how to target the list in global so users can override, downside is that it will be a change affecting all lists. 

TBD: More research about different approaches and follow up.

**Comment by Fercas123** [comment]
documentation change addressed as short term solution, needs long term solution.

**Comment by joshwooding** [comment]
I think we should create a new issue for a long-term solution. There is a way and it's documented.

**Comment by efriandika** [comment]
Hi @Fercas123 
Which documentation did you refer to? I don't see any information related in this page: https://www.saltdesignsystem.com/salt/components/combo-box/usage

We also use this combobox in our application. 
Really interested in this solution.

**Comment by origami-z** [comment]
Short term recommendation changed in #3728.

Long term solution to be investigated in #3599
