### ISSUE TITLE
Indeterminate Linear Progress Bar

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3354]
### Area

UI Components

### The problem

We can use spinner to represent indeterminate state of circular progress, but can't find an equivalent for linear progress

### The solution

Someting like
https://mui.com/material-ui/react-progress/#linear-indeterminate

### Alternatives and examples

/

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Code API needs to be updated, around default `variant` and `value=undefined`

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- Zhihao to pickup
- ready for Core by EOS

**Comment by bhoppers2008** [comment]
@navkaur76 to add required updates to (Next) library.

**Comment by origami-z** [comment]
Jul 1 - Found some problems with new indeterminate implementation on buffer. Also changing site examples to remove radio toggle.

**Comment by origami-z** [comment]
Jul 3 - updated site examples, doc wording, rearranged examples. #3429 ready for review

**Comment by navkaur76** [comment]
Figma updates complete + branches merged by Yun.

**Comment by origami-z** [comment]
Released in code in [@salt-ds/core@1.32.0](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fcore%401.32.0)
