### ISSUE TITLE
Disabled combo box stays focused

### ISSUE THREAD

**Issue by zeenatbaig** [jpmorganchase/salt-ds#3369]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

"@salt-ds/core": "^1.15.0",

### Description

For our use case the combobox is disabled after the user selects an option. The issue is that the combo box stays in focus (shown by the dotted blue lines around the combobox). Even when a user clicks on something else the diabled combobox stays focused.

### Steps to reproduce

set disabled set to true on onSelectionChange if a option is selected 

### Expected behavior

Once the combo box disables and the user click on another part of the screen then the combobox should lose focus. 

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by zeenatbaig** [comment]
When are they going to release a fix on this issue

**Comment by origami-z** [comment]
Something extra for consideration, what should be the expected behavior for a keyboard user after selecting an item.

**Comment by origami-z** [comment]
Fixed in [@salt-ds/core@1.30.0](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fcore%401.30.0)
