### ISSUE TITLE
Theme Next: Components rounded corner support

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3373]
```[tasklist]
### Tasks
- [ ] Interactive card: 4 corners rounded (currently accent bar is square) #3514
- [ ] #3523
- [ ] Pagination
```

**Comment by origami-z** [comment]
Move dates to meet 7 Jul unstable provider removal date

**Comment by bhoppers2008** [comment]
@bhoppers2008  @dplsek to prioritise verification work for the theme release.

**Comment by navkaur76** [comment]
9th July - discussed in the attributes kick off meeting for #3536, pending solutions for: 

- accent bar bleeding from rounded corners issue to be addressed in card
- pagination

**Comment by navkaur76** [comment]
To be closed as:

-  #3514 is being addressed as part of an overall card consolidation ticket - [#3875](https://github.com/jpmorganchase/salt-ds/issues/3875)
- Pagination spec to be updated and tracked within [#3874 ](https://github.com/jpmorganchase/salt-ds/issues/3874) instead

Corner verification work for existing components in #3536 is complete.
