### ISSUE TITLE
Date picker to show an example on how to configure different date format within input

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3390]
### Area

UI Components, Documentation

### The problem

To support specific use case on different locale, date picker needs flexibility to configure different date format (after parsing)

Salt default date format will remain to be 'dd MMM yyyy' (according to content guideline), for most international support and avoid confusion.

### The solution

Show an example on documentation

### Alternatives and examples

-

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
cc @Fercas123 @ivan-calderon

**Comment by Fercas123** [comment]
closed by https://github.com/jpmorganchase/salt-ds/pull/3489
