### ISSUE TITLE
Old Dropdown styles on the site affect the Dropdown demos

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3443]
### Package name(s)

Website / Documentation

### Description

This is because the site includes Dropdown's styles in two places:

- ExampleListView on mobile
- Tabs

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by alexlostorto** [comment]
Hi @joshwooding! 🙂

Thanks for raising this issue.

Could you provide screenshots of the issue or provide steps to reproduce the problem on our end?
You also mentioned that the Dropdown's styles reside in two places, could you provide the links/full path to both files?

Kind regards,

Alex

**Comment by origami-z** [comment]
Menu icon / text is not correct
https://www.saltdesignsystem.com/salt/components/menu/examples#with-icon

**Comment by joshwooding** [comment]
Menu > Impacted by Breadcrumbs in Mosaic
Dropdown > Impacted by Tabstrip using Dropdown
