### ISSUE TITLE
Bordered form controls

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3456]
Bordered variants are needed for:

- [x] Input #3537 
- [ ] Dropdown
- [ ] ComboBox

They should align to MultilineInput

Spec for input
https://www.figma.com/design/C4uM2dzDWMcAFqP3PYFAy1/Bordered-Input?node-id=3-73&t=mNPDy8G82XQIkSpM-1

**Comment by ThusharaJ07** [comment]
Added bordered prop to combobox - #3594 (merged)
Added bordered prop to dropdown - #3551  (merged)

**Comment by origami-z** [comment]
Will be released in #3644
