### ISSUE TITLE
Divider component in code

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3483]
Following spec from #3320

- New component
- Test
- Site doc
- Storybook

**Comment by origami-z** [comment]
To be released, lab to core merged in #3543

**Comment by Vineet119** [comment]
added example for divider in AG grid statusBar and Overlay - with Actions

**Comment by origami-z** [comment]
Released in [@salt-ds/core@1.30.0](https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fcore%401.30.0)
