### ISSUE TITLE
Scope and design Logo component

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3525]
Action followed by #3310

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- publish docs to siite

**Comment by bhoppers2008** [comment]
Blocked pending input from brand on JPMC logo assets and alignment issues. Meeting schedule for Tuesday 9th July. Agenda to be provided by @origami-z @mark-tate .

**Comment by mark-tate** [comment]
Meeting with brand to decide direction
