### ISSUE TITLE
System Status Build

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3535]
Following design from #3318

Worked by [ThusharaJ07](https://github.com/ThusharaJ07)

**Comment by mark-tate** [comment]
To be picked up by Pepper during Zazu
Goal: M(5)
Build by EOS but maybe with known issues around button colors.

(Dependencies on Color button)

**Comment by ThusharaJ07** [comment]
To do from Friday's review on the PR:
1. move the component to lab ~ since we are waiting for the status buttons & its examples to be added.
2. change the accessibility docs as suggested by Josh

**Comment by mark-tate** [comment]
Goal: published to RC by EOS

**Comment by ThusharaJ07** [comment]
Moved components to Lab from Core.
Addressed review comments by @origami-z .

Waiting on PR review & approval.

**Comment by ThusharaJ07** [comment]
Merged PR : #3693 

This PR covers adding System Status components with error, success, warning and info variant - and adding examples for them.

below is the Pending work (depended on Status Button component work) - 
-add examples for close button
-add examples for mutiple alert
-add examples for secondary action
