### ISSUE TITLE
Verify component theme next attributes, update spec and enable snapshot

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3536]
Below components which has corner radius added. ~~This is prerequisite for making `SaltProviderNext` stable~~

Theme next 
- (Assumed) new color palette
- Corner
- Accent (teal/blue)
- Heading font
- Action font

Need to verify they are defined in Figma spec, updated in Figma Salt (Next) library. Confirm code parity.

- [ ] Update Figma component spec
- [x] Update Figma (Next) library
- [ ] Update Corner token description (Figma)
- [ ] Update Corner token description ([code](https://storybook.saltdesignsystem.com/?path=/docs/experimental-theme-next--docs))
- [ ] Create an issue to track Curve on Salt [site foundation page](https://www.saltdesignsystem.com/salt/foundations/index)

In code - https://storybook.saltdesignsystem.com/?path=/docs/experimental-theme-next--docs

In Figma - https://www.figma.com/design/qXEHyJjOEiPMHkrnvuV8xk/Salt-2-Border-radius?node-id=1307-9257&t=7cli6F5LR8CuGWnT-1

```[tasklist]
### Existing components
- [x] Checkbox
- [x] Pill
- [x] Switch (thumb)
- [x] Toggle Button
- [x] Button (Skip, leave to last)
- [x] Switch (track)
- [x] Toggle Button Group
- [x] Tooltip
- [x] Banner
- [x] Card
- [x] Dialog
- [x] File drop zone
- [x] Overlay
- [x] Panel
- [x] Toast
- [x] Avatar
- [x] Badge
```

```[tasklist]
### Stretch goal
- [x] Dropdown / Combo Box #3456
- [x] Input (bordered)
- [x] List
- [x] Menu
- [x] Date Picker Calendar #3530
```

**Comment by mark-tate** [comment]
Zazu Goal: L(11)
- Border to be done by Darrin
- Shadow to be done by Ben
- By EOS we want to remove the unstable tag from Salt 2

**Comment by mark-tate** [comment]
SoS Raised  A Question:
@bhoppers2008 this story does not appear to be progressing ? 
What is the new date for Salt 2 to become stable ?

**Comment by mark-tate** [comment]
Goal Complete all verification by EOS

**Comment by navkaur76** [comment]
9th July - attributes kick-off meeting w/ Zhihao + Darrin. Outcome: Nav to prioritise + update figma component specs for corner attributes across existing components, Darrin to take a look at the stretch goal components (prioritise dropdown/combo box and menu for Pepper team).

**Comment by navkaur76** [comment]
17 Jul - components using corner radiuses verified in both design + code. Latest source of reference for design can be found in Border radius file.

**Comment by navkaur76** [comment]
This ticket (3536) to be closed, and instead split into additional tickets to track the remaining theme Next attribute verification work. Refer to tickets #3834, #3835, #3836 and #3837.

**Comment by navkaur76** [comment]
Closing ticket due to comment above.
