### ISSUE TITLE
Support status color for FormFieldHelperText

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3540]
### Area

UI Components

### The problem

With #3308 complete, it's now possible to support status color in text. This means we can style helper text with the FormField status. 

### The solution

.

### Alternatives and examples

.

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by alexmotoc** [comment]
I think I have a solution for this, could I pick up this task?

**Comment by bhoppers2008** [comment]
Ben to finalise review with @dplsek

**Comment by mark-tate** [comment]
@dplsek to make a decision by 23/07/24

**Comment by dplsek** [comment]
Please keep status helper text style the same as standard helper text style (italic). The only difference should be the color of the text itself and the addition of the corresponding status icon. The tokens for styling the status text and icon should be as follows:

Icons = decorative tokens: red/orange/green – 500
Text = informative tokens: red/orange/green – 400(dark) and 600(light)
