### ISSUE TITLE
Tab component does not return to it's original visual state, when the browser resizes

### ISSUE THREAD

**Issue by VAIBHAVHATISKAR21** [jpmorganchase/salt-ds#3542]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

@salt-ds/lab : 1.0.0-alpha.46

### Description

Tab component doesn't adjust back to it's original visual state , when tab is moved from one monitor to another.

### Steps to reproduce

Screen where tab component is implemented, 
1) Try to move it from one screen to another
2) Tab will shrink in new screen

3) Now maximize the browser tab, it is still the same as it was in Step 2. 

### Expected behavior

Ideally it should expand back to it's original state , as the screen size is same in another monitor.

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
I tried to reproduce this on [Storybook](https://storybook.saltdesignsystem.com/iframe?args=&id=lab-tabs-next-tabstrip-next--lots-of-tabs-tabstrip&viewMode=story) but wasn't able to. Could you provide a reproduction, please?

Note: The overflow in tabs isn't great and is currently being worked on, so it should improve in the future.

**Comment by VAIBHAVHATISKAR21** [comment]
It can be reproduced in [SALT website](https://www.saltdesignsystem.com/salt/components/tabs/examples#main-tabstrip) , 
When full screen, drag chrome to another monitor, Tab will get adjusted to MicroMenuIcon , but when Chrome is maximized back , it is still rendering MicroMenuIcon (which it should have rendered back to old state of Tab)

**Comment by origami-z** [comment]
Reproduce: shrink the Salt website window to around 1180px width on the [tabs example](https://www.saltdesignsystem.com/salt/components/tabs/examples#main-tabstrip), maximize the page, tabs are not reflowed.
