### ISSUE TITLE
Disabled accordions should not have status

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3549]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

latest

### Description

Disabled accordions should not have status, this aligns with the behaviour in Input.

### Steps to reproduce

https://codesandbox.io/p/sandbox/disabled-open-accordion-538x9h

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Need to document overall approach around readonly, disable and status. Decision seems to be not clear on the design side.
