### ISSUE TITLE
FileDropZone component not picking same file after reset

### ISSUE THREAD

**Issue by shakeelss2009** [jpmorganchase/salt-ds#3591]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.23.0

### Description

Hi,
The FileDropZone component isn't selecting previously selected file after reset,
https://storybook.saltdesignsystem.com/?path=/story/core-file-drop-zone--default
Steps to reproduce from above storybook sample,
1. Browse for a file and select it. It shows message "Upload completed".
2. Click on Reset button.
3. Browse files and select the same file that was previously selected. Nothing happens.

We are using this component in a similar scenario where after selection, we show the selected file in a table and also have a "delete" option. So, when we delete the file and try to browse and select it again, we are unable to do so. Only workaround is to select a different file and then select the deleted file.

I know this behavior is due to the onChange event and event not being triggered on selecting same file. However, I believe it is also a bug and not the right user experience.

### Steps to reproduce

The FileDropZone component isn't selecting previously selected file after reset,
https://storybook.saltdesignsystem.com/?path=/story/core-file-drop-zone--default
Steps to reproduce from above storybook sample,
1. Browse for a file and select it. It shows message "Upload completed".
2. Click on Reset button.
3. Browse files and select the same file that was previously selected. Nothing happens.

### Expected behavior

Select the file

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Workaround - adding `event.target.value = null;` within trigger's `onChange` should work.

Will look into incorporating this within component.

**Comment by mark-tate** [comment]
Zazu Goal: S(3)
- bug fix to be implemented by EOS

**Comment by origami-z** [comment]
27 Jun - merged, will be in the next release
