### ISSUE TITLE
Combo box validation status focus ring is not using correct color

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3612]
### Package name(s)

Core (@salt-ds/core)

### Description

Focus ring color should match status
https://storybook.saltdesignsystem.com/?path=/story/core-combo-box--validation

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by ThusharaJ07** [comment]
Point 3, 4, 5 needs to be fixed in the Issue.
https://www.figma.com/design/pzgdSYa8O1Vgdlor3XmKzl/Salt-%2F-Story-Parity?node-id=4660-1715&t=P4EF6APrm0X4hdfV-0
