### ISSUE TITLE
Input not reading out content (text) passed in end Adornment

### ISSUE THREAD

**Issue by ThusharaJ07** [jpmorganchase/salt-ds#3615]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

@salt-ds/core": "1.29.0

### Description

Adornments should be read similar to a placeholder when user lands on the text input field. Based on the current configuration for the end adornment of “USD”, the Salt storybook shows a configuration where the salt Text element is passed which results in the attached image.
<Input endAdornment={<Text>USD</Text>} defaultValue={args.defaultValue ?? "Value 1"} {...args} />

https://storybook.saltdesignsystem.com/?path=/story/core-input--with-static-adornments

### Steps to reproduce

Use screenreader to tab onto field in example.

### Expected behavior

Screenreader should announce something like “Edit text, USD"

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Will need information whether expectation is the same between [static adornment](https://www.saltdesignsystem.com/salt/components/input/examples#static-adornments) and [button adornments](https://www.saltdesignsystem.com/salt/components/input/examples#button-adornments)

**Comment by mark-tate** [comment]
Goal: S(3)

Pepper team to provide more information (update this story)

**Comment by ThusharaJ07** [comment]
Updates:
- to fix the static adornments for input so that screen reader can read the label for static adornments along with input value when user lands on the text input.
- the button adornments works fine. no fix needed for this.

**Comment by origami-z** [comment]
Update static adornment examples with a11y recommendation, likely via `aria-describedby`

**Comment by ThusharaJ07** [comment]
All static adornments aren't associated to the input by default. Channels teams will have to do it manually with aria-describedby and an id for the screen reader to call out the statuic adornments.
What Salt has updated:
Salt has updated the docs for static adornment example on site stating "Don't rely on static adornments alone for labelling, screen readers will not read them out." so that channel teams are aware about this.
