### ISSUE TITLE
When Pill resizes the close icon should stick to the end

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3622]
### Package name(s)

Core (@salt-ds/core)

### Description

When Pill resizes the close icon should stick to the end, currently it's not.
Tasks
- [ ] Figma (Salt 1) to provide example/guidance to achieve alternative resize behaviour
- [ ] Code

### Steps to reproduce

1. Go to https://saltdesignsystem-git-list-box-fed-team.vercel.app/salt/components/pill/examples#closable
2. Manually re-size the pill with CSS
3.
![image](https://github.com/jpmorganchase/salt-ds/assets/12938082/6f765c7a-6cce-4ee3-bd2a-34a21b800114)

### Expected behavior

When Pill resizes the close icon should stick to the end

![image](https://github.com/jpmorganchase/salt-ds/assets/12938082/c1054087-c36f-4f89-bde6-9d7b323b3fcd)

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by Fercas123** [comment]
looks like it is a documentation issue, it's missing `justify` in the closable examples.
