### ISSUE TITLE
Docs: Combo box > Empty Message example: is not empty

### ISSUE THREAD

**Issue by j5v** [jpmorganchase/salt-ds#3632]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

(current, 2024-06-24)

### Description

**Edit**: this bug report is based on a misunderstanding of when the 'empty message' appears. In further comments, I've instead asked for a fuller description, to avoid confusion with 'empty list' or 'no selection' design patterns. Obsolete report as follows:

> The example for Combo Box > Empty Message shows a populated set of options. I think you intended to provide an empty list in the example. https://www.saltdesignsystem.com/salt/components/combo-box/examples#empty-message.
> 
> The code loads a list of options from `import { shortColorData } from "./exampleData";` but it should instead use none.

### Steps to reproduce

1. Go to https://www.saltdesignsystem.com/salt/components/combo-box/examples#empty-message

### Expected behavior

The message `No results found for &quot;{value}&quot;` is (formatted and) displayed.

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [X] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
The current behavior that the empty message will be displayed when filtering with no match. With discuss with the team what's the best alternative

**Comment by j5v** [comment]
> The current behavior that the empty message will be displayed when filtering with no match. With discuss with the team what's the best alternative

Thanks @origami-z for the clarification. Perhaps this bit needs a change, to reflect that the message is intended for filtered results:

> # Empty message
> Use the Option component to display a message when there are no options available.

**Comment by mark-tate** [comment]
Goal : XS(1)

Pickup based on availability of developer
