### ISSUE TITLE
Figma add right indicator position to Accordion

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3634]
Right side support for Accordion indicator has been added in code. Completing this issue will add the indicator position to Salt and Salt (Next) Figma libraries.

Branch: https://github.com/jpmorganchase/salt-ds/pull/3552/files#r1651111677
Preview: https://saltdesignsystem-git-accordion-chevron-fed-team.vercel.app/salt/components/accordion/examples#arrow-alignment

This issue will also update the position and animation on the indicator when positioned on the left side. Regardless of side, the indicator will always flip from down (when closed) to up (when open), to align with dropdown, combo box and nav item controls.

**Comment by mark-tate** [comment]
Goal complete by EOS

**Comment by bhoppers2008** [comment]
This work is done. Ready for @yunjungyeh to review and merge.

**Comment by mark-tate** [comment]
Complete by end of of Cappuccino

**Comment by yunjungyeh** [comment]
Mon 5 Aug - Branches in Salt Next, Salt Light/Dark are merged
