### ISSUE TITLE
Menu component appears behind the Drawer

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3636]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.28.0

### Description

When use a Menu component within a Drawer, menu component doesn't show up (likely appear behind the Drawer)

### Steps to reproduce

https://stackblitz.com/edit/salt-template-mfrf5v?file=App.tsx

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Goal: XS(1)
To Fix

**Comment by joshwooding** [comment]
Released in @salt-ds/core@1.31.0
