### ISSUE TITLE
Theme: Icon switching (status indicator)

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3641]
In relation to ticket [#3625](https://github.com/jpmorganchase/salt-ds/issues/3625)

Goal: remove the use of status indicator icon across components in Salt (Next) component library, to instead use icons directly. CC: @pseys 

Complete + test #3625 first before addressing this goal.

**Comment by mark-tate** [comment]
should be done by 23rd of July

**Comment by navkaur76** [comment]
Closing as this is part of the same task as #3625
