### ISSUE TITLE
Figma add Swap component to Banner

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3642]
Resolving this issue will add a Swap Content area beneath the title in the Banner component in the Salt (Next) figma library.
```[tasklist]
### Tasks
- [x] Salt Next (Ben)
```

Update for Salt Light/Dark in [#3935](https://github.com/jpmorganchase/salt-ds/issues/3935)

**Comment by mark-tate** [comment]
Can we raise priority of this in Cortado @bhoppers2008 as this is a pain point for Pepper
Darrin says assign to Ivan

**Comment by bhoppers2008** [comment]
This work is done. Ready for @yunjungyeh to review and merge.

**Comment by mark-tate** [comment]
Cortado Goal:
Figma release (matching Salt next)

**Comment by yunjungyeh** [comment]
Mon 5 Aug - branch merged in Figma Salt Next. Update for Salt Light/Dark in #3935
