### ISSUE TITLE
Figma add multi-select combo box to Salt and Next

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3643]
Resolving this issue will add multi-select combo box to the Salt and (Next) Figma libraries. The component should expand with pill content and provide the relevant tokens for pills used specifically in the field. 

"Add Pill group to Form Field control (be sth like that but called Input with Pill group https://www.figma.com/file/68D63Nnlrx29Mhs19eEF4d/UITK-v33%3A-Light-components?type=design&node-id=22682%3A360473&mode=design&t=rjgalh0H424Ad4BE-1)"

**Comment by mark-tate** [comment]
Goal complete by EOS

**Comment by bhoppers2008** [comment]
Size and target sprint for release updated.

**Comment by origami-z** [comment]
Aug 12 - WIP

**Comment by yunjungyeh** [comment]
14 Aug - Initial review with @bhoppers2008 & @joshwooding

**Comment by yunjungyeh** [comment]
Fri 23 Aug - Branches in Next/Light/Dark/Guide are merged
