### ISSUE TITLE
Deprecate `salt-text-action-letterSpacing` tokens

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3647]
From a design perspective we are no longer using `salt-text-action-letterSpacing` within our component library. It is an outlier that only impacts buttons. The token can be deprecated and its use in code removed. 

`salt-text-textAlign-embedded` and `salt-text-action-textAlign` both centre text. The latter is only used in Button. Opportunity to reduce the number of repetitive tokens in the DS.

**Comment by origami-z** [comment]
What's the replacement?

For Characteristics, we need to think about whether a potential use case for consumer overrides. Having "duplicate" is probably ok, given reducing duplicate is mostly a job of lower tier tokens

**Comment by origami-z** [comment]
`--salt-text-action-letterSpacing` is also used in action Text. Not going to deprecate.
