### ISSUE TITLE
Update Figma Guide - Accordion

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3653]
Update the Salt Figma guide to include the content for Salt Next
Estimated size: S

**Comment by yunjungyeh** [comment]
Wed 17 Jul - Waiting for New Figma UI (contacted Figma via the website and email), planning how to update the guide to include Salt Next

**Comment by mark-tate** [comment]
Latte Goal: complete by EOS

**Comment by dplsek** [comment]
Update pending from @yunjungyeh... moving to Lungo until we know otherwise

**Comment by yunjungyeh** [comment]
Mon 28 Oct - Completed and reviewed with @joshwooding
