### ISSUE TITLE
Update Figma Guide - Avatar

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3654]
Update the Salt Figma guide to include the content for Salt Next
Estimated size: XXS

**Comment by yunjungyeh** [comment]
Wed 17 Jul - Waiting for New Figma UI (contacted Figma via the website and email), planning how to update the guide to include Salt Next

**Comment by mark-tate** [comment]
Latte Goal: complete by EOS

**Comment by yunjungyeh** [comment]
Thu 24 Oct - reviewed with @bhoppers2008 @joshwooding and updated
