### ISSUE TITLE
ComboBox render bug

### ISSUE THREAD

**Issue by rnjpmc** [jpmorganchase/salt-ds#3669]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.22.0

### Description

I have code using the combo box, inside the combo box I have a map that cycles through a small array of data and uses them in an <option/>. This runs locally and im able to cycle through those different options inside the combo box. However the error occurs when I run a simple render test. I am getting a "TypeError: win.ResizeObserver is not a constructor" error only when running the test.

### Steps to reproduce

create a combo box with about 10 items inside. try and create a test that only checks if the component renders. 

### Expected behavior

after running the tests, the tests all pass

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Please see: https://github.com/jpmorganchase/salt-ds/issues/1673#issuecomment-1549683094
