### ISSUE TITLE
Ag grid floating filter column chooser list item doesn't have hover effect

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3671]
### Area

UI Components

### The problem

Use below site example, click floating filter of "Capital" column, observe no list item hover effect on the column chooser.
https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples#floating-filter

In v1.3.7 of the theme, there were hover effect on the list items.

### The solution

Add hover style to `ag-virtual-list-item`
- background color
- cursor: pointer?
- Adjust spacing between checkbox and text (very tight in HD)
- [Optional] Expand the clickable area of the set filter item (e.g. use padding instead of margin)

### Alternatives and examples

-

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Going out in next release
