### ISSUE TITLE
Theme documentation to support Salt (Next) release note

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3676]
From @bhoppers2008 

* We should aim to get an 'official' release note out on Salt Next docs at end of this week. 
* Making Salt (Next) available is opening the flood gates for theming. We need to document:
   * What is Salt theming? What is it not? What is it intended for?
   * What is a theme? How does it impact my product? What are the risks? (None/limited–same components different/new theme).
   * What is the Salt (Next) library? Who should use it? (Currently limited to new brand endorsed palettes–legacy palette a WIP).
   * How to use the Salt (Next) library? How do i set up my themes for my project?

**Comment by pseys** [comment]
Briefing arranged for 1530 (BST) today.

**Comment by bhoppers2008** [comment]
Docs shared for review with leads @origami-z @dplsek @joshwooding @mark-tate
