### ISSUE TITLE
Date picker to control input values from external state

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3712]
### Area

UI Components

### The problem

Have been trying to integrate `@salt-ds/lab` `DatePicker` component with React-Hook-Form.

Below is the implementation for controlled DatePicker with React-Hook-Form.

Point to consider :

- We wanted to make sure that user is notified about the incorrect format or garbage string, hence we are persisting invalid value in form state.
- Backend API's are expected to save date fields as string.

https://stackblitz.com/edit/salt-template-emlnbf?file=App.tsx 

### The solution

Enable `startDateStringValue` and `endDateStringValue` to be controlled props in `DateInput` ?

### Alternatives and examples

-

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
now part of ongoing date picker work

**Comment by origami-z** [comment]
Input value is controllable now, updated example with `lab.52` version. 
https://stackblitz.com/edit/salt-template-l4mqoy?file=App.tsx,RHFDatePicker.tsx

This is achievable not, so closing. Left with one minor TS error raised in #4237
