### ISSUE TITLE
Component QA Story fix up

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3713]
- Dialog
    - move to core
    - combine stories to reduce cost if possible
    - Missing no injection
- File Drop Zone
    - Missing no injection
- Overlay
    - combine stories to reduce cost if possible
    - Missing no injection

**Comment by mark-tate** [comment]
Adhoc task that someone can pickup if they have free capacity

**Comment by origami-z** [comment]
Jul 15 - Delay to next sprint. Not enough Dev capacity

**Comment by mark-tate** [comment]
complete

**Comment by mark-tate** [comment]
new starter could help us with this
