### ISSUE TITLE
Dropdown list flicks when being auto-scrolled

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3717]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

v1.31.0

### Description

There is an issue with the dropdown. When there are many records and user have scrolled down in the list and when user move the cursor towards the first element present in the list at that moment and dropdown area, then it auto scrolls to the top of the list. Also, sometimes there is flicker in the dropdown and screen as well.

### Steps to reproduce

lets consider in [example](https://www.saltdesignsystem.com/salt/components/dropdown/examples#object-values) present on Salt page.

- Scroll down dropdown list to the bottom (maybe a bit of scrolling the main page)
- Hover over top of dropdown list
- [Sometimes] the page is flicked to the top, and next time expanding the dropdown list, it's no longer a scrolling scrolling container

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
@yunjungyeh can you review as part of combobox work ?

**Comment by yunjungyeh** [comment]
@joshwooding  fixed the first 2 items below:
- Scroll down dropdown list to the bottom (maybe a bit of scrolling the main page)
- Hover over top of dropdown list

**Comment by joshwooding** [comment]
Fixed by #3900
