### ISSUE TITLE
Enable theme next features on site

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3738]
With #3714, we need to think about how to surface those additional styling options on the main site. It could be additional a toggle on the main site, or deploy a copy specifically for theme next, or isolate theme next just to example area.

**Comment by origami-z** [comment]
25 Jul - have some basic idea, going to prototype something and show others

**Comment by origami-z** [comment]
Aug 12 - PR prototype in #3897, needs discussion

**Comment by origami-z** [comment]
Aug 30 - will rearrange toggles from [Figma mock](https://www.figma.com/design/K3i9i0iYoJbdQcchhYXY63?node-id=393-19322#928001921)

**Comment by mark-tate** [comment]
Espresso Goal: PR ready, could be merged once reviewed

link to be shared to team

**Comment by origami-z** [comment]
Code merged in #4082, will be promoted to production during next release
