### ISSUE TITLE
Add Pill group to Form Field control

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3750]
Add Pill group to Form Field control (be sth like that but called Input with Pill group https://www.figma.com/file/68D63Nnlrx29Mhs19eEF4d/UITK-v33%3A-Light-components?type=design&node-id=22682%3A360473&mode=design&t=rjgalh0H424Ad4BE-1)

Combobox guide page (and potentially a combo box sticker): how you combine Input with Pill group

```[tasklist]
### Tasks
- [ ] Salt 1 component
- [ ] Salt next component
- [ ] Component Guide
```

**Comment by joshwooding** [comment]
Replaced by #3643
