### ISSUE TITLE
Salt Next - Fix: Icon 2x won't resize properly

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3755]
Salt Next - Fix: Icon 2x won't resize properly like the other sizes

**Comment by mark-tate** [comment]
Latte: complete by EOS

**Comment by yunjungyeh** [comment]
This is not relevant now as the icon has been removed from the component list and are being used directly from the Salt Icon library

**Comment by dplsek** [comment]
Pending update from @yunjungyeh moving to Lungo until we know otherwise
