### ISSUE TITLE
Figma Salt Next - Banner should have the same Optional Title prop as System Status

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3760]
https://www.figma.com/design/YVs0akocogiev3kZuqKZDW/System-Status?node-id=87-3211&t=u7sy5jHRJ1G0DYCx-0#848023029

```[tasklist]
### Tasks
- [x] Salt Next (Ben)
- [ ] ~~Salt 1 Light/Dark (Yun)~~ #3935
```

**Comment by mark-tate** [comment]
@bhoppers2008  we can treat these two banner issues as the same priority for Cortado

**Comment by bhoppers2008** [comment]
This work is done. Ready for @yunjungyeh to review and merge.

**Comment by mark-tate** [comment]
Cortado Goal:
Salt 1 light and dark updated

**Comment by origami-z** [comment]
Aug 12 - haven't started
