### ISSUE TITLE
Ag grid Countries symbol looks bigger in HD Compact in ag grid theme v2

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3775]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

v2

### Description

Countries symbol in HD Compact grid looks large

in 1.14.0, it used to be smaller 

https://github.com/jpmorganchase/salt-ds/blob/7c6437c9de3e0c2f4fc0e1004fda2dcf677b180e/packages/ag-grid-theme/css/salt-ag-theme.scss#L33

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Jul 17 - Snapshot release in #3822 confirmed the fix. Will do more regression test.

**Comment by mark-tate** [comment]
To be released in next release
