### ISSUE TITLE
Combo box different selection and clear behaviour 

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3785]
### Area

UI Components

### The problem

Currently following is combo box behavior

- If user select any option then they have to erase complete text or most part of the text to show complete list and update option.

- If user adds some text and then move out and then focus inside it wont show the selected option and something wont show options to user(If previous entered text doesn't match with options).

### The solution

It is good to have following things:

- Show all option on focus

- Show filtered **selected** option when user types

- Clearing filter string if no selection is made

    - If there was no selection earlier, show blank

    - If there was a selection before, clear filter string and revert to previous selection

- ~~Clear selection if filter string is made blank by user.~~ (done in https://github.com/jpmorganchase/salt-ds/blob/e8d923ce43d681954f54760a60b70bfa9582ed6c/packages/core/src/combo-box/ComboBox.tsx#L311-L313)

### Alternatives and examples

https://codesandbox.io/p/sandbox/react-hook-form-salt-combobox-y2nd96

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
cc @bhoppers2008 @joshwooding

**Comment by bhoppers2008** [comment]
On this bullet "If there was a selection before, clear filter string and revert to previous selection"... i find it unexpected that an 'Esc' key press doesn't revert to previous selection at any point (even if all characters have been removed from the field).

**Comment by yunjungyeh** [comment]
Interaction specs are done and to be reviewed, details in teams group chat.
cc @origami-z @bhoppers2008 @joshwooding 

1. Show all option on focus - **code example as Custom Filtering** 
2. Show filtered selected option when user types - **code to be done**  + **a bug to be fixed**: for now it's different behaviour between clicking arrow button and the input 
3. Clearing filter string - **code to be done** 
4. Clear selection if filter string is made blank by user - **code done**

**Comment by mark-tate** [comment]
Cortado Goal: create tickets for each example and label "help wanted"

**Comment by mark-tate** [comment]
closing in favour of individual issues #3953, #3954, #3952
