### ISSUE TITLE
Multi select combo box pill hover is wrong in theme next

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3786]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.31.0

### Description

In theme next, pill within combo box is light blue on hover and is not readable

https://storybook.saltdesignsystem.com/?path=/story/core-combo-box--multiselect&globals=density:touch;themeNext:enable

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

## Work notes

- Combo box spec should be updated to make it clear which colors are override from default pill
- Design to be done in #3643

**Comment by mark-tate** [comment]
had wrong sprint, plan to start in Cappuccino instead

**Comment by origami-z** [comment]
This is a bug report, should take priority than new work @bhoppers2008  @yunjungyeh

**Comment by origami-z** [comment]
Similar selected/active state solution should apply to #3871

**Comment by yunjungyeh** [comment]
26 Jul / 29 Jul - Characteristic Spec being reviewed and updated


**29 Jul Decision with @bhoppers2008 @joshwooding :** the hover is called selected in code, similar to active. For Salt Next will have border. For Salt 1 without border. They are all from Pill without changes. Only adding Keyboard Focus state.

**Comment by yunjungyeh** [comment]
Thu 1 Aug - Had a catch up call with @Vineet119 @ThusharaJ07 @joshwooding, another related issue #3921 created

**Comment by mark-tate** [comment]
Cortado Goal: PR reviewed and merged

**Comment by yunjungyeh** [comment]
Figma Spec: https://www.figma.com/design/ICpaMU4L3bdPUAodX7k7RX/Combo-Box?node-id=6267-3548&t=OhzKErFX7oo8RgR8-1

**Comment by origami-z** [comment]
Aug 12 - release blocked by button update

**Comment by joshwooding** [comment]
Closed by #3985
