### ISSUE TITLE
Dot badge development

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3787]
Follow design done by #3321.

Spec: https://www.figma.com/design/nGyYwURvwapYwYUTlMXd7r/Dot-badge?node-id=1521-426&t=L2BThd8sZH3AQ9mf-1

**Comment by mark-tate** [comment]
Goal: Dev complete by EOS
Kickoff required

**Comment by yunjungyeh** [comment]
kick-off scheduled on Thu 25 Jul

**Comment by origami-z** [comment]
Push 1 sprint behind due to capacity

**Comment by mark-tate** [comment]
Cortado Goal:
Kickoff required
RC by EOS

**Comment by yunjungyeh** [comment]
PR #3969

**Comment by joshwooding** [comment]
Aug 14 = PR has initial review. Needs a final review by @yunjungyeh

**Comment by origami-z** [comment]
Aug 16 - Needs discussion on code API.

**Comment by javasun1000** [comment]
COmmenting to test access with @joshwooding

**Comment by joshwooding** [comment]
@Vineet119

**Comment by yunjungyeh** [comment]
Updates for the feedback from Jake, @mark-tate, @joshwooding, @origami-z, @dplsek, @yunjungyeh are addressed, PR https://github.com/jpmorganchase/salt-ds/pull/3969 merged to main
