### ISSUE TITLE
Update ListBox inconsistencies in Figma

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#3789]
Off off the back of fixing multiline examples (issue: https://github.com/jpmorganchase/salt-ds/pull/3739), we noticed some inconsistencies in the Figma libraries between Salt Current and Salt Next which need to be aligned on:

1. List Box - by default the icon is switched off in Salt Current, but in Salt Next it is turned on. Speaking with Yun/Josh we've decided to turn it off in Salt Next, reason being there is no icon by default in the code example. 
2. List Box - name of sticker in Salt Next is 'Single-select List Box sticker' and in Salt Current it is 'Single-select'... we are going to align these and update Salt Current to match Salt Next.

**Comment by shey-v** [comment]
Updates have been done in Figma branch with confluence pages (salt 1 & 2) updated, @yunjungyeh to merge and publish.

**Comment by yunjungyeh** [comment]
9 July - merged Salt 1 Light/Dark and Salt Next
