### ISSUE TITLE
Navigation item group screenreader only reading expand

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3792]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.31.0

### Description

When focus is on grouped item, screen reader is only out "expand", 

https://www.saltdesignsystem.com/salt/components/navigation-item/examples#vertical-nested-group

In VoiceOver - “expand, collapsed, button”

This is likely caused by `aria-label` set on the button
https://github.com/jpmorganchase/salt-ds/blob/9abf267432bc47f4df16bdd7d0a1039d3e45c42d/packages/core/src/navigation-item/ConditionalWrapper.tsx#L28-L29

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
will be addressed by https://github.com/jpmorganchase/salt-ds/issues/3279

**Comment by mark-tate** [comment]
going out in next release

**Comment by joshwooding** [comment]
Released
