### ISSUE TITLE
Bordered date picker dev

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3795]
### Area

UI Components

### The problem

Need bordered version to be more compatible with theme next's rounded corner

Design aligned to other form controls in #3456

### The solution

Add bordered option

### Alternatives and examples

/

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
design review required ?
@dplsek

**Comment by ThusharaJ07** [comment]
~added provision for dropdowns (month and date) to appear as bordered when the date picker is bordered
Merged to labs.
