### ISSUE TITLE
Figma add bordered option to date picker

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3796]
Add bordered option like input / combo box

Dev work in #3795

**Comment by mark-tate** [comment]
@bhoppers2008  can you update this ticket ?

**Comment by mark-tate** [comment]
Goal: complete by EOS

**Comment by ivan-calderon** [comment]
@mark-tate, @dplsek, @joshwooding, @origami-z bordered controls for Calendar and Date Picker ready for review in Figma. 

[Date picker updates](https://www.figma.com/design/ChsbbO7pLomT4F5H6tQyLP/branch/BfdvvnFJO5JOj553lBiB6h/Salt-(Next)-Components-%26-Patterns?m=auto&node-id=20003-4202&t=njWBW51WSA54cC3v-1)
- Bordered **date input** is available via Figma properties panel
- 1px gap added between the input and calendar

[Calendar updates](https://www.figma.com/design/ChsbbO7pLomT4F5H6tQyLP/branch/BfdvvnFJO5JOj553lBiB6h/Salt-(Next)-Components-%26-Patterns?m=auto&node-id=24735-11606&t=njWBW51WSA54cC3v-1) affecting Date picker
 - Bordered **dropdown controls**  

c.c. @yunjungyeh

**Comment by origami-z** [comment]
Aug 12 - added in Figma as branch

**Comment by joshwooding** [comment]
Aug 14 - Needs a final review from @yunjungyeh.
