### ISSUE TITLE
Dropdown example chevron is not aligned to right correctly

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3820]
### Package name(s)

Website / Documentation

### Description

Chevron is rendered on the left, instead of right 
https://www.saltdesignsystem.com/salt/components/dropdown/examples#default
v.s.
https://storybook.saltdesignsystem.com/?path=/story/core-dropdown--default

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Duplicate of #3443
