### ISSUE TITLE
Figma H3 small text style does not use "Heading Font" option

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3830]
### Package name(s)

Core (@salt-ds/core)

### Description

H3 small doesn't have "Heading Font" mode switch in Figma

### Steps to reproduce

Select H3 layer and try mode switch (double hexagon icon), there is no heading mode

 https://www.figma.com/design/e753bB0n5Adc0LCXqtvslu/Salt-(Next)-Style-Library?node-id=4440-2296&t=ictZNN9YmRUw0dlf-4

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Need to verify all text styles

**Comment by pseys** [comment]
The text style variable have become detached somehow. It's a simple fix I think but I need to check all styles to make sure its not wider 
spread

**Comment by pseys** [comment]
Fixed. The issue was limited to H3 Small and has been corrected. The Figma library has been published with the fix and a release note added explaining the fix.
