### ISSUE TITLE
Facing Type Error in @Salt/lab 1.0.0-alpha.49 - Generic type 'ElementType' requires between 0 and 1 type arguments

### ISSUE THREAD

**Issue by ashwini-shinde-chase** [jpmorganchase/salt-ds#3831]
### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

@Salt/lab 1.0.0-alpha.49

### Description

[build:*types] > build:types
[build:*types] > tsc
[build:*types]
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(152,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(193,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(223,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@internationalized/date/dist/types.d.ts(272,5): error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.
[build:*types] C:/JPMC/DEV/TMP/MSPayments/dsp-merchant-dashboard-mfe/node_modules/@salt-ds/lab/dist-types/form-field-legacy/FormHelperText.d.ts(7,49): error TS2707: Generic type 'ElementType' requires between 0 and 1 type arguments.
[build:*types] npm run build:types exited with code 2

### Steps to reproduce

Execute tsc command.
Using below versions:
npm 10.5.2
node js - 20.13.1
"@salt-ds/core": "^1.32.0",
    "@salt-ds/icons": "^1.12.1",
    "@salt-ds/lab": "^1.0.0-alpha.49",
    "@salt-ds/theme": "^1.20.0",

### Expected behavior

Expected to run build without errors.

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Thanks for raising an issue, just curious have you tried changing your code to use the FormField from core? If you are using form controls from core it would be required.

**Comment by ashwini-shinde-chase** [comment]
Yes, FormField component, we are using from core.
I am using DatePicker from lab.

**Comment by origami-z** [comment]
The error suggests you're lab form field? Which TypeScript version are you on?

> @salt-ds/lab/dist-types/form-field-legacy/FormHelperText.d.ts(7,49):

**Comment by ashwini-shinde-chase** [comment]
"target": "ES2016"
    Using as configured in tsconfig.json
