### ISSUE TITLE
Black block icon shown if invalid icon name is given

### ISSUE THREAD

**Issue by JahanU** [jpmorganchase/salt-ds#3842]
### Package name(s)

Icons (@salt-ds/icons)

### Package version(s)

"@salt-ds/icons": "^1.12.1",

### Description

See example here:
https://stackblitz.com/edit/salt-template-hvvtmr?file=App.tsx

### Steps to reproduce

https://stackblitz.com/edit/salt-template-hvvtmr?file=App.tsx

### Expected behavior

No Icon? empty space

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
No icon is worse to find out the problem
