### ISSUE TITLE
Add HD compact grid support to Salt Next

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3850]
Resolving this issue will add HD compact grid support to the Salt Next Figma library.

The challenge to resolve here is that HD compact cannot be added as a density, as it won't be available to other components (it's unique to grid).

There are two approaches being explored [here](https://www.figma.com/design/lLpxFCNFxmBUAEY5f6ZiMQ/Next-Compact-Grid-Test?node-id=0-1&t=vBCVUYKwt4rMu5aw-1):

1. Variable driven approach: A Figma only `grid row height` variable collection which sets row height to tokens: `default` or `compact (for HD only)`. Risk: `grid row height` can be applied to any density grid (ie., row height for any density can be set to the HD compact height)–mitigated by clearly stating 'HD only' token name.
3. Component props driven approach: An additional component to drive height of HD cells only. Risk: needs to be set per header/cell component–mitigated by providing clear guidance and HD compact grid stickers.

**Comment by bhoppers2008** [comment]
@pseys for reference.

**Comment by bhoppers2008** [comment]
Current spec row height currently excludes border between rows, so we need to configure ag grid with +1 number to be on spec. MTK has HD compact correct, but other densities wrong, which they will fix

**Comment by mark-tate** [comment]
Cortado Goal:
Update spec

**Comment by navkaur76** [comment]
kick off w/ Paul scheduled for 06/08

**Comment by navkaur76** [comment]
Using variable driven solution. @pseys to add relevant variables for row height in Styles library before the component can be updated.

**Comment by joshwooding** [comment]
Aug 14 - @pseys  to add a variable to the Figma library.

**Comment by origami-z** [comment]
Needs result from #3996

**Comment by pseys** [comment]
Figma variables have been created in a branch and are ready to merge. Waiting on a resolution to #3996 before progressing.

**Comment by mark-tate** [comment]
Espresso Goal : released by 13th September

**Comment by pseys** [comment]
Figma variables updated and published ready for Nav to reference in the Data Grid component. Two new 'Figma only' variables are available: `rowHeight` and `contentHeight`

**Comment by bhoppers2008** [comment]
Released on 23rd September. [Full release notes](https://confluence.prod.aws.jpmchase.net/confluence/display/SALTDS/Figma+release+notes).
