### ISSUE TITLE
Document Logo Component on Internal Site

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#3858]
Design in #3525

**Comment by origami-z** [comment]
Aug 12 - Pepper published first version, scaling one density instead of per density

**Comment by joshwooding** [comment]
Aug 19 - Page being created for logo pattern on the internal site

**Comment by joshwooding** [comment]
Aug 20 - Hopefully getting a draft ready by EOW

**Comment by bhoppers2008** [comment]
Moved to next sprint. @mark-tate and Asmita to work together to get Asmita's page mock up on the site (potentially a page under 'Docs' nav item for the time being... it can be reconciled with Honey's site work).

**Comment by mark-tate** [comment]
Espresso Goal, docs to be published by EOS

**Comment by mark-tate** [comment]
Frappe Goal, docs to be published by EOS

**Comment by joshwooding** [comment]
Guidance has been published internally
