### ISSUE TITLE
Character count and help text for multiline input

### ISSUE THREAD

**Issue by zttt5080** [jpmorganchase/salt-ds#3860]
### Area

UI Components

### The problem

The current multiline input doesn't support adding help text label like the help text under regular input, or character count. 

### The solution

Would like to have help text plus character limit count below the multiline input. 

### Alternatives and examples

N/A

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
You can use form field helper text - https://www.saltdesignsystem.com/salt/components/form-field/examples#helper-text
