### ISSUE TITLE
Resolve styling issues with Form Field controls in code

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3861]
The following styling observations need to be resolved across Form Field input type controls:

1. **Hover state when active**: Should be no change in color when the field is active and hovered. **Affects**: Combo Box.
2. **Active activation line**: Activation line should remain visible when the field is active. **Affects**: Combo Box, Input, Multiline.
3. **Active activation line + border color**: When active, activation line and border should color should persist as `var(--salt-editable-borderColor-active)`. No change on hover or click when the field is active.  **Affects**: Combo Box, Date Input.
4. **Status focus ring color** (_Ticket 3612_): Focus ring color should match the status of the field (i.e., error should be `--status-error-borderColor` **Affects**: Combo Box.

**Comment by mark-tate** [comment]
Espresso Goal: low priority compared to Buttons work, pickup once Buttons ready for release (this is higher priority than Charts)
Should just be checking 4 pages on site
