### ISSUE TITLE
Tooltip status getting overridden with form validation status

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3868]
### Area

UI Components

### The problem

We are using Tooltip inside Form field. This tooltip is used to show the description regarding the field. We have set the status as info for the tooltip.

When there is error in the field and Form field validation is set to error then this overrides the status of tooltip as well.

Since this is just an Info regarding the field it's status should not change.

I have added an example [here](https://codesandbox.io/p/sandbox/react-hook-form-salt-input-with-info-text-5tkd9s).

Steps to replicate:

1. Hover on info icon and check the status and icon present in tooltip.

2. Click on submit without entering any text.

3. Error will be shown and when you hover again on info icon then the status of tooltip also changes to error even when we have explicitly set the status to info.

Is there any way to not override the status of tooltip?

### The solution

Tooltip takes its `status` prop as priority than form field status

### Alternatives and examples

?

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by liamsms** [comment]
Hi - I could pick this up
