### ISSUE TITLE
Figma - Component Custom content / Swap audit

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3872]
```[tasklist]
### Tasks
- [x] Accordion
- [ ] Banner (Ben will add)
- [ ] Card
- [ ] Dialog
- [ ] Drawer
- [x] Overlay
- [ ] Panel
- [ ] .Side Panel
- [x] Toast
```

**Comment by joshwooding** [comment]
Can this be updated with a list of affected components please?

**Comment by joshwooding** [comment]
Aug 20 - work starting tomorrow

**Comment by yunjungyeh** [comment]
29 Aug - Component Custom content / Swap audit has been done in confluence.

The following actions (discussed with @bhoppers2008):

For Accordion / Overlay / Toast
- Update Prop names to: Content area
- Update Layer names to: Content area

For Drawer / .Side panel
- add the content area component inside to make them swappable

**Comment by yunjungyeh** [comment]
Updated and merged - Accordion / Overlay / Toast:
- Update Prop names to: Content area
- Update Layer names to: Content area

**Comment by yunjungyeh** [comment]
Testing for Drawer and will be done by EOS.
will create issues for updating .Side panel and Card
