### ISSUE TITLE
Card consolidation and updates

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3875]
**Task 1 (design + dev):**

- Address #3514 

**Task 2 (design):**

Problem: 

Current use of accent is confusing. By default it is grey, but purpose of accent bar is to display color. 

Should Cards be:

1. Default = no accent, grey border
2. Accent = color accent, grey border

Hoverable? 
1) Remove it? (Is it confusing to have hover state but no click? was an MCP requirement)
or...
2) Keep it? If hoverable is true, then the accent bar color is only be displayed on hover.

**Comment by navkaur76** [comment]
26/07 - regroup meeting with Nav, Ben, Darrin, Zhihao + Josh. 

- Confirmed card states + characteristics 
- Accent display is optional for all variants. 
- Rounded corners - some further figma + code work to be done to address the structure. Exploring accent inset within border. 

Nav to pick back up figma work on 30/07 after AL. Zhihao has left some comments around component structure in figma, in the meantime.

**Comment by origami-z** [comment]
Aug 2nd - Code / doc update in Cortado

**Comment by origami-z** [comment]
Aug 5 - more Figma component work needed to address borderless snap issue

**Comment by mark-tate** [comment]
Cortado Goal: Ready For Dev by EOS

**Comment by navkaur76** [comment]
Card token discussion notes: 

**Requirement (if Card is using selectable tokens):**
 
To add a disabled token for interactable card (so the accent is blue, essentially treating disabled card as an alpha of default card).
 
**Outcome:**
 
Explore using actionable tokens for card, instead of selectable. Reasoning:

- Actionable/background contains colours for all card accent states (apart from a new token that will need adding for “active disabled”).
- Instead of adding action states to accent (which is only treated as a static border + background colour) - we’re saying it is an interactive card, therefore an actionable item. This semantically aligns to actionable tokens.
- Provides continuity with button which is also an actionable item.
- Q: _Is Card then considered an actionable or selectable component?_ A: We can take precedent for this from toggle button group, which uses actionable tokens but is a component you make a selection from. Similarly, we’re saying interactable card is using actionable tokens, but can be considered selectable when used within a group (i.e., selectable pattern). Either way, visually card wouldn’t change and would use actionable tokens across both use cases.
- (Follow up note: does toggle button group also need an active-disabled token?)

We would end up with: Static card, Link card and Interactable card (which covers both “actionable” and “selectable” interactions)
 
**Question:** do we want to consider a name change from “Interactable card” to “Actionable card”? We don’t use the term “interactable” elsewhere. OR, do we document what we mean by “interactable” – i.e., Interactable card is both actionable and selectable. This could be added as an entry in the site glossary page.
 
**Other agenda items discussed:**
 
- When wiring up card to category, the category colours will require equivalent disabled tokens
- Figma borderless issue – Nav to first make token updates and then address the borderless behaviour as a secondary problem. Follow up call on this pending.

**Comment by pseys** [comment]
Had a discussion with Nav today about actionable token use in Card. Nav has set-up time for us to look into this in more detail tomorrow as it's not as straight forward as first thought and we need to review our options.

**Comment by origami-z** [comment]
Aug 12 - discussed tokens on Friday

**Comment by origami-z** [comment]
Aug 16 - likely slip to next sprint

**Comment by joshwooding** [comment]
Aug 20 - Tokens agreed, but need updates to the library. @origami-z  to look at the code updates.

**Comment by pseys** [comment]
The variable `accent-background-disabled` has been added to the Salt (Next) Style Library. The variable references `--palette-accent-disabled`

**Comment by pseys** [comment]
In Next I've added:
`accent-background-disabled` that points to an existing palette token of `--palette-accent-disabled`

In Legacy we need to also add `--palette-accent-disabled` which points to `--salt-color-blue-500-fade-background` – It needs to be 'accent-disabled' because `--palette-accent-background-disabled` has previously been deprecated.

**Comment by joshwooding** [comment]
> In Next I've added: `accent-background-disabled` that points to an existing palette token of `--palette-accent-disabled`
> 
> In Legacy we need to also add `--palette-accent-disabled` which points to `--salt-color-blue-500-fade-background` – It needs to be 'accent-disabled' because `--palette-accent-background-disabled` has previously been deprecated.

We've undeprecated tokens before (tertiary container tokens). Is the a reason accent-disabled is different?

**Comment by pseys** [comment]
> We've undeprecated tokens before (tertiary container tokens). Is the a reason accent-disabled is different?

If we're OK undeprecating the token then let's do that rather than add more to the legacy palette. I'll change what I've done to use `--palette-accent-background-disabled` 

Thanks Josh.

**Comment by joshwooding** [comment]
> > We've undeprecated tokens before (tertiary container tokens). Is the a reason accent-disabled is different?
> 
> If we're OK undeprecating the token then let's do that rather than add more to the legacy palette. I'll change what I've done to use `--palette-accent-background-disabled`
> 
> Thanks Josh.

Worthing confirming with @origami-z but we've done it before so we have precedence

**Comment by origami-z** [comment]
if that's the right naming, let's undeprecate i guess

**Comment by origami-z** [comment]
Aug 28 - Token used is blocked by Button update

**Comment by mark-tate** [comment]
Espresso Goal to be released by September 13th

**Comment by mark-tate** [comment]
Frappe Goal: Code & Design in sync and published to Core

**Comment by origami-z** [comment]
From @navkaur76 - Updated card specs: https://www.figma.com/design/gbHcDLjP1M976avIlRDWl7/Card?node-id=3811-72617

**Comment by mark-tate** [comment]
Frappe Goal: released by EOS

**Comment by origami-z** [comment]
Sep 17 - code changed, needs design review, especially around Salt current token on hover/active (which doesn't have border)

**Comment by navkaur76** [comment]
Sep 20 - meeting with @pseys on the Salt (current) tokens for the hover and active borders. Paul to update the actionable/accented/border tokens in current to change those two borders from transparent to blue 700 + blue 500. Will also result in a small border update to button too.

**Comment by pseys** [comment]
As a follow up to Nav's comment, in order to accommodate Card having a accented border on hover and active we need to update the following two characteristics in Salt 'current' to use two new palette tokens:

| Characteristic | Palette | Light mode | Dark mode |
|---|---|---|---|
| `actionable-accented-borderColor-hover` | `palette-interact-cta-border-hover` (new) | `blue-500` | `blue-500` |
| `actionable-accented-borderColor-active` | `palette-interact-cta-border-active` (new) | `blue-700` | `blue-700` |

As Nav mentioned, this will result in the bordered button having a coloured border on hover and active, however, this will match the background color so won't be visible to users. 

If this is an acceptable solution from a technical perspective I'll update the Figma files accordingly. 

cc @origami-z

**Comment by origami-z** [comment]
Shouldn't be a problem, preview after the change [button](https://3836b311.saltdesignsystem-storybook.pages.dev/?path=/story/core-button--accented) and [accented card](https://3836b311.saltdesignsystem-storybook.pages.dev/?path=/story/core-interactable-card--accent-placement)

**Comment by origami-z** [comment]
Sep 23 - Code change ready in #4111, needs design review with 3 card types

**Comment by mark-tate** [comment]
Meeting oni Tue, update on Wed, by end of sprint expected to be complete

**Comment by mark-tate** [comment]
Galao Goal: meeting 30th Sept / by end of wk1 design complete

**Comment by mark-tate** [comment]
part of next figma release

**Comment by origami-z** [comment]
code complete, in release from #4179

**Comment by pseys** [comment]
`actionable-accented-border-hover`  and `actionable-accented-border-active` colors updated in Figma light and dark mode libraries.

**Comment by mark-tate** [comment]
Latte goal: Design side ready to publish, requires Figma variable.
(Code released already)

**Comment by pseys** [comment]
Bug raised with corner radius not adhering to style option choices.

**Comment by yunjungyeh** [comment]
16 Oct - in Figma: updated to the new variables, metadata, component description and some fixes, and merged!
