### ISSUE TITLE
Stepper Input theme next style

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3878]
Update stepper input for theme next, potential idea from Ben 

- isolate the top and bottom corners and keep the middle four square? Similar to Segmented Button Group
- might be more effective if the gap between the top/bottom stepper buttons doesn't scale but remains consistent at border/ border-strong

**Comment by mark-tate** [comment]
needs design input @bhoppers2008 
is it impacted by button changes?

**Comment by mark-tate** [comment]
Frappe Goal: Refer to other Stepper Input ticket

**Comment by mark-tate** [comment]
Design review complete
