### ISSUE TITLE
Provide support for a Pill menu variant in Figma.

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3888]
Resolving this issue will add support for Pill to be used as a menu. This is [possible in code](https://stackblitz.com/edit/salt-template-nhteby?file=package.json,index.tsx,App.tsx), but needs support in Figma.

The following tasks need to be completed:

1. Updates to Salt Next library
2. Add right icon (with boolean prop - default `hidden`) to Pill `Default` component.
3. Provide sticker coupling Pill with Overlay List.

**Stakeholder**
Request comes from [Pepper team](https://www.figma.com/design/ChsbbO7pLomT4F5H6tQyLP?node-id=8864-83291#885328383).

**Comment by yunjungyeh** [comment]
Mon 5 Aug - merged in Figma Salt Next
