### ISSUE TITLE
Request for interactive tag variants

### ISSUE THREAD

**Issue by jf-ux** [jpmorganchase/salt-ds#3891]
### Area

UI Components

### The problem

The current tag component is only informative.

### The solution

We would like allow users to hover over or click on tags to show some additional information or tooltips.

### Alternatives and examples

I heard this request is in backlog already but just want to provide additional use cases if needed.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
If you need a tooltip on a Tag, you should be able to add one.
Tags are not designed to be interactive, so what you probably need is Pill, which is the closest thing to Tag that is interactive.

Thanks for the feedback

**Comment by origami-z** [comment]
For click use case, you may need Overlay
