### ISSUE TITLE
Tabstrip overflow showing as undefined

### ISSUE THREAD

**Issue by steinalex** [jpmorganchase/salt-ds#390]
Since bumping the UITK labs package to 0.4.0 (from 0.3.0), we have a bug where the overflow in the `Tabstrip` component shows as `undefined`.

![image](https://user-images.githubusercontent.com/54838842/188698590-5a2175c7-e7eb-488f-b531-e15daa42fccc.png)

A simplified example of how to reproduce the issue
```ts
const tabs = [
{ id: 1, title: 'Tab 1' }, 
{ id: 2, title: 'Tab 2' }, 
{ id: 3, title: 'Tab 3' }, 
{ id: 4, title: 'Tab 4' }
]

<Tabstrip>
  {tabs.map(({ id, title }) => {
    return <Tab key={id}>{title}</Tab>
  ))}
</Tabstrip>
```

**Comment by ZarkoPernar** [comment]
Hey @steinalex , thanks for submitting this bug. We will keep this in the backlog as we are currently nearing a release of the next version of Tabs rebuilt from scratch. It will initially be released as TabsNext in labs but quickly moved to core as just Tabs. It will keep a subset of the same api as the current version of Tabs so the migration should be fairly simple. I will ping you in this thread when we release. Expect it within a week.

**Comment by ZarkoPernar** [comment]
@steinalex a fix for this issue is to add a label prop to each tab. So in your example that would be:

```jsx
Since bumping the UITK labs package to 0.4.0 (from 0.3.0), we have a bug where the overflow in the Tabstrip component shows as undefined.

image

A simplified example of how to reproduce the issue

const tabs = [
{ id: 1, title: 'Tab 1' }, 
{ id: 2, title: 'Tab 2' }, 
{ id: 3, title: 'Tab 3' }, 
{ id: 4, title: 'Tab 4' }
]

<Tabstrip>
  {tabs.map(({ id, title }) => {
    return <Tab key={id} label={title}>{title}</Tab>
  ))}
</Tabstrip>
```
