### ISSUE TITLE
Figma updates following Button update

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#3903]
Following the release of Button updates (inclusion of appearance and color options) the following needs to be updated:

**Next**
- [x] Overlay – layers refer to secondary button
- [x] Segmented Button – component descriptions mention CTA, Primary, Secondary
- [x] Form Field – CTA button mentioned in adornment playground
- [x] Toast – QA Playground

**Legacy (light and dark)**
- [x] Pill – needs updating to use new actionable styles
- [x] Toggle Button – needs updating to use new actionable styles
- [x] Data Grid – QA Playground mentions CTA, Primary and Secondary
- [x] Segmented Button – references CTA, Primary, Secondary in component layers, component description and QA playground
- [x] Toast – mentions CTA, Primary, Secondary in QA Playground
- [x] Dialog – QA Playground mentions primary button
- [x] Split Button - References

**Comment by pseys** [comment]
FYI @bhoppers2008

**Comment by mark-tate** [comment]
@bhoppers2008 probably needs splitting up ?

**Comment by mark-tate** [comment]
Espresso Goal to be released by September 13th

**Comment by joshwooding** [comment]
@bhoppers2008 can you mark the ones you've resolved please!

**Comment by mark-tate** [comment]
Frappe Goal: update and sync with code by EOS

@navkaur76 to update above list to tick off the completed work at SOS

**Comment by mark-tate** [comment]
status about needs updating @navkaur76

**Comment by bhoppers2008** [comment]
This issue is closed. Updates complete and merged. Ready to publish.
