### ISSUE TITLE
Form controls in Figma act incorrectly when vertically resized

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3909]
When resizing form controls vertically they have the incorrect alignment.

Potential solution: Single line should have min height / max height
```[tasklist]
### Components
- [ ] Combobox
- [ ] Dropdown
- [ ] Date Picker
- [ ] Input
- [ ] Multiline Input
```

**Comment by bhoppers2008** [comment]
Update: All libraries updated and merged. Ready to publish.
