### ISSUE TITLE
Dialog size implementation is wrong between code and doc

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3920]
### Package name(s)

Website / Documentation

### Description

Currently, what's in code is doing different than what documentation is saying (e.g. medium and large dialog does not go to full screen when xs breakpoint).

https://github.com/jpmorganchase/salt-ds/blob/e8d923ce43d681954f54760a60b70bfa9582ed6c/packages/core/src/dialog/Dialog.css#L54-L127

Size table (width) and Size table (height) is not formatted correctly

The column headers for the Height table read 'width' instead of 'height'.

https://www.saltdesignsystem.com/salt/components/dialog/examples#sizes

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Cortado Goal:
Kickoff required
Lower priority than other Cortado work so moving to Doppio, Nav will pull this into Cortado if blocked or completes other work

**Comment by mark-tate** [comment]
Espresso Goal: decide which one is correct and feedback to team ?
Has relationship with side-panel and other similar components that might need re-sizing as well.
For Espresso, we should identify the work needed and cost, if necessary we make a call and push this to Frappe ?

**Comment by mark-tate** [comment]
Moved  to Latte, so we can spend Galao consolidating the Header changes across  components and then re-visit this, as the changes, somewhat overlap

**Comment by mark-tate** [comment]
Latte Goal: define correct size by EOS

**Comment by ivan-calderon** [comment]
@bhoppers2008, @origami-z the [site docs](https://www.saltdesignsystem.com/salt/components/dialog/examples#sizes) are incorrect and information should align to code. Please refer to [this recommendations](https://www.figma.com/design/mwOfVisFMPyiQxtkanggsb/Dialog?node-id=1795-12935&t=orpXRo8gTaH5pZze-1) for more details. I have also added a recommendation about to re-organize the table to make specs more clear and improve info scanning. LMK your thoughts!

**Comment by origami-z** [comment]
PR #4346 created following @ivan-calderon 's recommended change on Figma

**Comment by mark-tate** [comment]
Lungo Goal: review PR

**Comment by mark-tate** [comment]
merged already
