### ISSUE TITLE
Ag grid theme copy cell background color is flipped

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3922]
### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

v2.0.1

### Description

When copy cell in dark mode, background flips to white (the blink), was not the case before v2. 

In light mode, it's flipped to dark.

### Steps to reproduce

1. Go to https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples#variants
2. Set to dark mode
3. Copy any cell (ctrl + c)
4. Observe the blinking color is white

### Expected behavior

Possible solution: `--ag-range-selection-highlight-color: var(--salt-overlayable-rangeSelection);`, or create a new token to be more prominent 

https://www.ag-grid.com/react-data-grid/global-style-customisation-selections/#cell-selections

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Cortado Goal:
To be fixed and released

**Comment by origami-z** [comment]
Aug 12 - found potentail color, @origami-z  to work with @dplsek

**Comment by origami-z** [comment]
Prototype stackblitz - https://stackblitz.com/edit/salt-ag-grid-v31-theme-v2-lkzmse?file=style.css,App.jsx

**Comment by joshwooding** [comment]
Aug 20 - Work to resume after button work is done

**Comment by origami-z** [comment]
New prototypes
- Salt current: https://stackblitz.com/edit/salt-ag-grid-v31-theme-v2-rx4qkp?file=App.jsx,style.css 
- Salt next: https://stackblitz.com/edit/salt-ag-grid-v31-theme-v2-lwyexe?file=style.css,App.jsx

**Comment by dplsek** [comment]
We will be using blue 500/50 in Salt CURRENT and blue/teal 700/300 in Salt NEXT for the flashing copy state. Links included above to the coded examples and the corresponding Figma file with contrast ratios for text can be found [here](https://www.figma.com/design/n2I0jXlzOYZWjxTxkWkNPk/AG-Grid-theme-copy-cell-background-color?node-id=0-1&t=exTdKo9B6Mo2OYuC-1)

**Comment by origami-z** [comment]
We need a set of tokens in theme, shall we call it `--salt-selectable-background-highlight` (more or less align with ag grid's variable `--ag-range-selection-highlight-color`)? Potential mapping below, @pseys to confirm

## Salt current

| Characteristics | Palette | Foundation | 
| --- | --- | --- |
| `--salt-selectable-background-highlight` | `--salt-palette-interact-background-highlight` (light) | `--salt-color-blue-50` | 
| `--salt-selectable-background-highlight` | `--salt-palette-interact-background-highlight` (dark) | `--salt-color-blue-500` | 

## Salt next

Alpha palette only deal with white/black, go with accent palette?

| Characteristics | Palette | Foundation | 
| --- | --- | --- |
| `--salt-selectable-background-highlight` | `--salt-palette-accent-action-highlight` (light) | `--salt-color-blue-300` | 
| `--salt-selectable-background-highlight` | `--salt-palette-accent-action-highlight` (dark) | `--salt-color-blue-700` |

**Comment by origami-z** [comment]
Extend a sprint for token review

**Comment by mark-tate** [comment]
Espresso @pseys to review and released by 13th September

**Comment by origami-z** [comment]
@pseys yes, if we can make this change in this release, it would be good. Button release remains the highest priority across the board

**Comment by origami-z** [comment]
New proposal to use the same token from range selection token, which works mostly ok except when cell ranges were already selected, then copy would result the same color highlight. Updated prototypes to show this.

> * Salt current: https://stackblitz.com/edit/salt-ag-grid-v31-theme-v2-rx4qkp?file=App.jsx,style.css
> * Salt next: https://stackblitz.com/edit/salt-ag-grid-v31-theme-v2-lwyexe?file=style.css,App.jsx

**Comment by pseys** [comment]
FYI @origami-z @dplsek 

| Characteristic | Theme | Palette | Foundation | Foundation (Fade) |
|--|--|--|--|--|
| `--salt-overlayable-background-highlight` | **Next** | `--salt-palette-alpha` | `--salt-color-black-30a` | |
| | | | `--salt-color-white-30a` | |
| | **Legacy** | `--salt-palette-neutral-highlight` | `--salt-color-black-fade-background-highlight` | `--salt-color-black` + `--salt-opacity-25` |
| |  |  | `--salt-color-white-fade-background-highlight` | `--salt-color-white` + `--salt-opacity-25` |

**Comment by bhoppers2008** [comment]
@pseys to document the change and update light/dark modes and the Salt (Next) Styles to keep alignment with code.

**Comment by mark-tate** [comment]
Frappe Goal: released by EOS
