### ISSUE TITLE
ToggleButtonGroup returns undefined when an icon is clicked

### ISSUE THREAD

**Issue by liamsms** [jpmorganchase/salt-ds#3923]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.32.0

### Description

When clicking a ToggleButton's icon in a controlled ToggleButtonGroup, the `onChange` event will return an object where `target.value` is undefined instead of the value prop provided to the ToggleButton. Clicking the ToggleButton's text works as expected. 

### Steps to reproduce

1. Create a controlled ToggleButtonGroup.
2. Click one of the ToggleButtons on the icon - not the text.
3. `onChange` will return an object where `target.value` is undefined.

```
export default function App() {
    const [value, setValue] = useState('first');

    const handleChange = (event: any) => {
        setValue(event.target.value);
    };

    return (
        <ToggleButtonGroup value={value} onChange={handleChange}>
            <ToggleButton value="first">
                <AppSwitcherIcon />
                First
            </ToggleButton>
            <ToggleButton value="second">
                <VisibleIcon />
                Second
            </ToggleButton>
            <ToggleButton value="third">
                <FolderClosedIcon />
                Third
            </ToggleButton>
        </ToggleButtonGroup>
    );
}
```

### Expected behavior

Expected the `onChange` event to return an object where `target.value` equals the value prop provided to the ToggleButton.

Workaround by wrapping the children with `{pointerEvents: 'none'} `
```
<ToggleButton value="first">
    <div style={{ pointerEvents: 'none', display: 'flex', alignItems: 'center', gap: 5 }}>
        <VisibleIcon />
        First
    </div>
</ToggleButton>
```

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Judging by toggle button group code, `currentTarget` should be used? https://github.com/jpmorganchase/salt-ds/blob/4906584e8d5740b7492ad3e3cdb16dc570c6a6b3/packages/core/src/toggle-button-group/ToggleButtonGroup.tsx#L85

**Comment by liamsms** [comment]
That fixed it - ty
