### ISSUE TITLE
Update Pill to follow the new actionable tokens introduced by #3325

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3930]
Spec:

New actionable tokens were added for button but "button" like components need to be updated e.g. Pill

```[tasklist]
### Tasks
- [x] Update pill spec
- [x] Update component in Figma
- [ ] #3925
```

**Comment by origami-z** [comment]
Aug 5 - assigning to Cortado, given code change will happen in #3925

**Comment by yunjungyeh** [comment]
Figma Spec: https://www.figma.com/design/TO4KPFbKdlqtDdy1tbp6BO/Pill?m=auto&node-id=2516-3625&t=CA2m2bPj5zqvvAmg-1
cc @joshwooding @bhoppers2008 @Vineet119

**Comment by origami-z** [comment]
Aug 12 - blocked by button update

**Comment by mark-tate** [comment]
Espresso 2nd week button task, released by 13th September

**Comment by mark-tate** [comment]
Frappe Goal: released by EOS

**Comment by mark-tate** [comment]
code updates required still
