### ISSUE TITLE
Update Banner component in Salt Figma

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#3935]
The following updates have been made in Salt Next, and need to be made to Salt Light/Dark.
Salt Next issue #3642 #3760 

Aug 3, 2024 update

- Optional title element added.
- Swappable Content area added.
- Inline swap added.
- Props added to support swapping and optional elements.
- Prop names and order updated.
- All component descriptions updated.
- QA stories added.

**Comment by mark-tate** [comment]
Cortado Goal:
Update in Salt 1 spec in light/dark

**Comment by origami-z** [comment]
Aug 12 - should be pushed to later sprint

**Comment by yunjungyeh** [comment]
@bhoppers2008  Branches are created with some updates in Light/Dark (called #3935 Update Banner: Optional title, swappable content area, Inline swap)

**Comment by mark-tate** [comment]
To be published in next release
