### ISSUE TITLE
Chart Theme: Categorical color palette re-order

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#3937]
Linked to #3323

Consumers have requested to re-order the categorical color palette to maximize visual contrast between colors in the fixed order.

**Comment by mark-tate** [comment]
Can we start this without knowing the High Charts version we will support ?

**Comment by origami-z** [comment]
> Can we start this without knowing the High Charts version we will support ?

Kind of yes, "Chart theme" is somewhat a generic concept, then we can try to fit as much as possible to Highcharts. Like what we designed data grid, and ag grid theme is a "fit as much as possible" theme.

**Comment by mark-tate** [comment]
Cortado Goal:
Ready for Dev by EOS
Pepper to be stakeholder
Refine ticket (breakout as needed)
Kickoff for charting

**Comment by pseys** [comment]
While button is on hold I'm picking this up and will refine the description on the Issue to clarify what is required.

**Comment by joshwooding** [comment]
@pseys and @dplsek to break this out into multiple tickets

**Comment by joshwooding** [comment]
Aug 20 - Shared progress and received feedback/advice that is being reviewed. Another call later to gather feedback.

**Comment by dplsek** [comment]
This ticket has been broken up, re-titled, and the description edited to be specific to the re-ordering of the categorical color palette.

New tickets have been created for the 'broken up' parts previously included in this ticket:
[Chart Theme: tokens](https://github.com/jpmorganchase/salt-ds/issues/4034)
[Chart Theme: documentation](https://github.com/jpmorganchase/salt-ds/issues/4035)
[Chart Theme: design examples](https://github.com/jpmorganchase/salt-ds/issues/4036)

**Comment by mark-tate** [comment]
Espresso: low priority task as focus is Buttons release, pickup if possible once Buttons work ready for release

**Comment by mark-tate** [comment]
Design review complete, docs need updating, 
how do we release this change and map the colors between old and new mappings

**Comment by origami-z** [comment]
On re-order, it will definitely be a breaking change.

I'd think - adding separate data viz series using the new order, keeping existing order for `Tag`, with the potential re-ordering in next breaking change (https://github.com/jpmorganchase/salt-ds/issues/1107)

**Comment by dplsek** [comment]
Per @origami-z confirmation that this will definitely be a breaking change, had a meeting with @pseys and @bhoppers2008 and determined the best course of action will be to explain the new order and the rationale via a blog post until we can make the update. This will allow existing consumers to use it they way it currently exists and new consumers to adopt the new proposed order:

**NEW** (corresponds with [option #4](https://www.figma.com/design/WOxL4BTkDq2ghzDVoJ0euz/Salt-(Next)-Palette-%E2%80%93-Categorical-(final)-r1?node-id=3302-4670&t=zM3wHjB3fje3HclI-1))

1. Plum
2. Jade
3. Autumn
4. Cobalt
5. Fuchsia
6. Olive
7. Indigo
8. Cider
9. Forest
10. Rose
11. Aqua
12. Salmon
13. Ocean
14. Citrine
15. Slate
16. Fur
17. Lavender
18. Lime
19. Violet
20. Smoke

**Comment by origami-z** [comment]
> explain the new order and the rationale via a blog post until we can make the update

A blog would be good to explain the rationale, but won't necessarily solve the adoption and transition problem. With the new order, most teams would need to implement sequence similar to our categorical-1/2/3. And so far, we don't know when the next breaking change is.

I would suggest we add a new sequence (maybe with 'data-viz' prefix), so we can point others to it when implementing charts. We can make it clear that it's different order than categorical, which needs to be handled with caution (e.g. when used together with tag). With the new sequence, we may also consider whether 20 or 40 makes sense to be baked in, and/or other discussions (e.g. feedback from Pepper around 500 being not vibrant enough)

**Comment by mark-tate** [comment]
Revised Goal: article published by EOS

**Comment by mark-tate** [comment]
Blog written/in-hand and will post this week (internal only)
