### ISSUE TITLE
Salt site work: Site IA review, Wireframe

### ISSUE THREAD

**Issue by honey-chang** [jpmorganchase/salt-ds#3947]
Site IA Review:
- Get the site IA reviewed by the content team.

Wireframe:
- Create wireframes to check the structure of the site.

**Comment by origami-z** [comment]
Aug 12 - pushed to next sprint, no content review

**Comment by honey-chang** [comment]
Doppio goal: Revise Site IA based on user research and competitor analysis. 
_The content team review is planned for Espresso due to limited work resources in the content team._

**Comment by joshwooding** [comment]
@honey-chang to split out content review into a new issue
