### ISSUE TITLE
Add onClose and enableAddTab to SALT Tabs

### ISSUE THREAD

**Issue by kingszi** [jpmorganchase/salt-ds#3955]
### Area

UI Components

### The problem

I would like to request the features onClose and enableAddTab that exist in the UITK Tabs. I'm aware that the SALT Tabs is still a lab component and we have a workaround, but it is not ADA compliant and would appreciate if this feature could be added down the line.

### The solution

As explained above

### Alternatives and examples

unable to add a photo, but I mean the example under the 'Controlled' section on the UITK Tabs component page.

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Hi, thanks for the feedback. I'll close this as we have the requirements in our backlog already:

https://github.com/jpmorganchase/salt-ds/issues/2396
https://github.com/jpmorganchase/salt-ds/issues/2400

Please follow those issues for any updates.

Thanks,
Josh
