### ISSUE TITLE
Checkbox without visible label alignment and documentation

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3961]
### Area

UI Components, Documentation

### The problem

When Checkbox is used without any `label` (e.g. custom cell in a data grid), checkbox is not vertically center aligned, due to 
https://github.com/jpmorganchase/salt-ds/blob/5668b079203873a5889fac659007868b53e23196/packages/core/src/checkbox/Checkbox.css#L28

### The solution

- document relevant guideline around label-less checkbox
- find a solution to address alignment

### Alternatives and examples

-

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
@bhoppers2008 to look to see if we have the same problem in Figma

**Comment by bhoppers2008** [comment]
Figma updates made to all libraries; merged and ready to publish. @joshwooding has made updates in code; PR in review.
