### ISSUE TITLE
Research for Foundations portion of site uplift 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#3962]
### - Desk research
- Define: What are "Foundations"? 
- Define: Scope for project 
- External Salt site Foundations pages analysis 
### - Competitor research 
- Competitor Foundations Page structure examples 
### - Conduct 1:1 User Interviews 
- DXD Designers
- Key Insights 

[Figma Link ](https://www.figma.com/design/VM7ZcMuVoGhYkyMSbfPc6T/Amrita-Foundations-Site-Uplift%3A-Working-File!?m=auto&node-id=9-27&t=dKOT1tjzUMxAObyk-1)

**Comment by origami-z** [comment]
Aug 12 - on track, interview on going

**Comment by joshwooding** [comment]
Aug 14 - conducted the first interview, will have done 5 by EOW. Will start working on the report.

**Comment by joshwooding** [comment]
Research has been completed for now, further work will continue in ...
