### ISSUE TITLE
Add an example of an expand and collapse all button for accordions

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#3965]
### Area

Website

### The problem

.

### The solution

.

### Alternatives and examples

.

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
This feels more asking for controlled example #3250 ..?

**Comment by joshwooding** [comment]
> This feels more asking for controlled example #3250 ..?

Yeah, The controlled example can be this. But since this was a specific ask it's good to document it.
