### ISSUE TITLE
Figma prototype bug - Button 

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#3977]
Bug reported by a user on teams.

Issue: when an overlay has been opened the 'Active' state on the buttons remains even when the overlay has been closed. This is likely because the 'Active' state hasn't been looped back around to the 'Default' state. Prototype [link](https://www.figma.com/proto/1Fc3jd1queM0PZA2cAUZlk/Tree-SALT-Example?page-id=0%3A1&node-id=1-11182&viewport=1783%2C1095%2C0.84&t=DLBVcd9em9d3WR5G-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1%3A11182&show-proto-sidebar=1).

**Comment by bhoppers2008** [comment]
@navkaur76  where in the prototype can the issue be seen?

**Comment by bhoppers2008** [comment]
A long standing [Figma bug](https://forum.figma.com/t/hover-state-doesnt-reset/3556/58). Salt can't fix.

Have provided a working alternative solution and fixed some bugs in the Light/Dark library Dialog components.
