### ISSUE TITLE
Documenting the emoji usage for prop names in Figma Salt Next

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3982]
Accordion, Banner, Button bar and Pill currently use emojis in their prop descriptions. We should create a standard approach for this going forward to ensure that we are consistent.

**Comment by yunjungyeh** [comment]
Goal: capture the usage of the emojis in a confluence page - the why how which emojis, - and add to release announcement that we are updating the props with emojis.

update can be done later

**Comment by mark-tate** [comment]
Galao Goal: complete by end of wk1, published to internal site

**Comment by mark-tate** [comment]
time to be scheduled before next standup

**Comment by yunjungyeh** [comment]
Tue 8 Oct - Created #4274 Emoji usage in Salt Next - Validate the potential improvement as further tasks
