### ISSUE TITLE
Remove the unnecessary Characteristics QA in Figma Salt Next

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#3991]
To remove unnecessary Characteristics QA in Salt NEXT library

**Comment by joshwooding** [comment]
Aug 20 - Blocked by the current release

**Comment by yunjungyeh** [comment]
Fri 23 Aug - Updated and merged
- Avatar
- Calendar
- Card
- Dialog
- Drawer
- File Drop Zone
- Link
- List Box
- Menu
- Navigation Item
- Overlay
- Pagination
- Panel
- Pill
- Progress
- Scrim
- Segmented Button Group
- Spinner
- Switch
- Tabs
- Toggle Button
- Toast
- Tooltip
- 🅿 App Header
- 🅿 Metric
