### ISSUE TITLE
Review HD Compact definition in Data Grid and beyond

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3996]
We have [HD Compact](https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples#hd-compact) for ag grid theme, and it has mixed definition of sizing and spacing, e.g. country symbols needs to be on base size height, but button needs to have full row height (base size + spacing 50).

Stretch goal - Identify definition of "compact", and see whether other densities can be applied

**Comment by joshwooding** [comment]
Aug 20 - Call to be scheduled by @navkaur76

**Comment by bhoppers2008** [comment]
Agreement made to maintain reduced base height (visually) in compact grid + strategy for @navkaur76  to implement.
Nested lists considered a different context to be addressed in a separate piece of work. (@mark-tate @origami-z @joshwooding separate issue to be tracked).
