### ISSUE TITLE
File Upload Pattern Design

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#3998]
Following pattern framework criteria the scope as follows:
- [x] Create pattern site page for review 
- [x] Define if Figma sticker component or example is required. (Or both if the case)

**Comment by ivan-calderon** [comment]
@bhoppers2008 the the [file upload pattern site](https://www.figma.com/design/RiNQBa5ctbNCQaPAPqL8D7/File-upload-pattern?node-id=1-96&t=nme1SLVxrfXf5CPS-1) page is ready for review.

**Comment by mark-tate** [comment]
Frappe Goal: Publish pattern to site using Static List

**Comment by bhoppers2008** [comment]
Ben reviewing Mon 30th Sep

**Comment by mark-tate** [comment]
Ready for dev

**Comment by bhoppers2008** [comment]
Reviewed the figma file and left comments for review.

**Comment by bhoppers2008** [comment]
Reviewed. Updated. Ready for dev

**Comment by bhoppers2008** [comment]
Figma sticker outstanding. Complete in Lungo.

**Comment by ivan-calderon** [comment]
[File upload sticker branch](https://www.figma.com/design/ChsbbO7pLomT4F5H6tQyLP/branch/ExyJwUoIJEixAKFGpm9juo/Salt-(Next)-Components-%26-Patterns?m=auto&node-id=45688-30085&t=fhy7O45Jn3MxoIJD-1) reviewed with @yunjungyeh. QA to be performed yet.

**Comment by dplsek** [comment]
@ivan-calderon completed design and stickers.

Closing this ticket and @joshwooding can create a new one for the dev portion.
