### ISSUE TITLE
Review Dialog guidance now that button and header block work is decided

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#4020]
Review our dialog guidance now that #3325, #3326 and #3839 is decided.

This might include changes to the component and/or documentation.

**Comment by mark-tate** [comment]
Due to capacity, we are extending this work by 1 sprint, so this should be completed for Espresso

**Comment by mark-tate** [comment]
Espresso Goal: wk1 get to a state, when Ben can review wk2

**Comment by mark-tate** [comment]
Frappe Goal: Guidance finalised by EOS and published alongside Header block by EOS

**Comment by mark-tate** [comment]
@navkaur76 to split into 2 issues

**Comment by navkaur76** [comment]
Closing this issue and instead splitting the work out to be tracked via the following separate issues: #4171 , #4172 , #4173 , #4174
