### ISSUE TITLE
Update Tabs component in Salt and Salt Next Figma libraries

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#4021]

**Comment by bhoppers2008** [comment]
Changes are done and merged. Needs to be published.

**Comment by mark-tate** [comment]
@ivan-calderon is this complete, can we close?

**Comment by ivan-calderon** [comment]
Completed. Branches as follow:

- [Tabs Figma branch (Next)](https://www.figma.com/design/ChsbbO7pLomT4F5H6tQyLP/branch/A0Y1cqgmm5jFghjdcCR29U/Salt-(Next)-Components-%26-Patterns?m=auto&node-id=24771-47476&t=6W2MeRUPvnzNj9UC-1)
- [Tabs Figma branch (Light)](https://www.figma.com/design/7KgRuAqrlNM8pYSMRthbjt/branch/MXhDPAjboNg9E6083LJUqm/Salt-Light-Components?m=auto&node-id=31558-2153&t=sPE3XPjclYtvmyEd-1)
- [Tabs Figma branch (Dark)](https://www.figma.com/design/14t5w7BuWParQh6AAnVP0C/branch/5XvJQhrYSVbICisbFqkGKt/Salt-Dark-Components?m=auto&node-id=5457-78514&t=VVdei9aKl6xodwaK-1)
