### ISSUE TITLE
Document relationship between status and readonly / disabled

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4029]
There are a few back and forth on when should status (icon) be visible when a component is readonly and disabled. We landed on 

- disabled: don't show status
- readonly: show status

This can go under About > Glossary before finding a better home

Some relevant wording

> Rationale is based on accessibility. If something is disabled there is no need for it to be 'visible' in the UI–it's irrelevant to a workflow. That contradicts 'status' which is very relevant to a workflow. In contrast, read-only is relevant information/data that i can't control but which is applicable to the flow. It needs to meet accessibility requirements. It's appropriate to therefore allow that state to communicate status if required as well.

**Comment by mark-tate** [comment]
Galao Goal: to be defined/published

**Comment by mark-tate** [comment]
Latte Goal: Ben/Amrita to draft a definition

**Comment by dplsek** [comment]
Extending into Lungo pending review with @bhoppers2008 @amritadesmet

**Comment by amritadesmet** [comment]
**Update:** Created PR #4348 

If this definition needs edits or anchor links to a different part of the site, let me know. @bhoppers2008 @origami-z 

**Status icon visibility**

For disabled components, status icons are not displayed. This approach is based on accessibility principles, as disabled elements don't require visibility in the UI.

In contrast, read-only components display status icons. These elements contain relevant information applicable to the workflow. Displaying status icons ensures accessibility and communicates necessary information.

**Comment by mark-tate** [comment]
Lungo Goal: published this sprint

**Comment by bhoppers2008** [comment]
@mark-tate Comment added to #4348 for @amritadesmet @jake-costa to update.

**Comment by amritadesmet** [comment]
**Update**: Had call with @jake-costa to summarize @bhoppers2008 's new descriptions. 

**Next step:** Review + merge

**Comment by amritadesmet** [comment]
Squashed & merged
