### ISSUE TITLE
Capture Detailed Component Usage Metric

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4040]
Enhance metric capture to support product OKR (migrate from UITK -> Salt)

**Comment by mark-tate** [comment]
Priority for Espresso

**Comment by mark-tate** [comment]
Espresso Goal: Priority goal after Button release, has to be started ASAP..
the sooner we do it, the better the quality of our OKR

**Comment by origami-z** [comment]
Sep 3 - started some query using Source graph, while waiting for button updates

**Comment by mark-tate** [comment]
Frappe Goal: verify the data is accurate before publishing

**Comment by origami-z** [comment]
Summary of work
- Scripts to get number of imports for Salt and UITK using SourceGraph (`managed-api-data-convertor` repo), with aggregated summary like ManagedAPI data
    - SourceGraph result is semi-fluctuating (potentially due to BitBucket server stability), so would be good to take result based on average per month basis
- Excel file created (Teams / General / Salt / Metrics ) to capture aggregated summary by LOB
