### ISSUE TITLE
Write a New Joiner Blog 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4042]
### **Salt Team Onboarding Experience from a New Joiner's point of view** 

_Brief: If you could note down your experience of the onboarding process within DXD and Salt team over the next few weeks, which can be used to convert into a short blog piece that will be published to our internal site!_

**Blog outline:** 
- Personal introduction + Overview of onboarding experience
- What worked 
- What didn't work 
- How to improve the experience 
- Key takeaways from onboarding 
- Resource suggestions based on the team's recommendations + own suggestions (reading, podcasts, learning, help contacts)

**Comment by amritadesmet** [comment]
**Feedback**: Received from Paul + implemented 

**Status:** Final draft is ready

**Next Steps:** Publishing is _**on hold**_ until the Modem blog deprecation is reorganized on go/engineer or an alternative place is found

**Comment by origami-z** [comment]
Maybe just add a blog like the button blog on Salt internal site?

**Comment by amritadesmet** [comment]
Discussed this with Mark yesterday - The content of this blog post is unrelated to direct delivery work + the release so on hold for now.

**Comment by amritadesmet** [comment]
Discussed with Mark - Closing this as on hold where posts will go + unrelated to current delivery work
