### ISSUE TITLE
Write "Setting up Figma libraries" blog 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4043]
### **How to set up your Salt Figma Libraries - Written by a New Joiner** 

**Blog outline + with images:** 

- Setting up Salt libraries
- Enabling Salt libraries 
- Setting up custom Salt plug-ins

**Comment by origami-z** [comment]
For first two points, can we make the getting started guide updated?

**Comment by amritadesmet** [comment]
Temporary short term solution until Getting Started content and Onboarding content is published on new site.

**Comment by amritadesmet** [comment]
Discussed with Mark - Closing this as on hold where posts will go + unrelated to current delivery work
