### ISSUE TITLE
Iconography foundation page

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4048]
```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/4316
- [x] Update external site Iconography docs with new content
```

**Comment by amritadesmet** [comment]
- Outline written content for Legacy + Next
- Align with leads on included content + definitions 
- Align on grouping categories for Icons 
- Lo-fi mockups for page 


To be started in Galao Sprint

**Comment by mark-tate** [comment]
Lungo Goal: publish to site and close ticket

**Comment by amritadesmet** [comment]
**31 Oct Update:** Created PR #4356 

**Next Step:** Will ask help from Dev to - 
- Insert new images
- Insert all country symbols component
- Add in the scaling component for icons + country symbols from the Scale foundation page

**Comment by amritadesmet** [comment]
**Next steps:** Pending upload new images on GH

**Comment by mark-tate** [comment]
Macc Goal: PR Open / Publish page

**Comment by amritadesmet** [comment]
**Update:** Waiting for PR #4391 to be ticked and merged

**Comment by amritadesmet** [comment]
PR squashed and merged
