### ISSUE TITLE
Dialog component not rendering correctly on Safari

### ISSUE THREAD

**Issue by maria-mcparland** [jpmorganchase/salt-ds#4066]
### Package name(s)

Core (@salt-ds/core)

### Package version(s)

    "@salt-ds/core": "^1.35.0",

### Description

On Safari the DialogContent element is rendering too small. You can see this on the documentation examples. 

Safari cuts out the text in DialogContent:

![safari](https://github.com/user-attachments/assets/eef8a7af-3837-4898-b776-2d597857c179)

Chrome renders correctly:
<img width="966" alt="chrome" src="https://github.com/user-attachments/assets/868ab76a-6872-4e94-b805-7872fc919772">

### Steps to reproduce

Open any example on [https://www.saltdesignsystem.com/salt/components/dialog/examples#default](https://www.saltdesignsystem.com/salt/components/dialog/examples#default) in Safari and do the same in Chrome.

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [ ] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
@tomhazledine FYI

**Comment by mark-tate** [comment]
Frappe Goal: fixed as part of wider Dialog changes
