### ISSUE TITLE
Date Picker example shows controlled/uncontrolled switch warning

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4069]
`const [selectedDate, setSelectedDate] = useState(undefined)` will trigger controlled/uncontrolled switch warning for 

```
<DatePicker
        selectedDate={selectedDate}
```

https://www.saltdesignsystem.com/salt/components/date-picker/examples#with-validation

**Comment by mark-tate** [comment]
This has been fixed in labs and is now a release candidate, we welcome feedback so we can move datepicker to Core 

Please refer to #4096
