### ISSUE TITLE
v1.35 causing testing errors with Dropdown and React Testing Library

### ISSUE THREAD

**Issue by jasonseminara** [jpmorganchase/salt-ds#4074]
### Package name(s)

Core (@salt-ds/core), Icons (@salt-ds/icons), Theme (@salt-ds/theme)

### Package version(s)

@salt-ds/core: 1.35.0
@salt-ds/icons: 1.12.1
@salt-ds/theme: 1.21.0

### Description

I upgraded the above versions in our `package.json`. I then ran `npm i`.

I have this component:

   // DemoFormField.tsx
    import {
      Dropdown,
      FormField,
      FormFieldLabel,
    } from '@salt-ds/core';        

    export function DemoFormField(){
      return
        <FormField>
            <FormFieldLabel>Demo</FormFieldLabel>
            <Dropdown
              multiselect
              selected={...}
              variant="secondary"
              onSelectionChange={(_, value) => console.log(value)}
            >
             {/* options */}
            </Dropdown>
          </FormField>
    }

Running `nx test <project-name>` causes an error in our form fields:

`TypeError: activeElement.scrollIntoView is not a function`

      144 |     );
      145 |     const myDropdown = screen.getByRole('combobox', { name: 'Demo' });
    > 146 |     await user.click(myDropdown );`

### Steps to reproduce

1. Upgrade these three packages in your project: 
   - @salt-ds/core: 1.35.0
   - @salt-ds/icons: 1.12.1
   - @salt-ds/theme: 1.21.0
 2. Run a test where you click on a `<Dropdown multiselect />`
 3. Observe an error in your test: `TypeError: activeElement.scrollIntoView is not a function`
 

### Expected behavior

I expected the tests to pass as they did in `@salt-ds/core@1.30.0`

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by wwwzwbz** [comment]
r u using jest and Create React App for testing? If so, maybe you can try add:
`Element.prototype.scrollIntoView = jest.fn();`
in you `setupTests.js` file

**Comment by joshwooding** [comment]
As @wwwzwbz, this is probably due to JSDOM being used, which doesn't support scrollIntoView https://github.com/jsdom/jsdom/issues/1695#issuecomment-449931788

You can use the solution above or look in the issue on the JSDOM repo for other solutions.

**Comment by jasonseminara** [comment]
Thank you, it worked perfectly.
