### ISSUE TITLE
Dates before min and after max are not disabled in Calendar

### ISSUE THREAD

**Issue by ujjavalsinha** [jpmorganchase/salt-ds#4090]
### Latest version

- [X] I have tested the latest version

### Description

Dates before min date and after max date are not disabled. User is able to click on those dates (though change event is not being triggered).

Can the dates, after max date and before min date,  in the same month, be disabled too ? 

### Steps to reproduce

1. Render Calendar component from @salt-ds/lab.
2. Pass max and min dates to the component as props.
3. Click on the Calendar input, and you will see that the dates that are after max date are also enabled and user can click on it(though change event is not triggered but the dates should ideally be disabled).

### Expected behavior

Dates that are after max and before min date prop passed to Calendar, in the same month, should be disabled.

### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

@salt-ds/lab@1.0.0-alpha.51 

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
@ujjavalsinha please update your question with actual package version, `npm list @salt-ds/lab` may help.

**Comment by ujjavalsinha** [comment]
Is team already working on this ?

**Comment by mark-tate** [comment]
Yes, it’s been merged to Labs and will be in our next release. Although remember Labs is not a stable release, so we will continue to refine until we get confirmation from folks that the api is stable and fit for production use. Can you feedback after the release and let us know your feedback.

**Comment by ujjavalsinha** [comment]
> Yes, it’s been merged to Labs and will be in our next release. Although remember Labs is not a stable release, so we will continue to refine until we get confirmation from folks that the api is stable and fit for production use. Can you feedback after the release and let us know your feedback.

Thank you very much for resolving this. 
Yes sure, once its released, will provide feedback. May I know when the next release will be?

**Comment by mark-tate** [comment]
https://storybook.saltdesignsystem.com/?path=/story/lab-calendar--min-max-date

now released and test added to check disabled dates cannot be selected to ensure no further regressions
