### ISSUE TITLE
Site Styles - common re-usable styling required by all content

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#4102]
Frappe Goals: create lo-fidelity design of components and home page and then use this to define the site foundations.
ie. spacing, typography and page sizes

**Comment by mark-tate** [comment]
Goal: shared by EOS with team

**Comment by mark-tate** [comment]
Galao Goal: create an editorial spec by EOS without any dependencies on Mosaic or Salt site

**Comment by honey-chang** [comment]
General style recommendation is done.
Galao Goal: Aiming to finish Markdown type ramp mapping, applying styles to site templates.

**Comment by honey-chang** [comment]
Site styles ready to share [Figma file](https://www.figma.com/design/DSTvHKhDVyUria4ganC62O/Salt-site-style?node-id=90-11922&t=mvs9pncRIJXnSkJw-1)

**Comment by mark-tate** [comment]
Completed design work, needs review before ready-for-dev
