### ISSUE TITLE
DatePicker docs

### ISSUE THREAD

**Issue by mark-tate** [jpmorganchase/salt-ds#4103]
Write/publish the Documentation for DatePicker, DateInput and Calendar

**Comment by mark-tate** [comment]
Goal: published first draft by EOS

**Comment by ivan-calderon** [comment]
Link to [Date picker docs](https://www.figma.com/design/iVb153RCmU5R7uvZ3ySPoR/Date-Picker?node-id=2056-27984) for reference.
