### ISSUE TITLE
Purpose of Foundations IA 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4108]
**Objective:** Clarify content and IA of Foundations prior to designing pages 

- Purpose of Foundations 
- Objectives + Goals of Foundations 
- Type of content / information level within Foundations 
- Site IA: Where does Themes go? 
- Site IA: Where do Design Tokens go?
- Propose a Foundations IA 

**Frappe Goal:** Achieve alignment with leads on proposed Foundations IA 

[Figjam link ](https://www.figma.com/board/hTDDJkBd4nypHIshf4CuaG/Salt-Internal-Site-IA?node-id=0-1&t=idcUh7VU1xIBT5Ym-1)

**Comment by amritadesmet** [comment]
**Update:** Input received from Paul + Ben + Josh 

**Foundations IA key changes:** 
- Align page titles to match Foundation names in code 
- Categorize certain Foundations into groups 
- Consolidate smaller Foundation pages into others (i.e. Accent + Opacity into Color, Scale into Size) 
- Introduce Corner radius

**Comment by amritadesmet** [comment]
EOS Review update: Shared Figma link with the team for feedback + questions

**Comment by mark-tate** [comment]
Published in Frappe
