### ISSUE TITLE
Simplify Salt (Next) Style library Figma variable collections

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4113]
- Change 'Foundation: Typography' to just 'Typography'
- 'Move Foundation: Shadow' number variables to Density – this will create the potential to apply density to shadows in the future if required
- Link Shadow 'effects' to new 'Shadow' values in Density
- Remove 'Foundation: Shadow' collection from variables

**Comment by pseys** [comment]
Changes have been made within a branch. Awaiting the 16 September release before merging the branch to main and publishing the changes.

**Comment by mark-tate** [comment]
Frappe Goal: merged by EOS

**Comment by pseys** [comment]
Changes merged, ready to publish.

**Comment by mark-tate** [comment]
ready to publish

**Comment by pseys** [comment]
Changes published. Release note added to confluence.
