### ISSUE TITLE
Update Figma libraries to match AG Grid characteristic tokens

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4115]
Follow on to [Ag grid theme copy cell background color is flipped #3922](https://github.com/jpmorganchase/salt-ds/issues/3922). 

Salt Figma libraries need to be updated to include the 'highlight' tokens used in AG Grid copy cell feature.

| Characteristic | Theme | Palette | Foundation | Foundation (Fade) |
|--|--|--|--|--|
| `--salt-overlayable-background-highlight` | **Next** | `--salt-palette-alpha` | `--salt-color-black-30a` | |
| | | | `--salt-color-white-30a` | |
| | **Legacy** | `--salt-palette-neutral-highlight` | `--salt-color-black-fade-background-highlight` | `--salt-color-black` + `--salt-opacity-25` |
| |  |  | `--salt-color-white-fade-background-highlight` | `--salt-color-white` + `--salt-opacity-25` |

**Comment by mark-tate** [comment]
Frappe Goal: published by EOS

**Comment by pseys** [comment]
`overlayable-background-highlight`  added to Salt (Next) Styles library. The change has been merged and is ready to be publish.

**Comment by pseys** [comment]
New token added to Salt Light and Dark Figma libraries. Changes have been merged and are ready to publish.

**Comment by pseys** [comment]
All style libraries have been published: 
- Salt (Next) Style Library
- Salt Light Mode
- Salt Dark Mode

Release notes added to confluence.
