### ISSUE TITLE
Ag grid theme `editable-cell` shouldn't set text align to right

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4141]
### Latest version

- [X] I have tested the latest version

### Description

It should be part of `.numeric-cell` not `.editable-cell`

### Steps to reproduce

Inspect example - https://www.saltdesignsystem.com/salt/components/ag-grid-theme/examples#variants

### Package name(s)

AG Grid Theme (@salt-ds/ag-grid-theme)

### Package version(s)

2.1.0

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
will be released in next release
