### ISSUE TITLE
LazyCountrySymbol `sharp` prop does nothing

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4161]
### Latest version

- [X] I have tested the latest version

### Description

`< LazyCountrySymbol sharp code="AD" />` doesn't not show sharp variant

### Steps to reproduce

-

### Package name(s)

@salt-ds/countries

### Package version(s)

`@salt-ds/countries@1.4.0`

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Related #4217

**Comment by origami-z** [comment]
to be released
