### ISSUE TITLE
Header Block pattern

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#4171]
Design goal: draft a header block pattern by EOS. Likely overlaps into next sprint. Also re-align the figma component to remain as a pattern stickersheet, rather than it's own component in: 

- [x] Salt Next component library
- [x] Salt Light component library (current)
- [x] Salt Dark component library (current)
- [ ] Figma guide

**Comment by mark-tate** [comment]
Galao Goal: design review by end of wk1

We will bring in remaining work as and when we start working on them

**Comment by mark-tate** [comment]
Latte Goal: page needs publishing, ready to go, review during sprint, maybe bumped to Lungo

**Comment by bhoppers2008** [comment]
No work to happen beyond pushing dialog and overlay header to labs in Latte. Updates to header block pattern page to be updated for core in Lungo sprint.

**Comment by mark-tate** [comment]
Lungo Goal: no dev capacity

**Comment by bhoppers2008** [comment]
Moved to Macchiato sprint. No capacity in Lungo. @navkaur76 to resume work after holiday.

**Comment by mark-tate** [comment]
Macc Goal: Kickoff planned to align the remaining work

**Comment by bhoppers2008** [comment]
Pattern page
