### ISSUE TITLE
Review button bar component and pattern guidance

### ISSUE THREAD

**Issue by navkaur76** [jpmorganchase/salt-ds#4174]
Review button bar pattern site guidance (and examples), and update to reflect amended stance on ordering of buttons. Also consider the recent button work. 

Figma work to be done (in both Next + Legacy):

- Add new button bar set with updated styling and button ordering
- Update pattern page examples and guidance. Add a note at the end of the page for option to use solid neutral button as an alternative secondary action (for MTK)
- Implement deprecation as component set

@bhoppers2008 to address #3933 for any pending updates to be made in Light/Dark libraries

**Comment by mark-tate** [comment]
Latte Goal: complete, requires review by EOS

**Comment by bhoppers2008** [comment]
No work to happen beyond pushing dialog header to labs in Latte. Updates to dialog core examples and guidance and button bar pattern page to be updated for core in Lungo sprint.

**Comment by bhoppers2008** [comment]
Moved to Macchiato sprint. No capacity in Lungo. @navkaur76 can resume work when she returns from holiday.

**Comment by yunjungyeh** [comment]
discussed progress/plan with @navkaur76 and the Lungo goal will be: 

1. Sticker in Light/Dark/Next
2. design/content for site updates ready for dev.

This is also required to be done for dialog works #4172 & #4377

**Comment by mark-tate** [comment]
Macc Goal: part of the Header block kickoff

**Comment by mark-tate** [comment]
Mocca Goal: release by end of wk1

**Comment by bhoppers2008** [comment]
Figma merged (to be published) and pattern page done.
