### ISSUE TITLE
Country Symbol CSS as background not bundled by webpack

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4184]
I'm trying to use country symbol via [CSS background](https://www.saltdesignsystem.com/salt/components/country-symbol/examples#css-background-image), i have below imports

```
import '@salt-ds/countries/saltCountries.css'
import '@salt-ds/countries/saltSharpCountries.css'
```

Above CSS is not getting bundled in my app, which i suspect is to do with [webpack treeshaking](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects)

https://github.com/jpmorganchase/salt-ds/blob/39277e0ad8ad4d28a34e4c2883fdb947d4717f57/packages/countries/package.json#L15

The change was originally made in #1764, which needs further testing of the impact

Source: SO Question 91530

---

One potential workaround: import country symbol CSS in CSS files.

**Comment by mark-tate** [comment]
related #4217

**Comment by mark-tate** [comment]
Lungo Goal: scope work by EOS

**Comment by origami-z** [comment]
No dev capacity, push out a sprint

**Comment by mark-tate** [comment]
red eye: fixed by eos if no other priority surfaces

**Comment by joshwooding** [comment]
The easiest thing to do is to add back the *.css sideEffects. Webpack does have a quirk about tree-shaking CSS files but typically webpack configs enable sideEffects via the style-loader rule. I'm guessing in this case the custom webpack config didn't do this. Adding them back shouldn't negatively affect other scenarios and minimizes error.
