### ISSUE TITLE
Define solution to resolve button requirement for System Status

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4188]
**Description**
Currently the System Status component is misusing sentiment buttons in order to provide inline actions. Salt provides guidance that sentiment buttons should be used/ considered independantly of status (i.e., just because an 'error' status is used, does not mean a 'negative' sentiment button is the correct choice).

Furthermore, two problems exist:

1. In current theme, sentiment solid buttons are not the same color as the status background.
2. In Next theme, status is currently not wired up to accent palette group in the same way that sentiment is wired up to accent. This means in Ligh/Dark Teal modes, teal buttons are displayed on the Info System Status.

**Requirement**
Identify a holistic solution which enables actions to be displayed inline within the System Status component and doesn't conflict with our guidance on use of sentiment buttons relative to status.

**Stakeholder**
Global banking/ Pepper pattern library.

**Goal**
The goal of this issue is to agree a written proposition that we can confidently move into design and development.

**Comment by origami-z** [comment]
Scope to define before thinking about visual implementation (notes for myself)

- Where; can/can't 
    - used within certain type of component? (e.g. system banner, grid)
    - with characteristics? (e.g. yes for status, never for sentiment, variant? appearance?) 
- What styling options needs to be "concerned" / designed around? (e.g. mode, accent, anything else?)
- What; is Button the only component will have this problem? Any other potential "nesting" / inline interactive problem?

**Comment by dplsek** [comment]
[Salt Next](https://www.figma.com/design/YVs0akocogiev3kZuqKZDW/System-Status?node-id=208-3758&t=CCcLypr5V8bH5N9d-1) design proposal

[Salt Current](https://www.figma.com/design/7KgRuAqrlNM8pYSMRthbjt/branch/yI0LKEU93sCWgeK6uIbeXH/Salt-Light-Components?m=auto&node-id=33139-1233&t=H5ElkOHmDocvKjTW-1) design proposal

**Comment by mark-tate** [comment]
Proposal defined, new ticket required @bhoppers2008 @dplsek for Galao

**Comment by mark-tate** [comment]
Alpha Button added to Q4/Q1 roadmap - will be clearer by EOS

**Comment by mark-tate** [comment]
Create tickets for Alpha Button

**Comment by dplsek** [comment]
Proposed solution for [Salt Current](https://www.figma.com/design/7KgRuAqrlNM8pYSMRthbjt/branch/yI0LKEU93sCWgeK6uIbeXH/Salt-Light-Components?m=auto&node-id=33139-1233&t=0qrNutZ3VGo19n9e-1)

Proposed solution for [Salt Next](https://www.figma.com/design/YVs0akocogiev3kZuqKZDW/System-Status?node-id=479-809&t=yNWvgFRUObZskZKi-1)
