### ISSUE TITLE
Group headers in theme next are too light and don't meet contrast requirements

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#4193]
### Latest version

- [X] I have tested the latest version

### Description

![image](https://github.com/user-attachments/assets/946b2b67-4ad7-4123-aa79-690c0793f2b3)

### Steps to reproduce

https://storybook.saltdesignsystem.com/?path=/story/core-combo-box--grouped&globals=themeNext:enable

### Package name(s)

Core (@salt-ds/core)

### Package version(s)

latest

### Browser

- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [ ] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Figma spec needs to be updated
