### ISSUE TITLE
Figma update specs to use correct content color token

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4198]
Follow bug in code #4193, group header tokens should be updated to be "content" instead of "text" in all components

**Comment by mark-tate** [comment]
Galao goal: update spec

**Comment by pseys** [comment]
@ivan-calderon and I have been working on an addition to the Salt Spec Utilities library in Figma. This provides component instances for all design tokens for use within all component and pattern specs. 

If used, this will ensure all token references are accurate. It also provides us with the ability to flag deprecated or 'design only/planned' tokens. 

The component instances have been created and @ivan-calderon plans to add an issue for Next sprint to test the component instances. 

Although this issue isn't fully resolved it provides a solution to reduce the chance of this happening in future. 

@mark-tate  We may want to close this issue and add an issue to update all design specs to use the new spec utilities reference once QA is complete. 

cc @bhoppers2008 @yunjungyeh

**Comment by mark-tate** [comment]
Latte Goal: clarify what this work is

**Comment by mark-tate** [comment]
Latte Goal: complete QA by EOS and moved additional work to #4301
