### ISSUE TITLE
Tabs overflow menu shows as `object Object` instead of actual name

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4207]
### Latest version

- [X] I have tested the latest version

### Description

Tabs overflow menu item is shown as `[object Object]`

### Steps to reproduce

https://stackblitz.com/edit/salt-template-fylufz?file=App.tsx

### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

1.0.0-alpha.52

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Should be verified in #3448

**Comment by dplsek** [comment]
Progress is being made by @joshwooding @ivan-calderon ... addressing some accessibility issues with @jake-costa
