### ISSUE TITLE
Write short Foundations roadmap for internal site 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4208]
**Objective:** Foundations roadmap that we can use to communicate to the stakeholders.

**Content:** 
- Business Opportunity 
- What's changing?
- Current Status 
- Key Activities 

**Galao goal:** Draft is complete

**Comment by amritadesmet** [comment]
**EOS 14 Oct Update:** Draft written 

**Next Steps:** Review required from @pseys

**Comment by mark-tate** [comment]
Latte Goal: review required and published

**Comment by amritadesmet** [comment]
[Draft can be viewed here](https://www.figma.com/design/VM7ZcMuVoGhYkyMSbfPc6T/Foundations-Site-Uplift-2024-WIP?m=auto&node-id=2931-6459&t=tszhyMqd1Aag0WgL-1) (please make edits in additional colour or by copying original frame.)

**Comment by dplsek** [comment]
Had the Bitbucket call with @mark-tate yesterday... @amritadesmet will sync with dev on Monday to get published by EOD on internal site

**Comment by amritadesmet** [comment]
**Update:** Created a PR in Bitbucket, needs review

**Comment by mark-tate** [comment]
Lungo Goal: page to be published by EOS

**Comment by amritadesmet** [comment]
**31 Oct Update:** PR approved in Bitbucket, will be released soon

**Comment by amritadesmet** [comment]
Has been published
