### ISSUE TITLE
Content slots schedule table for planning

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#4211]
1. Create basic scheduler for newsletter releases with empty slots for content.
2. Populate slots with any known items.
```[tasklist]
### Tasks
- [x] Process diagram
- [x] Planner
```

**Comment by amritadesmet** [comment]
[Content brainstorm Figma file](https://www.figma.com/design/GvwVseZPjP9plWrX2s6iCa/Newsletter-Content-Brainstorm?node-id=0-1&t=71x8xvwy8vA0P7hF-1)

**September Update:** Amrita + Honey met with AEM a few weeks ago to discuss how to onboard if we were to use AEM. 

**Summary**

- Honey established the high-level context for the Salt team’s newsletter efforts.
- Prem provided a brief overview of DP Content’s AEM instance and how the DP Content team administers it.
- Prem showed the use-case-based variations of the new Global Communications template (featuring Salt email components).
- Amrita clarified some open questions re: the Salt use case (tracking/reporting requirements, email send vs. web needs, etc.)
- We discussed next steps for onboarding to (and exploration of) DP Content’s AEM instance.

**Open questions from AEM to think about (future consideration by the Salt team)**:

- How often will you send the newsletter (i.e., biweekly, monthly, quarterly, semiannually, annually)?
- What is your authoring model (i.e., how many people will contribute to the newsletter, how many require AEM access, etc.)?
- What is your editorial model (i.e., who will review the content before it’s published/sent, etc.)?
- What is your distribution model (i.e., will you send an email AND surface newsletters on the Salt site … and how will you promote it)?
- What is your content ownership model (i.e., who from Salt truly owns the content and the responsibility to maintain/retire it)?
- What is your content retention model (i.e., how long will you keep old newsletters before archiving them in AEM and on your site)?
- How will you measure success in AEM (i.e., authoring ease, content velocity, etc.)?
- How will you measure success for the email itself (i.e., open rates, click-through rates, etc.)?

**Comment by amritadesmet** [comment]
**Content knowledge share meeting on Tue Oct 1**

**Key Takeaways:** 

- Re-defined the content and purpose of the newsletter 
- Showcase the business value 
- Showcase upcoming features with dates (if possible) to get users excited 
- Content could tie in with releases 

**Next steps:** Yun + Amrita calendar plan for the upcoming newsletters

**Comment by yunjungyeh** [comment]
Combinations of the ideas / feedback from the knowledge share meeting / offline discussions


We should try make the newsletter effortlessly after we **have a planner and template** (as a practical short-term goal)

**Good potential topics (content blocks) we can have:**
- Business value/product related
    - e.g. share how to migrate with the consumer
    - Metrics / Charts (Mark: can be the same - consumers can see the growth etc.)
    - Showcase the coming feature (to get feedback) - 
- FAQ / What’s our hottest support
- The story (of work/challenges/behind the scene) e.g.
    - Design decision, can have multiple things tied together (e.g. why we reordering the categorical palette - key highlight from the blog etc.)
    - Date picker (e.g. design challenges/code challenges)
    - icon challenges

cc @bhoppers2008 @mark-tate @origami-z @joshwooding

**Comment by amritadesmet** [comment]
**Oct 14 Meeting w/ Mark + Ben**

- Proposal: Continue using current template for Release Notes 
- Authoring model: Byproduct on existing content creation - signposting to the work
  - Include Salt + Figma highlights and updates
  - Remove Summary section
- Format
  - Title - Salt Newsletter
  - Banner Image
  - Highlights - product related  
  - Highlight 1: New Release available - see GH changelog + Figma release notes
  - Highlight 2
  - Highlight 3
  - Highlight 4
  - Links - Github change log, release change log
- Timing: Align with the Sprint reports
- Long term: Product driven content and integrated with Figma release notes 
- Next steps: Format content + blurb from Darrin + Amrita

**Comment by yunjungyeh** [comment]
Mon 14 Oct - Highlights/decisions from the meeting with @mark-tate @bhoppers2008 
- Combine the current release letter as **Salt Newsletter** include all the product updates
- Use the latest release announcement email as the template (for the time being)
- Remove the Figma release Summary part/previous format we originally have 
- Contents are what the team are working on along the delivery, just need to decide what to include (add to confluence planner) based on the work in each sprint.
- The timing will try to align with the sprint reports
- @yunjungyeh send the emails, if OOO @bhoppers2008 will do

New format: have 4-5 Highlights, including (but not limited to):
1. **# 1 New Salt Updates Available** will have links to GitHub changelog, Figma library Release notes, (and AG theme update etc.)
2. Blogs/Articles
3. Site updates
4. Q3 team review
5. Component launch

cc @joshwooding @origami-z @pseys @dplsek
