### ISSUE TITLE
Emoji usage in Salt Next Figma libraries - Validate the potential improvement

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#4274]
further task from #3982

**Comment by mark-tate** [comment]
Macc Goal: complete by EOS

**Comment by yunjungyeh** [comment]
Wed 20 Nov - Testing done and updates applied in Next/Light/Dark Figma libraries

**Comment by yunjungyeh** [comment]
Fri 22 - [Testing plan and the results](https://www.figma.com/design/iTBhNefoudZnbCzOAtPieP/Salt-component-improvements---Naming-convention-%2F-Emoji-usage-in-properties?node-id=0-1&t=P5xPPrscRNPf828U-1)
