### ISSUE TITLE
Ag grid v32 floating filter active state

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4275]
### Description

v32 changed floating filter's "active" state to a toggle button inlined with the input (previously its indicated by an icon on the header cell)

https://www.ag-grid.com/javascript-data-grid/floating-filters/

`.ag-filter-active` is applied to the button, will need Salt support.

### Expected behavior

Visual indicator to show the filter is on

### Alternatives and examples

-

### Context

Upgrade ag grid from v31 to v32

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
Latte Goal: v32 upgrade release candidate

**Comment by origami-z** [comment]
Oct 17 - send snapshot for MTK to test, also testing in Stackblitz for v31 backwards compatibility

**Comment by origami-z** [comment]
Oct 21 : Ben to review previews in PR

**Comment by origami-z** [comment]
Oct 23 - MTK testing snapshot, visual regression changes are mostly expected code change

**Comment by origami-z** [comment]
moving into Lungo pending @bhoppers2008 review

**Comment by origami-z** [comment]
Met with Ben. We want combined approaches between PRs

1. Use toggle button active style
2. Use different filter icons, solid for active and outline for default state
3. Decrease size of HD compact "fake" toggle button to align with base height 16px

**Comment by origami-z** [comment]
To be released in #4418

**Comment by bhoppers2008** [comment]
Done and released.

**Comment by origami-z** [comment]
https://github.com/jpmorganchase/salt-ds/releases/tag/%40salt-ds%2Fag-grid-theme%402.2.0
