### ISSUE TITLE
Write blog post to announce status icon updates

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4286]
Supports #4100 

Write an explainer for the icon changes. 
- Minor tweaks to error, warning, info
- Addition of success-circle and checkmark
- Deprecation of success and step-success

**Comment by pseys** [comment]
Product announcement has been written and shared with @bhoppers2008 and @dplsek for review. Minor amends have been made and reviewed. The post is now ready to publish.

**Comment by dplsek** [comment]
In the process of being published by @bhoppers2008 ... moving to Lungo until we know otherwise
