### ISSUE TITLE
Review PUI changes

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4289]
The PUI Figma library highlights all of the changes they've made to the base Salt Next theme as well as component CSS overrides. 

- Review highlighted changes
- Identify which may be redundant in future based on backlog
- Identify potential Salt theme changes to move closer to PUI as well as highlight which changes we won't adopt
- Identify potential component changes to move closer to PIO as well as highlight which changes won't be adopted

**Comment by mark-tate** [comment]
Latte Goal: Be familiar with what they have done, what did they change ?

@pseys to refine goal

**Comment by mark-tate** [comment]
spreadsheet complete for first round of review
