### ISSUE TITLE
Refine Theme and UI schedule

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4296]
All leads to refine the theme and UI schedule and agree first tentative dates that will be presented back to leads and business library managers on Monday 21st October.

**Comment by dplsek** [comment]
Progressing but needs more discussion... extending into Lungo until we have further update from @bhoppers2008

**Comment by mark-tate** [comment]
Lungo: create tickets and sprint goals for 5 remaining sprints

**Comment by mark-tate** [comment]
Macc Goal: visibility of dates and alignment of priorities with Q4 goals

**Comment by mark-tate** [comment]
Mocca Goal: @bhoppers2008 to share with team by EOS

**Comment by pseys** [comment]
- Review completed of PUI Figma file. 
- All identified requirements have been added to a spreadsheet which has been shared with the team
- Agreed with James Sol that the spreadsheet would be reduced down to key requirements instead of component by component changes.

**Comment by mark-tate** [comment]
@bhoppers2008: this has been running since Oct, can we close it out or get it to a more of a known quantity/state ?

**Comment by mark-tate** [comment]
@bhoppers2008 to create more granular tickets
