### ISSUE TITLE
Write icon contribution guide for internal Salt site

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4300]
Currently we provide icon contribution guidance within our Figma library. This needs to be removed and replaced by a guide published on the internal site to enable link sharing and availability to all consumers. By removing it from the Figma library we simplify the designer experience when using the icon library.

**Comment by mark-tate** [comment]
Macc Goal: complete by EOS

**Comment by pseys** [comment]
@bhoppers2008 has added all images and committed the changes.

**Comment by pseys** [comment]
Content is now available on the internal site but images aren't yet displaying correctly. @mark-tate

**Comment by bhoppers2008** [comment]
Done and published.
