### ISSUE TITLE
QA Token utility Figma component 

### ISSUE THREAD

**Issue by ivan-calderon** [jpmorganchase/salt-ds#4301]
Latte goal: Complete QA of the token utility component. 

Issue tracking #4198 and #4193 issues.

**Comment by ivan-calderon** [comment]
[QA completed](https://www.figma.com/design/i8kSFpGbHIWXnv6LFvWKdU/branch/ovsZLkjsZnmAE6PxW06Za4/Salt-(Next)-Spec-Utilities?m=auto&node-id=5561-6180&t=QXUeS1eLnUI1ekKG-1) and shared with @pseys for review.

**Comment by dplsek** [comment]
@ivan-calderon completed and reviewed with @pseys for the design portion. 

Pending QA and maintenance strategy with @pseys and @bhoppers2008 which can be completed under a new ticket, which @ivan-calderon will create.
