### ISSUE TITLE
`theme-next.css` imports invalid CSS variables

### ISSUE THREAD

**Issue by liamsms** [jpmorganchase/salt-ds#4302]
### Latest version

- [X] I have tested the latest version

### Description

Some of the custom CSS variables imported by `theme-next.css` are missing a hyphen which causes Turbopack parser to fail
```
 ⨯ ModuleBuildError: ./node_modules/@salt-ds/theme/css/theme-next.css:829:86
Parsing css source code failed
> 829 |   --salt-actionable-negative-foreground-disabled: var(--salt-palette-negative-strong disabled);
```

### Steps to reproduce

1. Import theme-next.css
2. Start app using latest Next.js + Turbopack `next dev --turbo`

### Package name(s)

Theme (@salt-ds/theme)

### Package version(s)

1.23.0

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
@liamsms thanks for raising. will hotfix asap
