### ISSUE TITLE
Form Field v1

### ISSUE THREAD

**Issue by ZarkoPernar** [jpmorganchase/salt-ds#431]
Figma Link: https://www.figma.com/file/KSpYg21r69mHjXaQwWgAu3/Form-Field
___

```[tasklist]
### Released in
- [ ] Design
- [x] Dev
```

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1030
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1742
```

All versions assume support for:
- All densities
- All modes
- Accessibility considerations

 
### Version 1

1. Form label
  a. Placement: Top, Right (on left)
  b. Width: 100%
  c. Overflow: Wrap
2. States: Default, Hover, Selected, Read-only, Disabled
  a. Support for custom states (Markets’ ‘Non-default’)
3. Help text
  a. Width: 100%
  b. Overflow: Wrap
4. Focus ring support
5. Validation text: Error, Warning, Success
  a. Width: 100%
  b. Overflow: Wrap
6. Integrations: Input
  a. Activation line
  b. Variants: Primary, Secondary
  c. Validation states (inc. fill & icon Fixed): Error, Warning
7. Control child validation state

**Comment by parsakhan21** [comment]
Ben to work on up front design work. Start on Monday.

**Comment by james-nash** [comment]
11/24: Meeting today to review proposals

**Comment by parsakhan21** [comment]
1/18 - no progress yet on this; focusing on datagrid - wrap up by tomorrow

**Comment by JohannaJoergensen** [comment]
@bhoppers2008 - any updates on this?

**Comment by joshwooding** [comment]
Moved to blocked due to lack of current capacity

**Comment by joshwooding** [comment]
@joshwooding and @alycrys to review PR

**Comment by libertymayc** [comment]
@bhoppers2008 documenting CSS API for explicit use cases:

--saltFormFieldNext-width (default is 100%)
--saltInputNext-paddingLeft (should be used when embedded)
--saltInputNext-textAlign (default is left)

for custom states (e.g. Markets non default)
--saltInputNext-background
--saltInputNext-background-active
--saltInputNext-background-hover
--saltInputNext-borderColor
--saltInputNext-borderColor-active
--saltInputNext-borderColor-hover
--saltInputNext-borderColor-focused
--saltInputNext-outlineColor


*note these will change to --saltInput prefix once we deprecate the current Input and switch over to the new one :-)

**Comment by origami-z** [comment]
Figma library released
