### ISSUE TITLE
Website links don't have Salt focus ring styles

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4314]
### Latest version

- [X] I have tested the latest version

### Description

Raised in #4312, doc links are using Salt focus style

### Steps to reproduce

Tab through heading / links 

https://www.saltdesignsystem.com/salt/components/button/examples

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
This is fixed on main due to #3448

**Comment by joshwooding** [comment]
Closing this as should be fixed now
