### ISSUE TITLE
Update Pagination spec to include selected border

### ISSUE THREAD

**Issue by bhoppers2008** [jpmorganchase/salt-ds#4332]
This issue will update the selected pagination number to have a consistent visual treatment to a calendar day.

**Goal**
To get spec ready for dev.

**Related ticket**
#3758

**Comment by yunjungyeh** [comment]
Discussed with @dplsek @ivan-calderon @jake-costa to have option 3 adding the border inside.
Touch target in HD compliance to be discussed as a strategy/guidance across components.
