### ISSUE TITLE
Correct Button letterspacing in Figma

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4341]
Letterspacing for buttons in code is set to 0.6 whereas in Figma it is currently set to 0.0. This means buttons are marginally smaller in Figma than in code which could result inaccuracy between design specs and coded UIs

**Comment by mark-tate** [comment]
Lungo Goal: in Figma letter spacing is not applied to Buttons (exists in code)

**Comment by mark-tate** [comment]
Macc Goal: Ben to review, close by EOS
@pseys to close ticket once we update made

**Comment by pseys** [comment]
The component and pattern library has now been updated with the bug fix. It just needs to be published as part of the next release.

**Comment by pseys** [comment]
This has been updated in the latest release (15 November)
