### ISSUE TITLE
Update Success Icon in Code

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4347]
- Update icons (new / deprecate)
- Repoint status indicator component to new icon

This will be a new peerDep between icon version and icon

Dev work from https://github.com/jpmorganchase/salt-ds/issues/4100#issuecomment-2407007852

https://github.com/jpmorganchase/salt-ds/issues/4100#issuecomment-2371453062

**Comment by mark-tate** [comment]
Lungo Goal: complete by EOS

**Comment by origami-z** [comment]
Oct 31: PR #4364 ready for review, see https://github.com/jpmorganchase/salt-ds/pull/4364#issuecomment-2450344587 for Chromatic link to check visual regression comparisons

**Comment by mark-tate** [comment]
Macc Goal: PR up , answer Ben's questions and unblock by EOS
