### ISSUE TITLE
Figma Card Accent Left is using right bar

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4368]
Card accent=left is having right accent bar

https://www.figma.com/design/7KgRuAqrlNM8pYSMRthbjt/Salt-Light-Components?node-id=15936-6263&node-type=frame&t=0U8wxfk8YwPoguFm-0

**Comment by yunjungyeh** [comment]
Fri1 Nov - Fixed and published, replied to the email
