### ISSUE TITLE
Figma Guide plan & standard

### ISSUE THREAD

**Issue by yunjungyeh** [jpmorganchase/salt-ds#4371]
- Align with Ivan/Paul about the Guide update Plan,  
- Work with Delme & Ben P. to update the Guide Creation Standard.
- Ben P confirming and reviewing the works (1 Guide per branch - starting from Avatar & Accordion). 

Process in the future:
- When the designer has done the guide -> send it to Ben P. Ben P Update and merge

**Comment by mark-tate** [comment]
Mocca Goal: Align the guides on how to use the components with the component names

**Comment by bhoppers2008** [comment]
Ben P and Delme to review and Yun to document the standards that we apply to all new guides (for new library).

**Comment by yunjungyeh** [comment]
Thu 5 Dec - First version is done, to be reviewed with @bhoppers2008, 
(examples/screenshots to be added after the updated guides are done after new library)

**Comment by mark-tate** [comment]
Does any remaining work return to the backlog in the form of new tickets ?
Can we close this one as part of Mocha ? @yunjungyeh  @bhoppers2008

**Comment by bhoppers2008** [comment]
Reviewed with @yunjungyeh and some updates made. Further updates are out of scope until new Figma libraries are released. Can be addressed in separate ticket.
