### ISSUE TITLE
Tooltip covering first ComboBox option

### ISSUE THREAD

**Issue by kingszi** [jpmorganchase/salt-ds#4386]
### Latest version

- [X] I have tested the latest version

### Description

I am using a FormField ComboBox with a Tooltip where the tooltip is overlapping the first option of the combobox.

### Steps to reproduce

The element is structured like this:
`<FormField>
          <FormFieldLabel>{props.field.label}</FormFieldLabel>
          <Tooltip content={props.field.tooltip} placement="bottom">
            <ComboBox value={value}>
              {options?.map(option => (
                <Option value={option.label} key={option.value} id={option?.value?.replace(/\s/g, '') + 'Option'}/>
              ))}
            </ComboBox>
     </Tooltip>
 </FormField>`

### Expected behavior

Tooltip should not overlap the first option in the ComboBox.

### Package name(s)

Core (@salt-ds/core)

### Package version(s)

1.37.1

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by kingszi** [comment]
I've added both a structure and a picture but both have disappeared, if any more info is needed let me know

**Comment by origami-z** [comment]
@kingszi  can you update the question with your code please

**Comment by victorgbaye** [comment]
Hi @origami-z  I would like to work on this bug and actively contribute. Any guide or public slack?. @kingszi could you make a loom video of the bug and comment the link here.

**Comment by kingszi** [comment]
> @kingszi can you update the question with your code please

added some code to the question

**Comment by origami-z** [comment]
You can change `placement="bottom"` to other placements for the Tooltip?

Also, what's the purpose of the tooltip? If you want to add more information to the combobox, it's better to use `FormFieldHelperText` so it can be better associated to the element.

**Comment by kingszi** [comment]
> You can change `placement="bottom"` to other placements for the Tooltip?
> 
> Also, what's the purpose of the tooltip? If you want to add more information to the combobox, it's better to use `FormFieldHelperText` so it can be better associated to the element.

It's unfortunately a requirement from our business stakeholders, so I cannot change the placement or the component itself.

**Comment by origami-z** [comment]
> It's unfortunately a requirement from our business stakeholders, so I cannot change the placement or the component itself.

Unless you can provide UX related requirement or reason, this is not a bug. You asked the tooltip to display at the same place as combobox list. You may consider lower z-index of tooltip, and it will be your own customization.

And as I mentioned, you need to work out accessibility implications as well.

**Comment by kingszi** [comment]
I'm aware of the accessibility implications, as I mentioned this is not something I have control over because the requirement is set by someone else. Will try the z-index, thanks
