### ISSUE TITLE
Synthesise external Foundations test into report/blog

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4401]
Analyse external user test data for Typography + Color page

**Executive summary** of study 
* Method: why and how was it structured?
* Key takeaways: what did we learn?
* Next steps

**Macchiato EOS goal:** Data analysis complete

**Comment by amritadesmet** [comment]
**20 Nov update:** 

Figjam table WIP
Blog post WIP

**Comment by amritadesmet** [comment]
To be completed in Mocha

**Comment by mark-tate** [comment]
Mocca Goal: publish by EOS

**Comment by amritadesmet** [comment]
**28 Nov update:**

- Deck done 
- Blog done 

**Next steps:** Upload blog

**Comment by amritadesmet** [comment]
Pending review

**Comment by amritadesmet** [comment]
Blog published internally
