### ISSUE TITLE
TabsNext - overflow menu items name issue

### ISSUE THREAD

**Issue by akawanishi** [jpmorganchase/salt-ds#4415]
### Latest version

- [X] I have tested the latest version

### Description

When Tabs overflow the menu does not show appropriate tab names. This is also happening in official Salt DS website.

### Steps to reproduce

1. make screen smaller so that Tabs overflow into an overflow menu. 
2. open menu. 
3. Check out names of the menu items

### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

latest

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by joshwooding** [comment]
Duplicate of #4207. Should be fixed in https://github.com/jpmorganchase/salt-ds/releases/tag/@salt-ds/lab@1.0.0-alpha.55
