### ISSUE TITLE
Date Picker - Experimental time

### ISSUE THREAD

**Issue by akawanishi** [jpmorganchase/salt-ds#4423]
### Latest version

- [X] I have tested the latest version

### Description

Dark mode for time in experimental time Date picker has different color treatment than the date input, is this expected?
Also, the AM/PM label is being cropped.

### Steps to reproduce

check out example in Storybook
https://storybook.saltdesignsystem.com/?path=/story/lab-date-picker--with-experimental-time&globals=mode:dark;density:touch;themeNext:enable;corner:rounded

### Package name(s)

Lab (@salt-ds/lab)

### Package version(s)

latest

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by origami-z** [comment]
Features not documented on the official website is not fully ready.

`DatePickerTimeInput` hasn't gone through proper design cycles, it is there to help validate the feasibility to provide custom controls to the main Date Picker.

**Comment by mark-tate** [comment]
Create a feature request for a time support with your requirements and we can add to the backlog.

We know there are use-cases that will need time support, we wanted to build a base picker that when we added time, did not break all the other use-cases.
