### ISSUE TITLE
Border layout sticky example is misleading

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#4432]
### Related page(s)

https://www.saltdesignsystem.com/salt/components/border-layout/examples#sticky-positioning

### Kind of issue

Broken example

### Description

Sticky example is not showing how `sticky` block is actually doing, therefore teams can't really produce a nice app level set up. e.g. disable the class `.saltBorderItem-sticky` from devtool, the example doesn't change. It's likely due to the `center` styling from https://github.com/jpmorganchase/salt-ds/blob/b761b6008471eacbd414fd4f879f20f2c80c2a79/site/src/examples/border-layout/StickyPositioning.tsx#L17

Using sticky in real life below, all other regions would be scrolled. Applying `sticky` to west region will make it scroll above north region. 
 https://stackblitz.com/edit/salt-template-nj8skc?file=App.tsx 

The design advice on the documentation is valid, but implementation example needs to be fixed.

Related to SO Question 94322

### Browser

- [X] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by mark-tate** [comment]
red eye : fixed by EOS
