### ISSUE TITLE
Figma library cover design

### ISSUE THREAD

**Issue by pseys** [jpmorganchase/salt-ds#4462]
To support #4461 a new cover design for Figma files needs to be created to create consistency across Salt files and aid discoverability by consumers when searching for resources.

**Comment by pseys** [comment]
- Initial designs proposed. 
- @bhoppers2008 requested that the designs align more closely to JPM brand
- Time scheduled with @honey-chang to discuss alternate background graphics

**Comment by pseys** [comment]
Design refined. Darrin has taken on design direction. Awaiting final agreement. Once Darrin/Ben are happy I'll centralise the design and add to our libraries.

**Comment by origami-z** [comment]
need to make sure new thumbnail follows [new dimension ratio](https://help.figma.com/hc/en-us/articles/360038511413-Set-custom-thumbnails-for-files#:~:text=Thumbnail%20dimensions,-The%20exact%20dimensions&text=To%20make%20sure%20your%20thumbnails,templates%20in%20the%20right%20sidebar.)

**Comment by mark-tate** [comment]
closed by EOS mocha

**Comment by mark-tate** [comment]
@dplsek says YES, update file and then close

**Comment by dplsek** [comment]
Per @pseys we'll use status tokens to style tags as overrides until tags support status and sentiment for these cover templates.
