### ISSUE TITLE
Shadow foundation page 

### ISSUE THREAD

**Issue by amritadesmet** [jpmorganchase/salt-ds#4467]
- [x] Write new documentation 
- [ ] Update external site docs with new content 

**Mocha goal:** Complete documentation

**Comment by amritadesmet** [comment]
**Red-eye goal**: Publish onto site

**Comment by mark-tate** [comment]
Red eye goal:  publish by EOS

should communicate z-ordering and match them to component types and shadows

**Comment by origami-z** [comment]
> should communicate z-ordering and match them to component types and shadows

Talked to Amrita, z-index and shadow are different concepts, so needing to distinguish them nicely

**Comment by amritadesmet** [comment]
Z-Index will have it's own foundation page due to the content being different

**Comment by amritadesmet** [comment]
**12 Dec update:** Content ready for lead review

**Comment by mark-tate** [comment]
@pseys content ready for review

**Comment by dplsek** [comment]
@pseys has been providing feedback... will review once @amritadesmet is back. overall, progressing well.

**Comment by amritadesmet** [comment]
**17 Dec update:** Content reviewed by Darrin + Paul. Working on PR

**Comment by amritadesmet** [comment]
PR merged
