### ISSUE TITLE
Input v1

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#477]
Figma Link: @bhoppers2008 to create
___

```[tasklist]
### Released in
- [ ] Design
- [x] Dev
```

```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1742
```

All versions assume support for:
- All densities
- All modes
- Accessibility considerations

### Version 1

a. Variants: Primary, Secondary
b. States: Default, Hover, Selected, Read-only, Disabled
c. Styling: Text, Background, Activation line
d. Read-only empty marker
e. Support for custom states (Markets’ ‘Non-default’)
f. Focus ring support
g. Validation states (inc. fill & icon): Error, Warning, Success
h. Text alignment
i. Width (min width, etc?)
j. Integration with Form Field (see #431)

**Comment by parsakhan21** [comment]
May 12 - ben is working on spec; v1 tbd

**Comment by libertymayc** [comment]
CSS API for custom use cases cc @bhoppers2008 

--saltInputNext-paddingLeft (should be used when embedded)

for custom states (e.g. Markets non default)
--saltInputNext-background
--saltInputNext-background-active
--saltInputNext-background-hover
--saltInputNext-borderColor
--saltInputNext-borderColor-active
--saltInputNext-borderColor-hover
--saltInputNext-borderColor-focused
--saltInputNext-outlineColor

**Comment by parsakhan21** [comment]
june 2- v1 dev to be released today; semi figma release today - follow up with proper release when feedbck received

**Comment by origami-z** [comment]
Figma library released
