### ISSUE TITLE
Radio Button

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#479]
```[tasklist]
### Tasks
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1423
- [ ] https://github.com/jpmorganchase/salt-ds/issues/1422
```

**Comment by navkaur76** [comment]
1/26-
Kick off meeting held with component group and Ben/Josh/Paul

**Comment by joshwooding** [comment]
Some refactors, waiting for some designs on the specs:

@alycrys to add more detail

**Comment by alycrys** [comment]
Pending question: Do we want the icon to be customisable?

**Comment by joshwooding** [comment]
dev review needed
