### ISSUE TITLE
☂️ Setup v1 website build & hosting

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#510]
In order to deliver an initial Odyssey site by mid-December we need to:

- [x] #548
- [x] #547
- [x] #550
- [x] #551

Relates to: #483

**Comment by shinytoyrobots** [comment]
New dev starting soon has next.js background (right, @joshwooding?). That might be an architecture we consider. (I'm very familiar with Gatsby, and I think it's great, but next.js also seems kinda like the next step forward in some ways)

**Comment by joshwooding** [comment]
@shinytoyrobots The new dev does have a Next.js background. I think I've seen a massive uptick in Next.js usage due to Vercel and in my mind it's what we would probably use but I have nothing against Gatsby which has improved massively over the past years.

**Comment by shinytoyrobots** [comment]
We should consider search options (e.g. Algolia) fairly early in the process - because we'll want a high quality site search solution for site navigation.

**Comment by james-nash** [comment]
Removed the Storybook task (#549), as that's for post-launch

**Comment by james-nash** [comment]
Closing this as all tasks are now complete. Well done everyone!
