### ISSUE TITLE
Storybook for site components?

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#549]
Decide if/how we can use Storybook for developing / testing / reviewing site-specific components and templates and set it up

**Comment by JohannaJoergensen** [comment]
22 Nov - do we use a table layout, include a status summary overview on page? Team will look into this further

**Comment by james-nash** [comment]
Ah! @JohannaJoergensen: the above comment should go into a different issue. This issue is about setting up the tool [Storybook](https://storybook.js.org/) to catalogue any bespoke components we build in order to create the website.

Your comment relates to the actual components page in our site. However, I can't find an issue to cover that work right now. Will do a more thorough check in a moment and raise an issue if needed.

**Comment by JohannaJoergensen** [comment]
18 Jan - work in progress
