### ISSUE TITLE
Settle on a URL hostname and get the necessary DNS records setup

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#551]
Domain name has been chosen and purchased: saltdesignsystem.com

We still need DNS setup so that:

* `www.saltdesignsystem.com` points to our Cloudflare-hosted site, so that `https://www.saltdesignsystem.com/` is the canonical URL for our website.
* We should configure things so that the bare `https://saltdesignsystem.com/` (without the `www.`) is a permanent HTTP redirect to our canonical URL.

Depends on #662

**Comment by JohannaJoergensen** [comment]
Cannot be started until we have a name

**Comment by james-nash** [comment]
Closing this as URL works and site is live :-)

However, the bare domain is currently _not_ redirecting to the `www.` as it should, so I've raise issue #944 to get that fixed.
