### ISSUE TITLE
Explore Site Pages Quality (ada, performance etc)

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/salt-ds#623]
Explore using tools like Lighthouse to check for page speed, ada, broken links etc.
Is there any automation we can set up for regular checks? 

https://web.dev/measure/
https://webhint.io/

**Comment by JoanaMMoreira** [comment]
I've just noticed Docusaurus already checks for broken links: https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks

**Comment by EleanorHaproff** [comment]
PR was opened for when it was being worked on, but has been closed now this has been deprioritised https://github.com/jpmorganchase/uitk/pull/644
