### ISSUE TITLE
Finalize homepage design

### ISSUE THREAD

**Issue by shey-v** [jpmorganchase/salt-ds#677]
- [ ] Drop content into homepage design (including breakpoints)
- [ ] Ensure Rufaro is happy with the copy in situ and proof reads it, for any additional feedback
- [ ] Work on finalizing graphics and imagery for homepage
- [ ] Work with Jo to build it
- [ ] Work with Jo to add/tweak animations & effects

**Comment by JohannaJoergensen** [comment]
21 Nov - working on branding, mtg with leads scheduled - update to follow

**Comment by shey-v** [comment]
22 Nov - caught up with Rufaro this morning to discuss amended homepage copy. Working to get this into designs and send back any feedback so that Rufaro can send over final copy to Robin / James for a final sign off before handing to dev.

**Comment by james-nash** [comment]
1//24: Shey & Jo pairing up on this today
