### ISSUE TITLE
Explore search functionality in docusaurus

### ISSUE THREAD

**Issue by JoanaMMoreira** [jpmorganchase/salt-ds#689]
https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by JohannaJoergensen** [comment]
6 Feb - work in progress; found a bug; working on this

**Comment by JoanaMMoreira** [comment]
Draft PR: https://github.com/jpmorganchase/salt-ds/pull/1091
Branch: [site-search-spike](https://github.com/jpmorganchase/salt-ds/tree/site-search-spike)

For the purpose of the spike we've added offline search using [docusaurus lunr search](https://www.npmjs.com/package/docusaurus-lunr-search) which is built on top of [algolia](https://docsearch.algolia.com/), the [docusaurus recommended search tool](https://docusaurus.io/docs/search#using-algolia-docsearch). 

The search works well across the site but there is an issue when trying to search for subheadings within the docs. Subheadings  are parsed as regular text instead of titles which causes the search to link to the top of the page. This is due to our [content ](https://github.com/jpmorganchase/salt-ds/blob/main/site/docs/getting-started/developing.mdx?plain=1#L11)wrapper used in mdx files. Removing the wrapper from `mdx` files and passing it using [different methods](https://v1.mdxjs.com/guides/wrapper-customization/#using-the-wrapper-for-layout) didn't help and I believe the solution is to fix the document scanning logic provided by `docusaurus lunr search` (which possibly wouldn't even be an issue if we were to use Algolia's search out of the box.

**Comment by JoanaMMoreira** [comment]
FYI @james-nash @JohannaJoergensen I've added some notes above and closed this issue

**Comment by james-nash** [comment]
Great stuff. Thanks for writing up your findings!
