### ISSUE TITLE
Document component reference rules and update component references 

### ISSUE THREAD

**Issue by joshwooding** [jpmorganchase/salt-ds#777]
Rules:

Component names in titles should be title case e.g. Form Field, Salt Provider
Component names in technical documentation should be PascalCase e.g. FormField, SaltProvider

**Comment by james-nash** [comment]
Question for the content team: Would it make sense to also require technical documentation to format the PascalCase component names in a monospace font (i.e. wrap them in backticks in markdown or `<code>` element in HTML). E.g. `FormField`, `SaltProvider`? Might help further differentiate the different usages.
