### ISSUE TITLE
Capcake fixathon screenshots

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#828]
Just a temporary holding pen for screenshots and stuff.

**Comment by c1rrus** [comment]
Formatting is off on Android Wear browser 😜

![20221208_114735](https://user-images.githubusercontent.com/358435/206439493-c9ff7bd7-731b-45d3-8f47-314014e7879b.jpg)
![20221208_114808](https://user-images.githubusercontent.com/358435/206439500-0c4e8781-a40a-40f6-89e9-b4be11dbd774.jpg)
