### ISSUE TITLE
Set up internal url alias and redirect to design system website

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#850]
Can we configure "design.jpmorgan.com/salt" to exist, and to redirect to the saltdesignsystem.com site? The system needs to have some presence within the internal jpm IA.

**Comment by shinytoyrobots** [comment]
This should also include go/salt

**Comment by james-nash** [comment]
Unfortunately, `go/salt` is already taken for something completely different. However, I have already setup `go/salt-ds` (and will update it once our new domain goes live)

**Comment by JohannaJoergensen** [comment]
19 Dec - James to reach out to Neil for setup
