### ISSUE TITLE
Fix codeblock a11y issues

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#858]
It seems the code blocks that Docusaurus renders when you use triple backticks in markdown have a couple of a11y issues:

* The add `tabindex` to the `<pre>` element, making it focusable. Since it's not an interactive element, it shouldn't be there
    * Though, it might be worth doing a little digging into _why_ they did that. That attribute can't have just appeared by accident, so there must have been some kind of motivation for it
* The copy button within always uses the same, generic label text. For pages with several code blocks (e.g. our [getting started for developers page](https://uitk-site.pages.dev/getting-started/develop)) this makes them indistinguishable when users are browsing the page by listing all buttons (a feature some screenreaders have).
    * We should be able to set a custom label for each code block

**Comment by joshwooding** [comment]
No longer using Docusarus
