### ISSUE TITLE
Improve font loading

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#860]
Currently, the Salt website has a bad case of [FOUT](https://fonts.google.com/knowledge/glossary/fout) when loading. We should optimize the way we load the fonts:

* Can we make the unstyled case less jarring?
    * It seems to be using a serif font, which obviously looks totally different. Can we add some system fonts and `sans-serif` as fallbacks?
    * I think we can setup `@font-face` rules to configure system fonts to have similar metrics to OpenSans by fiddling with letter spacing and stuff like that. The idea is we can have a fallback font that displays immediately but is visually as close as possible to the proper OpenSans font. When that gets swapped in, the change is less noticable and will also cause less layout shifts.
* Can we reduce the download? For example, by:
    * Reducing the number of font files we load by limiting the number of weights and styles we use in our designs
    * Maybe we can [subset the font files](https://fonts.google.com/knowledge/glossary/subsetting) to cut down file sizes
    * Explore using variable font version of OpenSans instead
* Can we improve caching of the font files?
    * There might be some HTTP headers we can configure on the web server to maximise how long browsers will cache the font files, once they have been loaded.

Further reading:

* [How to avoid layout shifts caused by web fonts](https://simonhearne.com/2021/layout-shifts-webfonts/)

**Comment by joshwooding** [comment]
Fixed by #1509
