### ISSUE TITLE
Max-width pages / content

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/salt-ds#878]
Need to decide on behaviours around containing central content for both: 

1. Page view with sidebar and toc

2. Page view without sidebar or toc (including Homepage)

The 'Components' page's content is very wide even on a normal screen. Should prob be contained to a narrower size.

If viewing Homepage on a very large screen some elements are not contained ie: the 'What to expect' bit and the accordion illustration.

**Comment by JohannaJoergensen** [comment]
13 Dec - in progress

**Comment by james-nash** [comment]
I think this has now been fixed by #922. @Fercas123 - can you confirm? If so, we can close this issue

**Comment by james-nash** [comment]
I'm pretty sure this is done - the page content no longer stretches to the full width of the viewport on large screens. Therefore closing this issue.
