### ISSUE TITLE
Some alignment and layout issues when zoomed out

### ISSUE THREAD

**Issue by shinytoyrobots** [jpmorganchase/salt-ds#896]
Fairly minor/edge case (but may want to check on extra large or high res monitors).

When zooming out, there are some layout issues around the logo and the front page imagery.

![screenshot-salt](https://user-images.githubusercontent.com/825457/207382461-30dc7193-ac06-426e-99cb-e176c3e28004.jpg)

**Comment by james-nash** [comment]
Thanks for raising this. @jeanlaleuf had previously reported this issue too. Hopefully, the work we do for #878 will fix this issue too.
