### ISSUE TITLE
Site: Bare domain needs to be redirect

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#944]
Currently, both the "bare" `https://saltdesignsystem.com/` and `https://www.saltdesignsystem.com/` serve up the site (i.e. return HTTP 200).

Duplicate URLs are bad for SEO. We have chosen `https://www.saltdesignsystem.com/` as our canonical URL, so we should configure things (presumably on Cloudflare) to make `https://saltdesignsystem.com/` a permanent HTTP 301 redirect to the `www.` canonical URL.

**Comment by joshwooding** [comment]
Just curious, where did you see this method is bad for SEO? Cloudflare uses this approach for their website.

**Comment by joshwooding** [comment]
Should be done now
