### ISSUE TITLE
Site: Document our coding conventions

### ISSUE THREAD

**Issue by james-nash** [jpmorganchase/salt-ds#957]
We should document the conventions we use in our site's code, such as [separating content from component code](https://github.com/jpmorganchase/salt-ds/issues/954) and [how we organise our source files](https://github.com/jpmorganchase/salt-ds/issues/956).

Ideally, this should be captured in markdown file(s) that reside directly in the relevant source directories, to ensure that developers see them when they need to.

**Comment by parsakhan21** [comment]
1/31 - started on this today

**Comment by JoanaMMoreira** [comment]
PR ready for review: https://github.com/jpmorganchase/salt-ds/pull/1074
