### ISSUE TITLE
Link is supplying excessive text override

### ISSUE THREAD

**Issue by origami-z** [jpmorganchase/salt-ds#981]
### Package name(s)

Core v1.0.0 (@salt-ds/core)

### Description

When Link is used within certain HTML elements (e.g. `<code>`, `<h2>`, some text properties (e.g. font size, font family) are overridden.

Also `<Text as="p" styleAs="h2">` and `<H2>` display very differently...?

### Steps to reproduce

Some comparisons  between `<Link>` and native `<a>` in below StackBlitz example
https://stackblitz.com/edit/salt-template-sdyjsx?file=App.tsx

```
<Text>
  In a Salt Text component,{' '}
  <code>
    <Link href="https://www.google.com" target="_blank">
      Link within code
    </Link>
  </code>{' '} different font family
</Text>
```

![link within code](https://user-images.githubusercontent.com/5257855/210181586-b5ef7faf-f1af-4a5c-886f-5b76ba90586e.png)

```
<Text as="p" styleAs="h2">
  This is a <code>styleAs</code> h2 Text,{' '}
  <Link href="https://www.google.com" target="_blank">
    Link
  </Link>
  {' '}
  has wrong font size
</Text>
```

![link within p styled as h2](https://user-images.githubusercontent.com/5257855/210181598-fb1fd45c-0a7e-4777-a6b1-3063260fe369.png)

### Expected behavior

- Font size matches parent element, e.g. in `h2`.  
- Font style / family stays the same, e.g. in `code`
- `<Text styleAs="h2">` display the same as `<H2>`

### Operating system

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

### Browser

- [X] Chrome
- [X] Safari
- [ ] Firefox
- [ ] Edge

### Are you a JPMorgan Chase & Co. employee?

- [X] I am an employee of JPMorgan Chase & Co.

**Comment by alycrys** [comment]
Fixed
