### ISSUE TITLE
Site: research Storybook component functionality

### ISSUE THREAD

**Issue by EleanorHaproff** [jpmorganchase/salt-ds#984]
We need to move our component documentation from Storybook into the website. The text content is already MDX and should therefore be relatively easy to migrate. However, Storybook provides additional functionality for documenting components that does not currently exist for the site, such as:

- live component demos 
- prop tables auto-generated from the component source code
- css classes / charcteristics tables 

This task is to:

- Research how we might replicate that kind of functionality within the site
- Identify any other relevant functionality that we have in Storybook and will need to replicate within the site

**Comment by JohannaJoergensen** [comment]
18 Jan - in progress; almost done
